### ISSUE TITLE
VideoTileGrid not rendering Preview 

### ISSUE THREAD

**Issue by mshahzaib101** [aws/amazon-chime-sdk-component-library-react#163]
When i join 2 users using this library, then there audio gets connected but video is not connecting .
The view of the web app remain same, it didnt open VideoTileGrid component..

here is how i use it..
` <ThemeProvider theme={lightTheme}>

      <MeetingProvider>
             <VideoTileGrid />
                         <App />
      </MeetingProvider>
</ThemeProvider>`

**Comment by danial424** [comment]
+1

**Comment by azharsalmaan** [comment]
facing the same issue.

**Comment by mshahzaib101** [comment]
just resolved the issue, 
I was unable to see the video preview because no one(atandee) was sharing his video..
So i created a video share Button and after that other users were able to se the video preview
`
import { MeetingProvider, useLocalVideo } from "amazon-chime-sdk-component-library-react";

function MeetingPage() {
  const { toggleVideo } = useLocalVideo();

  return (
    <MeetingProvider>
      <App>
        <div style={{ border: "2px solid red", height: "100vh" }}>
          <button onClick={toggleVideo}>share video</button>
          <VideoTileGrid noRemoteVideoView={<div>No one is sharing his video</div>} />
        </div>
      </App>
    </MeetingProvider>
  );
}
`

**Comment by mshahzaib101** [comment]
just resolved the issue, 
I was unable to see the video preview because no one(atandee) was sharing his video..
So i created a video share Button and after that other users were able to see the video preview



        import { MeetingProvider, useLocalVideo } from "amazon-chime-sdk-component-library-react";

        function MeetingPage() {
        const { toggleVideo } = useLocalVideo();

        return (
         <MeetingProvider>
            <App>
                <div style={{ border: "2px solid red", height: "100vh" }}>
                     <button onClick={toggleVideo}>share video</button>
                     <VideoTileGrid noRemoteVideoView={<div>No one is sharing his video</div>} />
                 </div>
           </App>
           </MeetingProvider>
          )}

**Comment by bradmanAWS** [comment]
Glad it's resolved! Closing this issue.

**Comment by bradmanAWS** [comment]
We will update the documentation to make this more clear.
