### ISSUE TITLE
Links in some documentaion are invalid

### ISSUE THREAD

**Issue by kaaaren** [aws/amazon-chime-sdk-component-library-react#176]
### What are you trying to do?

Check the repo documentation.

### How can the documentation be improved to help your use case?

Some links in documentation are invalid. 

### What documentation have you looked at so far?

For example: 
1. introduction to components: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/introduction.stories.mdx, all links are broken
2. AudioInputProvider: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/DevicesProvider/docs/AudioInputProvider.stories.mdx

We need to fix the link pattern (i.e. `/?path=/docs/ui-components-badge--basic-badge`) used in all places

**Comment by michhyun1** [comment]
Im on it, will post a PR shortly

**Comment by michhyun1** [comment]
https://aws.github.io/?path=/docs/introduction--page

Visit our public documentation page, and then try the links. We don't access the links from the github repo

**Comment by kaaaren** [comment]
I see, thanks for clarifying! Closing issue.
