### ISSUE TITLE
useDevicePermissionStatus() returning UNSET after permissions are granted

### ISSUE THREAD

**Issue by brianleipprandt** [aws/amazon-chime-sdk-component-library-react#179]
### Describe the bug
_useDevicePermissionStatus_ doesn't return correct permission status after granting permissions

### Steps to reproduce:
1. Modify the demo/meeting application, add <DevicePermissionPrompt /> to src/views/DeviceSetup/index.tsx
2. Optional: Add logging to useDevicePermissionStatus which writes-out the current value of permission.
3. In Chrome, ensure your AV permissions are initially set to "ask"
4. Start a demo meeting.

**Expected Behavior**: After accepting permissions, the permission will be equal to '**GRANTED**'
**Actual Behavior**: Permissions go through the following states: UNSET => GRANTED => IN_PROGRESS.  At this point the prompt appears & the check shows "Unable to get device labels".  After clicking 'Allow', the state will transition to '**UNSET**'.

Note that if you reload after allowing permissions, you will correctly get state 'GRANTED'.

### Reproducible on the following devices
* Chrome + Mac desktop
* Safari + Mac desktop

## Other notes
Besides returning incorrect results, this API also doesn't allow the client application to distinguish between audio and video permissions. For instance, there is no way to tell when someone has allowed audio permissions, but has denied the video permissions.

**Comment by p-foucht** [comment]
Hi brianleipprandt,

You're right, there was some bad logic in the label trigger setup. I have a PR out to fix the issue [here](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/180).

That's a good point on the separate audio/video permissions. This PR doesn't address that, but we'll think of a way to address that.

Thanks for pointing both of these issues out!

**Comment by p-foucht** [comment]
PR pushed -closing this ticket. We'll keep in mind the audio/video permissions, feel free to open another ticket if you want to file and track it separately
