### ISSUE TITLE
Add audioVideo to useLocalAudioInputActivityPreview dependencies

### ISSUE THREAD

**Issue by shanepadgett** [aws/amazon-chime-sdk-component-library-react#182]
**Describe the bug**
Since audioVideo is not added as a dep of the useEffect in useLocalAudioInputActivityPreview, it is possible for the hook to not work because audioVideo is not set before the default device is set. By adding audioVideo as a dep, I was able to correct this issue.

**To Reproduce**
1. Create an app that uses the library
2. Setup a default meeting and join/start it in a top level component.
3. Use the MicSelection component and useLocalAudioInputActivityPreview hook as a direct child of the component setting up the meeting. Notice on initial load, it will set the mic input to the default device, but the ref you setup for the hook will not scale.

**Expected behavior**
Element ref should scale when audioVideo is initialized.

**Desktop (please complete the following information):**
 - OS: maxOS 10.14.6
 - Browser all

**Smartphone (please complete the following information):**
 - Version all

**Additional context**
We are creating storybook stories with the components we develop using your hooks and providers. We render them as direct children under a meeting initializer and I dont think audioVideo is being initialized before the hook is used.

**Comment by p-foucht** [comment]
Hi shanepadgett,

You're right - this does look a bug. I'll submit a PR to get this updated.

**Comment by p-foucht** [comment]
[PR posted here](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/192)

**Comment by p-foucht** [comment]
Merged - resolving
