### ISSUE TITLE
Add hook similar to useLocalAudioInputActivityPreview

### ISSUE THREAD

**Issue by shanepadgett** [aws/amazon-chime-sdk-component-library-react#183]
We would like to have a hook added that is similar to useLocalAudioInputActivityPreview, but instead of taking in an element ref to scale it, we would like to get the decimal value back as a return. We have our own component with custom logic that doesn't scale, but still needs access to this decimal value.

**Comment by p-foucht** [comment]
This makes sense. We'll look into adding this, or adjusting how the existing hook works so that it can be better extended

**Comment by p-foucht** [comment]
I'll be putting out a PR that adjusts `useLocalAudioInputActivityPreview` to take a third optional param for custom callbacks

`useLocalAudioInputActivityPreview(null, null, cb)`

Will that work for your use case?

**Comment by p-foucht** [comment]
[PR here](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/192) if you'd like to review or provide any suggestions

**Comment by shanepadgett** [comment]
Personally I don't like this pattern. It seems to me like the mic monitor logic could be separated out and both this and another hook could exist that do different things. The naming of this hook suggests it does preview work, i.e. scaling. I think another should exist for simply getting the value to us to do something with.

**Comment by p-foucht** [comment]
Those are good points -- I'll create a separate `useLocalAudioInputActivity` hook that just provides the value. I'll update the PR

**Comment by p-foucht** [comment]
[Changes](https://github.com/aws/amazon-chime-sdk-component-library-react/commit/bf847401cccb129aa376bbac37c277f2f649c12d) merged in. Resolving
