### ISSUE TITLE
Default Input (Mic) Device Disconnect Issue

### ISSUE THREAD

**Issue by shanepadgett** [aws/amazon-chime-sdk-component-library-react#189]
**Describe the bug**
To preface, we are somewhat mirroring your logic for your mic selection component, but we handle when an active device is disconnected to make sure a new device takes over. Yours currently does not do this and mic input simply stops working if you disconnect the active device.

In our implementation, if the current selected device is the (default) device, when you disconnect that device and another (default) device is selected, the mic input no longer works.

However, as long as the device you have selected is not marked as (default), when you disconnect is and the default device is set, things are working well.

The method that is called to select the new audio input (selectAudioInputDevice) -- on the meeting manager -- needs to take into account that default might be submitted again if the device that is default changes.

**To Reproduce**
The reproduction steps that are listed below but they are a bit misleading. Because you mic selection component useEffect doesn't take into account the active device disconnecting, it never calls the selectAudioInputDevice via onChange since you have a guard clause in the useEffect if there is already a selectedDevice. 

1. Launch the provided demo app
2. Use a pair of headphones or another mic and set it as the default device on your computer.
3. Put in details to start a meeting which takes you to the device selection page.
4. Verify that your headphones are shown as a (default) device in the mic dropdown and that they are selected.
5. Disconnect your headphones, and watch as a new (default) device takes over. When this happens, the mic input no longer works. 

**Expected behavior**
When you call selectAudioInputDevice on meeting manager with a deviceId of 'default', if the currently selected device is already default it should handle this and close the previous mic session and open a new one with the new default device.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: macbook pro
 - OS: macOS 10.14.6
 - Browser all

**Comment by p-foucht** [comment]
We had planned to add similar functionality (handling dropped devices) actually. Thanks for the detailed write-up, we'll look into getting this fixed

**Comment by ronork** [comment]
When we build the package the implementation of hooks goes missing from the code...is this intentional???
<img width="1193" alt="Screenshot 2020-09-09 at 9 27 57 PM" src="https://user-images.githubusercontent.com/20018997/92623006-55d8f000-f2e3-11ea-85a1-13ba33b5b8f1.png">

**Comment by nicklera1** [comment]
> When we build the package the implementation of hooks goes missing from the code...is this intentional???

Hi @ronork,

Based on your screenshot you are looking at the the [TypeScript Declaration](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) file which just describes the object and the actual implementation is in `lib/index.js`.  Please take a look at our [interactive component documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usetogglelocalmute--page) for examples and description of each components, providers and hooks.

**Comment by ronork** [comment]
Ok Got it..you are right I figured that I misunderstood the docs...then i
guess its not working for me..and its failing silently so can you suggest a
way i could debug this.
Just FYI I am able to create and join the meeting and this *Microphone*
Component is wrapped inside *ConfigBar* which in turn in wrapped in
*MeetingProvider*
[image: Screenshot 2020-09-09 at 10.02.14 PM.png]
[image: Screenshot 2020-09-09 at 10.00.20 PM.png]

**Comment by p-foucht** [comment]
There were similar issues reported to the Chime SDK (specifically around the **default device ID**), that should have been addressed in recent versions. Could you update to the latest version of the JS SDK and see if the issue persists?

If it does persist after updating the JS SDK, could you include info level logs?

**Comment by shanepadgett** [comment]
We tried by updating the chime sdk but it did not resolve the issue.

**Comment by p-foucht** [comment]
Hey @shanepadgett, please check out the above mentioned PR. If possible, it would be great if you could start the demo app from the PR and confirm if it addresses your issue

**Comment by shanepadgett** [comment]
> Hey @shanepadgett, please check out the above mentioned PR. If possible, it would be great if you could start the demo app from the PR and confirm if it addresses your issue

Looking into it

**Comment by p-foucht** [comment]
I believe this was addressed in the above linked commit that was released. Please re-open if you still experience the issue

**Comment by shanepadgett** [comment]
Just commenting a bit late on this to confirm that it was indeed fixed by this PR. Thanks!
