### ISSUE TITLE
useToggleLocalMute not working when audioVideo initialized after component mounts

### ISSUE THREAD

**Issue by brianleipprandt** [aws/amazon-chime-sdk-component-library-react#190]
**Describe the bug**
If you have a component that uses the 'useToggleLocalMute' hook prior to audioVideo being initialized, you will see 2 issues:
1. The hook useToggleLocalMute doesn't re-initialize the muted state when audioVideo is changed.  
2. The toggleMute callback doesn't listen for audioVideo changes so if a component using this hook is mounted before AV exists, pressing the toggle will do nothing.

**To Reproduce**
1. Create an app that uses the library
2. Setup a default meeting and join/start it in a top level component.
3. Use useToggleLocalMute hook as a direct child of the component setting up the meeting. 
4. Attempt to mute using your component.  Nothing will happen

**Expected behavior**
Using the toggleMute button will toggle the mute status & mute the call

**Additional context**
We are creating storybook stories with the components we develop using your hooks and providers. We render them as direct children under a meeting initializer and I dont think audioVideo is being initialized before the hook is first used.

**Comment by brianleipprandt** [comment]
Created a PR #191 with a fix.

**Comment by p-foucht** [comment]
Approved the PR, thanks for contributing! Closing the ticket but feel free to re-open if needed
