### ISSUE TITLE
Unable to use SDK Hooks as specified in the documentation

### ISSUE THREAD

**Issue by ronork** [aws/amazon-chime-sdk-component-library-react#195]
I was trying to use the useToggleLocalMute hook as specified in the docs and observed that the definition for the same is missing...went on to look for other such hooks couldn't find any..is there something i misunderstood or these missing hooks intentional?
<img width="1216" alt="Screenshot 2020-09-09 at 9 32 20 PM" src="https://user-images.githubusercontent.com/20018997/92623518-f29b8d80-f2e3-11ea-9656-8618fe7e02e4.png">

**Comment by nicklera1** [comment]
Hi @ronork,

Based on your screenshot you are looking at the the [TypeScript Declaration](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) file which just describes the object and the actual implementation is in `lib/index.js`.  Please take a look at our [interactive component documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usetogglelocalmute--page) for examples and description of each components, providers and hooks.

**Comment by ronork** [comment]
> Hi @ronork,
> 
> Based on your screenshot you are looking at the the [TypeScript Declaration](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) file which just describes the object and the actual implementation is in `lib/index.js`. Please take a look at our [interactive component documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usetogglelocalmute--page) for examples and description of each components, providers and hooks.

Thanks @nicklera1 you are right I just checked thanks for the quick reply, so why is this hook not working also I dont se any errors its not re rendering my component on click so I dont understand what I am doing wrong

This is where I am trying to use it

<img width="1168" alt="Screenshot 2020-09-09 at 10 07 16 PM" src="https://user-images.githubusercontent.com/20018997/92627333-d3ebc580-f2e8-11ea-904c-67270682fb32.png">

This Microphone Component is wrapped in Congfig Bar which inturn is wrapped in Meeting Provider.
FYI:I am able to create this meeting and even join it but the hooks seems no to work


<img width="1195" alt="Screenshot 2020-09-09 at 10 07 54 PM" src="https://user-images.githubusercontent.com/20018997/92627390-eb2ab300-f2e8-11ea-89c5-6645948d0a91.png">

**Comment by nicklera1** [comment]
On second screenshoot line #38 you don't have to use [AudioVideoProvider](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-audiovideoprovider--page) but instead you can import `[useAudioVideo](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useaudiovideo--page)` where needed this also might have side effect by using it. Every child component of `MeetingProvider` can use the `useAudioVideo` hook.

**Comment by ronork** [comment]
I think the audioVideo instance is initally null which gets retained even though its valur get updated as in the callback it somehow refers to the first instance..let me know if i am wrong.

<img width="873" alt="Screenshot 2020-09-10 at 9 31 46 AM" src="https://user-images.githubusercontent.com/20018997/92680434-76876100-f348-11ea-980b-6759e60c61b9.png">

**Comment by ronork** [comment]
To fix that I had to add a hook to wait till the AudioVideo instance is available on page load and then everything started to work.

<img width="614" alt="Screenshot 2020-09-10 at 9 49 14 AM" src="https://user-images.githubusercontent.com/20018997/92681292-e5fe5000-f34a-11ea-800a-10b36ba389d3.png">

**Comment by nicklera1** [comment]
Yes! We will update our hooks documentation to better inform developers of its usage context.
