### ISSUE TITLE
Undocumented issues

### ISSUE THREAD

**Issue by gkio** [aws/amazon-chime-sdk-component-library-react#199]
Please document that hooks 
```
  useToggleLocalMute
  useLocalVideo
```
need to be rendered when meeting has been started 
```
const meetingStatus = useMeetingStatus();
const isMeetingStarted = meetingStatus === MeetingStatus.Succeeded;
```

and also the `<LocalVideo />` because i spend 2 days to figure out why mute and LocalVideo does not work

**Comment by nicklera1** [comment]
Thank you @gkio for you feedback! we will add documentation related to SDK hooks and its usage context.

**Comment by nicklera1** [comment]
Related to https://github.com/aws/amazon-chime-sdk-component-library-react/issues/195

**Comment by ronork** [comment]
Is there any way of using **Sending and Receiving data messages** feature of  
**amazon-chime-sdk-js** while using the react component library??

**Comment by p-foucht** [comment]
Documentation was added, resolving
