### ISSUE TITLE
MeetingManager.start() fails

### ISSUE THREAD

**Issue by spencekim** [aws/amazon-chime-sdk-component-library-react#201]
**Describe the bug**
After submitting the device testing form in the join pre-meeting flow, the following message shows up on the error modal:

"Unable to join meeting
There was an issue finding that meeting. The meeting may have already ended, or your authorization may have expired.
Failed to construct 'URL': Invalid URL"

I believe this has to do with line 135 in the SDK file "MeetingManager.ts". 

**Screenshots**

<img width="612" alt="Screen Shot 2020-09-12 at 1 34 19 PM" src="https://user-images.githubusercontent.com/19200359/93004575-0cfc8380-f4fd-11ea-8680-301d4ef4c42f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome

**Comment by JesusCamaRay** [comment]
Hi, i have the same issue. What should i write in meeting ID? Thanks
