### ISSUE TITLE
Expose useDevicePermissionStatus hook

### ISSUE THREAD

**Issue by benho-athena** [aws/amazon-chime-sdk-component-library-react#204]
We saw a very handy hook in your demo project for getting the status of device permissions: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/332f0c0cfcf4f9d338cba24165c15036b8d27805/demo/meeting/src/hooks/useDevicePermissionStatus.tsx

Could you move this hook out of the demo project and into the SDK, and export it?

**Comment by p-foucht** [comment]
We'll add this as an exported item. Until it gets merged/released, feel free to copy the code snippet if needed before then

**Comment by p-foucht** [comment]
Hi @benho-athena 

Long overdue, but we'll be adding this as we move over to V2.0. We'll update here when it has been released

**Comment by p-foucht** [comment]
2.0 has been pushed and we've [exposed this hook](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/index.ts#L139), closing
