### ISSUE TITLE
There are 2 components with the same name being exported

### ISSUE THREAD

**Issue by davejlane** [aws/amazon-chime-sdk-component-library-react#205]
**Describe the bug**
2 components:
* https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/icons/ContentShare/index.tsx
* https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/sdk/ContentShare/index.tsx

Both are exported with the same name. I suspect this got missed as the icons are imported using wildcard matching.

**To Reproduce**
1. Create a component.
2. import { ContentShare } from 'amazon-chime-sdk-component-library-react'
3. Observe that it is not the icon component.

**Expected behavior**
I would expect that every component in the library has a unique name so that they can be referenced. 

**Additional context**
Naming suggestion for the icon : `ScreenShare`.

**Comment by p-foucht** [comment]
Hi @davejlane,

Thanks for submitting an issue as well as a great alternative name. We'll address this ASAP
