### ISSUE TITLE
Provide ability to disable active speaker styling in VideoTileGrid.

### ISSUE THREAD

**Issue by spencekim** [aws/amazon-chime-sdk-component-library-react#211]
**Describe the bug**
In the VideoTileGrid, the active speaker remote video tile is given special styling in the grid. This styling change is mandatory, which is problematic for some use cases. It would be great to have a activeSpeakerLayout = false prop or something similar to make this behavior optional. 

**Desktop (please complete the following information):**
 - Browser: Chrome, Safari, Firefox

**Comment by p-foucht** [comment]
Hi @spencekim 

You're right - we should be allowing this. I've [opened a PR](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/221) to allow for a layout prop

**Comment by p-foucht** [comment]
PR merged, it will be available in our next NPM release likely next week

**Comment by kodai305** [comment]
Is there an option to highlight the tile of the video?
