### ISSUE TITLE
[Docs] ControlBarItem vs ControlBarButton 

### ISSUE THREAD

**Issue by LoganArnett** [aws/amazon-chime-sdk-component-library-react#216]
### What are you trying to do?
In looking through the storybook I found that I can use a `ControlBarItem` component to add custom options to the `ControlBar` but when I go to import this component it does not exist. Going to the source code there is a file named `ControlBar/ControlBarItem.tsx`, however, the component within is named `ControlBarButton`. In issues and examples it is referenced in both ways. It seems like this should be cleaned up.

### How can the documentation be improved to help your use case?
Selecting one name for the ControlBarItem/ControlBarButton component and updating the references

### What documentation have you looked at so far?
Chime SDK and this library

**Comment by p-foucht** [comment]
PR merged :)
