### ISSUE TITLE
Angular version

### ISSUE THREAD

**Issue by sialcasa** [aws/amazon-chime-sdk-component-library-react#222]
Hello AWS team,

are there any plans to release an Angular implementation or a WebComponents version of this library?

Thank you

**Comment by p-foucht** [comment]
Hi @sialcasa, 

At the moment, it is not on our immediate roadmap. I wouldn't rule them out though, as our roadmap is often driven from customer interest/need. I'll be sure to let you know if there are any updates

**Comment by hassanrazakhalid** [comment]
+1 for Angular Components. Please
