### ISSUE TITLE
Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & RefAttributes<HTMLButtonElement>'

### ISSUE THREAD

**Issue by rjjlucy** [aws/amazon-chime-sdk-component-library-react#223]
**Describe the bug**
```
Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & RefAttributes<HTMLButtonElement>'
```
I see this error in the developer console when I add **onClick** prop for Button component or ModalButton component. However, the **onClick** event actually works with this error display.

**To Reproduce**
The following is my snippet 
```
        <ModalButtonGroup
          primaryButtons={[
            <ModalButton
              label={intl.formatMessage({ id: 'MeetingInformation.Done' })}
              variant="primary"
              closesModal
            />
          ]}
          secondaryButtons={[
            <Button
              label={intl.formatMessage({ id:
                  isCopied? 'MeetingInformation.Copied' : 'MeetingInformation.CopyAll' })}
              variant="secondary"
              onClick={handleCopyInfo}
            />
          ]}
        />
```
For `secondaryButtons`, no matter I use **ModalButton** or **Button**, as long as I add **onClick** prop, I can see this error.

**Expected behavior**
No error should observed.

**Comment by bradmanAWS** [comment]
This had been resolved! Please reopen this issue if you are still experiencing this behavior.
