### ISSUE TITLE
suppress prompts for input device permissions

### ISSUE THREAD

**Issue by TGod-Ajayi** [aws/amazon-chime-sdk-component-library-react#240]
I am looking for a way to suppress input device permissions when an attendee joins a meeting,
I am creating a record bot and I need the input device permissions to be suppressed when the bot joins the meeting

**Comment by p-foucht** [comment]
This isn't something that is currently supported. If you have control over the browser environment that the bot is running, you could look into [disabling the permission](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/facd71735d1464c0b0d82c31e431d79afec8b0a8/recording/run.sh#L43)

**Comment by TGod-Ajayi** [comment]
Thank you I am currently using this https://github.com/aws-samples/amazon-chime-live-events/blob/master/transcoding/run.sh
and i can see it is disabled here too
