### ISSUE TITLE
Chat Documentation in StoryBook 

### ISSUE THREAD

**Issue by pawanlakhera77** [aws/amazon-chime-sdk-component-library-react#244]
Please provide Documentation for implementing Chat function in Amazon Chime using React SDK Library.

Also if there is no Components available in React SDK for a particular functionality how can we create that using Amazon Chime JS SDK . ( I mean what is needed to be imported and where should we write the normal Amazon Chime JS SDK - Inside Meeting provider or Outside).
Thanks

**Comment by p-foucht** [comment]
There aren't currently any components for it. If you're referring to data messages referenced in the chime SDK, you will need to access the `audioVideo` reference via the `useAudioVideo` hook. The `audioVideo` reference is available once a meeting session has started, and it must be accessed in a component nested within the MeetingProvider. Once you have access to the audioVideo object, you can use the APIs for [data messages](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional)

**Comment by pawanl77** [comment]
@p-foucht I am using this in my React Functional Component like :     

const sendMessage = () => {
      new AsyncScheduler().start(() => {
         meetingManager.audioVideo.realtimeSendDataMessage('chat', "hello", 3000);
      });
   };

   const setupDataMessage = () => {
      meetingManager.audioVideo.realtimeSubscribeToReceiveDataMessage('chat', (dataMessage) => {
         //loading my Component here
         history.push('/');
      });
   }

   if (meetingStatus) {
      setupDataMessage();
   }


It is breaking the meeting for the other attendees . Is there any workaround ?

**Comment by p-foucht** [comment]
You shouldn't need to use `AsyncScheduler`. What exactly are the error logs you're seeing?

I believe something like this might work -- 
```
const audioVideo = useAudioVideo();

useEffect(() => {
  if (!audioVideo) return;

  audioVideo.realtimeSubscribeToReceiveDataMessage('topic', callback);

  return  () => cleanupHere();
}, [audioVideo])
```

This hook will run when an audioVideo instance is updated, so you can perform your setup here.  To send messages, you would do something like this

```
const audioVideo = useAudioVideo();

function sendMessage(message) {
  if (!audioVideo) return;

  audioVideo.realtimeSendDataMessage(...);
}

return <button onClick={sendMessage('hello')} />
```

**Comment by nicklera1** [comment]
@pawanl77 For Chat Related components and it's use please checkout this newly published demo https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/chat

**Comment by vidya-mohan** [comment]
@pawanlakhera77 please check out the demo application that @nicklera1 shared

**Comment by arpitprod** [comment]
> @pawanl77 For Chat Related components and it's use please checkout this newly published demo https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/chat

This link is not exist. What is updated link

**Comment by ziyiz-amzn** [comment]
Thank you @arpitprod. You can find the chat demo in https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat

**Comment by arpitprod** [comment]
Thank you for your timely reply.
