### ISSUE TITLE
Checkbox within a FormField does not render as expected

### ISSUE THREAD

**Issue by abey-george** [aws/amazon-chime-sdk-component-library-react#247]
**Describe the bug**
When using a Checkbox inside a FormField, the visual rendering shows the label before the checkbox. This is unexpected, and differs from the behavior seen in the Storybook based docs, where the checkbox is rendered before the label.

**To Reproduce**
1. Go to this standalone repro here: https://stackblitz.com/edit/react-ts-chime-ui-component
2. See that the checkbox is rendered after the "Acknowledge" label
3. Note: There is some other styling issue as well in the standalone repro, where the "tick mark" SVG is scaled up, but in the original project where I first saw this problem, I do not have the issue with scaled up SVG, just the ordering issue.

**Expected behavior**
Expect to see the checkbox first and then the label.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 86.0.4240.80 (Official Build) (x86_64)

**Additional context**

**Comment by michhyun1** [comment]
Thanks for bringing this to our attention. I've submitted a PR that should fix this issue! We'll track that PR and once it is merged, we'll close this issue. If you still experience that same issue afterwards, please feel free to reopen a ticket
