### ISSUE TITLE
new "Focusable" interface

### ISSUE THREAD

**Issue by alpjor** [aws/amazon-chime-sdk-component-library-react#252]
In the design of the Roster lists, it's the RosterCell that's focused with the keyboard navigation, and not the options button, inside the RosterCell. The design requests accessible keyboard navigation of long Roster lists and wants to prevent having to tab through each entry 1-by-1 by supporting tabbing across sections (RosterGroups), and using arrow-key navigation to go through each entry (RosterCell). To support these features I propose a new "Focusable" Interface that can be given to components like RosterCell that gives access to "tabIndex", "onFocus", and "onBlur" methods. This interface can be implemented by other components like Button that also support these features, and we can remove "tabIndex" from BaseProps.

**Comment by p-foucht** [comment]
[PR](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/254)
