### ISSUE TITLE
Question: Join meeting without turning on the camera?

### ISSUE THREAD

**Issue by LoganArnett** [aws/amazon-chime-sdk-component-library-react#261]
Currently when I run `meetingManager.join()` the camera is turned on by default. Is it possible to to join without turning on the camera and allow the user to test their camera if they choose to?

**Comment by devalevenkatesh** [comment]
Hello @LoganArnett ,

Yes, it is possible to join a meeting without turning the camera on. Are you talking about the [demo meeting app](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting)? If so, the app goes through below steps where you get the experience of joining the meeting with video preview on, on the device setup page.

1. `meetingManager.join()` is called which routes the app to load the [`DeviceSetup`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/98019825c2e84925ddecc9c046b320d1bd081697/demo/meeting/src/app.tsx#L37) component.
2. The `DeviceSetup` renders below tree:
2.1. Renders `DeviceSelection`.
2.2. Then it renders `CameraDevices`.
2.3. Then it renders `VideoPreview` which uses component library's [`PreviewVideo`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/98019825c2e84925ddecc9c046b320d1bd081697/demo/meeting/src/components/DeviceSelection/CameraDevices/index.tsx#L30) component. If you check this component, it [chooses the video input](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/98019825c2e84925ddecc9c046b320d1bd081697/src/components/sdk/PreviewVideo/index.tsx#L39) and [starts the video preview for the provided video element](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/98019825c2e84925ddecc9c046b320d1bd081697/src/components/sdk/PreviewVideo/index.tsx#L41). Hence you get the video right away.

To control this you could simply conditionally render the `PreviewVideo` component in the [`CameraDevices`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/98019825c2e84925ddecc9c046b320d1bd081697/demo/meeting/src/components/DeviceSelection/CameraDevices/index.tsx#L15) component.

> Note: You will need to update your demo app copy.

Example pseudo-code:
```js
const CameraDevices = () => {
  const [showPreview, setShowPreview] = useState(false);

  const startPreview = () => {
    setShowPreview(true);
  }
 return {
  <div>
   <Label style={{ display: 'block', marginBottom: '.5rem' }}>
     Video preview
   </Label>
   <button onClick={startPreview}>Start Preview</button>
   {showPreview && <PreviewVideo />}
  </div>
 };
}
```

Please let us know if this helps or you need more information.

**Comment by LoganArnett** [comment]
@devalevenkatesh I am currently not using the demo, just the library and I am still seeing the camera light turn on even when I am not running the preview logic anywhere

**Comment by devalevenkatesh** [comment]
Ok ok, It would be helpful if you provide some steps to re-produce and tell us more about how you are using the components, which components are you using?

**Comment by LoganArnett** [comment]
@devalevenkatesh I am creating a sandbox now will link shortly

**Comment by LoganArnett** [comment]
I have this Sandbox where there are no video elements added, it is the bare minimum demo with the `MeetingProvider` and a call to create a meeting and attendee and to join then immediately start, I have removed my actual API url for the meeting creation but you can of course fill that in with whatever you use.

https://codesandbox.io/s/bold-pascal-cogde

**Comment by LoganArnett** [comment]
@devalevenkatesh is there anything else that can be looked at here? This is a major issue for me with granting audio only access and still seeing camera light coming on

**Comment by nicklera1** [comment]
Hi @LoganArnett ,

Looking at the [MettingManager](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f302b2aeced728099e2f84b325f0491b5fc03d7a/src/providers/MeetingProvider/MeetingManager.ts#L312)  I see that we setting videoInputDevices during MettingManager Initialization phase. You could look there to modify the code and set to `null` to prevent camera (videoInput) being included. 

Hopefully this will unblock you. Please let me know if anything else I can help you.

**Comment by alexander-teemyco** [comment]
Hi @nicklera1 ,

I'm a Software Developer of another team who also need to start meeting with turned off camera.

You wrote:
> You could look there to modify the code and set to `null` to prevent camera (videoInput) being included.

How we can modify `MeetingManager` logic and still continue using of all other Chime React components?

One of our attempt was creating new logic using inheritance of `MeetingManager`.

We've tried to do something similar to `AudioVideo` documentation: https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-audiovideoprovider--page

But there was a problem that we cannot override `MeetingManager` in `MeetingContext` to continue usage of all other Chime React components that depend on `MeetingManager`.

`MeetingContext` is exported here:
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/5b4bb2fc3d1172a4c1ebae4c1f9d27db74d0d0c1/src%2Fproviders%2FMeetingProvider%2Findex.tsx#L25

But `MeetingContext` is not exported then here:
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c37cc41c8c5e1c8f88f35ad26d44013b0deb0af8/src%2Findex.ts#L109

So our attempt failed.

Can you please specify how we can change `MeetingManager` as you suggested?

**Comment by Jason-Reich** [comment]
@devalevenkatesh (or anyone) I went to the codesandbox that @LoganArnett made and I replaced his line

`  const { data } = await axios.post("/my-server", {});`

....with the example I happen to be following from https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page

Which is this:

`
    const response = await fetch(
      "<url to properly functioning api from the demo>"
    );
    const data = await response.json();
`

And I was [somewhat] reassured to see that I got the same error I'm getting on my application when I do this. Which is: 

"SyntaxError
Unexpected token < in JSON at position 0"

What is the way to get past this error?

**Comment by p-foucht** [comment]
Issue should be addressed in the above linked PR. It will be available in the next NPM release --  feel free to verify using the demo app

**Comment by p-foucht** [comment]
Fix pushed to NPM - resolving
