### ISSUE TITLE
Unmute Button Not working

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#262]
**Describe the bug**
I found in the Roaster window or in the useAttendeeStatus provider the muted status is not working. 
**To Reproduce**
1. Use Roaster or useAttendeeStatus provider to fetch the Attendees mic,video status.
2. Video Status is fine but the Mic status is always active and sometime i donot get mic staus in useAttendeeStatus.
**Expected behavior**
It should return the MIc status of Attendess properly.

**Comment by devalevenkatesh** [comment]
This seems duplicate of or related to [this issue](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/259). Closing this one, please re-open if this is a different issue. Also check the other issue for updates.
