### ISSUE TITLE
Create Waiting Room

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#263]
### What are you trying to do?

I am trying to create a waiting room for the Attendees just like zoom where Admin can allow Attendees to join the meeting.

### How can the documentation be improved to help your use case?
Include a section for managing the Waiting Room feature.

### What documentation have you looked at so far?

I have gone through the following links but didn't found anything similar to this functionality.
https://docs.aws.amazon.com/chime/latest/APIReference/Welcome.html
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useattendeestatus--page

**Comment by p-foucht** [comment]
That is outside the scope of what this library does, but you could build that functionality with your own setup. You would need a server and some websockets to communicate and manage the events (attendee joins a waiting room, admin moves attendee to meeting, etc), and you would create/start the meeting when the attendee is moved to the meeting. 

Closing, feel free to re-open if needed
