### ISSUE TITLE
Enable/Disable Other's Videos for All Attendees

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#264]
### What are you trying to do?

I am creating an application like classroom where Teacher is only allowed to give access to students to show their screen and share their video and audio when she likes.
### How can the documentation be improved to help your use case?
There is no documentation to add Enable/Disable Other's Videos for the above problem. Is this possible in chime?

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/

**Comment by devalevenkatesh** [comment]
Closing this issue due to it being similar to already filed one. Check [this issue](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/260).
