### ISSUE TITLE
Mute after Meeting Start

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#275]
**Describe the bug**
I am trying to automatically mute everyone after they joins the call. For this I am calling the toggleMute() function just after the meetingManager.start().

I thought that it would mute the audio of anyone joining the meeting. But it is not working as expected. Is there any way to local mute a person after he joins the meeting.

**To Reproduce**
1. Join the Meeting using meetingManager.start()
2. After this call the Mute function to locally mute the person ( toggleMute()  ). This function is fetched by adding :+1: 
const { muted, toggleMute } = useToggleLocalMute();
3. It is not muting the local attendee.

**Expected behavior**
It should mute the local attendee initially.

**Comment by henlamk** [comment]
When using meetingManager, you can access the audioVideo in it and call realtimeMuteLocalAudio, like this:

`meetingManager.audioVideo?.realtimeMuteLocalAudio();`
