### ISSUE TITLE
The check props in PopOverItem does not change color when hovering

### ISSUE THREAD

**Issue by rjjlucy** [aws/amazon-chime-sdk-component-library-react#277]
**Describe the bug**
The check props in PopOverItem component does not change to active color (white) when hovering the item.

**To Reproduce**
<img width="447" alt="CheckMark" src="https://user-images.githubusercontent.com/7172586/98430811-4bc63a00-2065-11eb-9712-5e78f22f0e1b.png">

Add a PopOverItem in PopOver and pass `true` to `check` props. Hovering over the list item, only the item color changes to white. The check marker does not change accordingly.

**Expected behavior**
The check marker should change to active color when hovering the list item

**Comment by p-foucht** [comment]
Closing per Brad's PR above
