### ISSUE TITLE
Add more than name to roster

### ISSUE THREAD

**Issue by LoganArnett** [aws/amazon-chime-sdk-component-library-react#278]
I see the roster provider code and that it only accepts name from an external source but I was wondering if I could add more fields somehow. If I recreate the roster provider and declare it inside of my MeetingProvider will that cause issues? I assume I can rename it and use similar logic but include more user info to display in the roster list

Or is there another way that I am missing?

**Comment by jkelting** [comment]
You can do it, but be careful there are other components, that use the roster provider. Whenever you want your own data to be shown you will have to write the component yourself and import your roster provider.

**Comment by p-foucht** [comment]
This is a valid use case, and a bit of a shortcoming of the RosterProvider. We could probably just [spread the return object](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/332f0c0cfcf4f9d338cba24165c15036b8d27805/src/providers/RosterProvider/index.tsx#L63) from the API call without causing any issues to the existing components that rely on RosterProvider

Would that address your use case?

**Comment by LoganArnett** [comment]
This is basically what I did as a workaround, grabbed the existing provider and made it more flexible

**Comment by LoganArnett** [comment]
But now that custom provider has to go everywhere and is basically doubling up

**Comment by p-foucht** [comment]
Got it -- we can look at getting it added to the RosterProvider, seems like it would be a common need for others too

**Comment by p-foucht** [comment]
Merged above commit, resolving ticket. Feel free to reopen if needed
