### ISSUE TITLE
useActiveSpeakersState is returning Empty Array

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#280]
**Describe the bug**
I am using useActiveSpeakersState to fetch the active speakers in the meeting. But it is returning an empty array irrespective of the users activated in the meeting. I have opened camera and audio of the user still they are not showing as active users.

**To Reproduce**
1. Create Meeting
2. Join 2-3 Attendees
3. Open their Camera and fetch activeUsers it will return null array.

**Expected behavior**
It should return the active users in the meeting.

**Comment by bradmanAWS** [comment]
Hi @pawanl77 , can you please send the logs for this event?

**Comment by 64json** [comment]
I encountered this bug as well, and I believe it is related to https://github.com/aws/amazon-chime-sdk-js/issues/673#issuecomment-690054697.

Whenever the following happens in `useAttendeeAudioStatus` (e.g., `attendeeId` changes or a component using this hook unmounts), `useActiveSpeakersState` stops tracking of the active speaker.
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/d0040ab0f0fa214dd0afdb19ebdc1d04d6afc732/src/hooks/sdk/useAttendeeAudioStatus.tsx#L34


It seems to be a bug on [aws/amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js), and I wonder if there's any workaround for the time being.

**Comment by p-foucht** [comment]
@64json Nice catch, that does look like a bug in the SDK. I'll look into getting that fixed

@pawanl77 Assuming the above is the issue you are running into, this would occur when you are unmounting a component relying on `useAttendeeStatus`/`useAttendeeAudioStatus`. Do you ever get a correct list of active speakers?
