### ISSUE TITLE
Feature request - Simulcast configuration

### ISSUE THREAD

**Issue by alexander-teemyco** [aws/amazon-chime-sdk-component-library-react#286]
Amazon Chime SDK JS allows to use Simulcast.

Here is a documentation: https://aws.github.io/amazon-chime-sdk-js/modules/simulcast.html

Please make possible to use Simulcast in Amazon Chime SDK Component Library React.

From simulcast documentation, we understand that we need to enable 2 options: 

- `MeetingSessionConfiguration.enableUnifiedPlanForChromiumBasedBrowsers`
-  `MeetingSessionConfiguration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers`

We found that this configuration is set in Chime React Component library here:

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f302b2aeced728099e2f84b325f0491b5fc03d7a/src/providers/MeetingProvider/MeetingManager.ts#L169-L173

And that function is called from `meetingManager.join` method:

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f302b2aeced728099e2f84b325f0491b5fc03d7a/src/providers/MeetingProvider/MeetingManager.ts#L130

So looks like we cannot change configuration to enable Simulcast.

**Comment by rishiraj824** [comment]
Hi there, I'm new here and wanted to contribute (been through contribution.md). Can I take a stab at it?

**Comment by p-foucht** [comment]
Added in the above PR, it will be available in the next NPM release. Let me know if you have any comments on the PR

@rishiraj824 Feel free to post PRs for any issues or improvements that are open 👍 

Resolving, feel free to re-open
