### ISSUE TITLE
Allow to pass sourceId to toggleContentShare

### ISSUE THREAD

**Issue by jpalumickas** [aws/amazon-chime-sdk-component-library-react#292]
Hello,

Chime SDK JS `startContentShareFromScreenCapture` has support for providing `sourceId`. This is useful in Electron applications. Would be nice to have this support in `toggleContentShare`

**Comment by p-foucht** [comment]
Hi @jpalumickas 

Sorry for the late response -- This is something we should be supporting and have backlogged. We'll provide any updates on the progress on this ticket

**Comment by jpalumickas** [comment]
Thank you @p-foucht !

**Comment by jing-chen1** [comment]
[#523](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/523) has been merged so closing the issue now. Please feel free to check out the new feature.
