### ISSUE TITLE
AudioInputControl/AudtioOutputContro/VideoInputControl

### ISSUE THREAD

**Issue by zabsalahid** [aws/amazon-chime-sdk-component-library-react#302]
**Describe the bug**
Users needs to click the dropdown under video button and it's giving inconsistent output just to display the video of the user. Label shows that the video is started, but it is not.

**To Reproduce**
1. Start meeting (Video is not yet started)
2. Click the video button (Expectation: it will automatically show the video of the current user, but what actually happens is it can't be started unless you click none on the dropdown and then click again the default video input, and click the video button.
3. AudioInputControl no slash to show that it is muted and the other person can still hear the user.

**Expected behavior**
• When we click the video button it will show the default input video, no need to select from the dropdown
• Microphone can be muted or unmuted

**Screenshots**
![image](https://user-images.githubusercontent.com/6036299/99897308-58889600-2cd3-11eb-840f-ebd967c780ef.png)
![image](https://user-images.githubusercontent.com/6036299/99897313-5e7e7700-2cd3-11eb-8ebb-a30b496be449.png)

**Desktop (please complete the following information):**
 - Chrome, Firefox
 - Version 1.2.0

**Comment by bradmanAWS** [comment]
Hi @zabsalahid, can you provide some more information about this issue? Are you able to reproduce this issue in our demo application? I don't get the same behavior when I tried these steps in our app. Perhaps you could share some of your implementation details so we could assist with the issue.

**Comment by michhyun1** [comment]
@zabsalahid Please refer to the demo app, as the meeting demo does not seem to have this issue. I'll close this ticket as we haven't heard back from you in 19 days, but please re-open this issue if needed.
