### ISSUE TITLE
PopOver with sub menu fails to open sub menu

### ISSUE THREAD

**Issue by abey-george** [aws/amazon-chime-sdk-component-library-react#306]
**Describe the bug**
Clicking on a PopOver item that contains a PopOverSubMenu, fails to open the sub menu.

**To Reproduce**
1. Go to https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-popover--pop-over-menu-with-submenu'
2. Click on the PopOver button.
3. Click on "This is a submenu"
4. Note that it fails to open the submeny

**Expected behavior**
I would expect clicking on "This is a submenu" to open the submenu

**Screenshots**
![image](https://user-images.githubusercontent.com/45127597/100458844-71f25f00-3092-11eb-9893-ed25676f96d7.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 87.0.4280.66 (Official Build) (x86_64)

**Comment by bradmanAWS** [comment]
Hey @abey-george I didn't see you also had a commit to fix this issue. The issue has been fixed here: https://github.com/aws/amazon-chime-sdk-component-library-react/pull/309
