### ISSUE TITLE
ContentShareProvider  is not returning the Remote Share status

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#318]
**Describe the bug**
@codeslinger @hyandell @alpjor As mentioned in the docs in the Storybook that ContentShareProvider  would return the following data
```
{
  // The tile ID of the active content share
  tileId: number | null;

  // Whether or not a remote user is screen sharing
  isRemoteUserSharing: boolean;

  // Whether or not the local user is screen sharing
  isLocalUserSharing: boolean;

  // Whether or not the local user's content share is loading
  isLocalShareLoading: boolean;

  // Whether or not someone in the session (remote, or local) is sharing
  isSomeoneSharing: boolean;

  // The chime attendee ID of the user sharing
  sharingAttendeeId: string | null;
}
```
But when I console the output it only returns 

{
   isLocalShareLoading: false
   isLocalUserSharing: false
   paused: false
   sharingAttendeeId: null
  tileId: null
}

I was trying to get "**isSomeoneSharing**" but i am not able to.

**Expected behavior**
It should return all the values either true or false

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  : Chrome

**Comment by p-foucht** [comment]
The documentation for ContentShareProvider appears to be out of date. We'll get that updated -- sorry for the confusion.

You can detect remote share status by using the `tileId` and `isLocalUserSharing` properties. [See here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/ContentShareProvider/state.tsx#L73)

tileId will tell you there is an availble content share, and isLocalUserSharing will tell you if the content share is local or remote.

Closing but feel free to reopen if needed
