### ISSUE TITLE
Error on selecting video input device

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#319]
**Describe the bug**
I am displaying a list of video input devices to select whichever the user wants to use. 
To get that list, I am calling the meetingManager.videoInputDevices, which correctly returns the list. 
Once I try to switch the video input, using the hook onVideoInputSelected with the according device id, console logs the following error: 

`
[ERROR] SDK - failed to get audio device for constraints {"audio":{"deviceId":{"exact":"0e00293e24a5e696c991dc223f3f482ea1a9ab0219e36bea6588e65579c35e82"},"echoCancellation":true,"googEchoCancellation":true,"googAutoGainControl":true,"googNoiseSuppression":true,"googHighpassFilter":true,"googNoiseSuppression2":true,"googEchoCancellation2":true,"googAutoGainControl2":true}}: OverconstrainedError
`

Just to clarify, the by default selected device is still recording fine, it is just not possible to switch devices.
Also, switching audio input and output is working just fine.

**Expected behavior**
The user can switch the active video input device.

**Desktop (please complete the following information):**
 - Browser: Chrome 87.0.4280
 - Version: 1.4

**Comment by bradmanAWS** [comment]
Hi @henlamk, can you please provide the complete client logs for a meeting session where this error occurs so we can take a look? Thanks!

**Comment by henlamk** [comment]
Just checked again, it resolved itself, though I cannot imagine how. 
Thanks for your quick response anyway.
