### ISSUE TITLE
MeetingManager.join doesn't resolve on Microsoft Edge

### ISSUE THREAD

**Issue by harrycollin** [aws/amazon-chime-sdk-component-library-react#320]
There appears to be a problem on Edge where the first invocation of MeetingManager.join doesn't resolve on the first try. If I invoke my 'joinMeeting' function again it works.

I'm using a simple setup: 

   ```
const meetingManager = useMeetingManager();

    const joinMeeting = async (id?: string) => {
        const response = await MeetingServiceRequest({
            url: id !== undefined ? `meetings/join?meeting_id=${id}` : `meetings/join`,
            method: "POST"
        })

        const data = await response.data;

        const joinData = {
            meetingInfo: data.meeting,
            attendeeInfo: data.attendee
        };
        console.log(joinData)

        await meetingManager.join(joinData); // < - This doesn't resolve!
        await meetingManager.start();
        
        setJoined(true);
    };
```

I am expecting this to resolve or at least through an error if something isn't right.

 - OS: Windows 10
 - Browser: Microsoft Edge 
 - Version 87.0.664.55 (Official build) (64-bit)

I have tested this on Chrome and it doesn't occur.

**Comment by p-foucht** [comment]
Hi @harrycollin 

Is this reproducible with the demo in the repo? I tried with Windows 10/Edge 87 and didn't run into any issue. It would also help if you enabled and provided info level logs in the MeetingProvider

**Comment by harrycollin** [comment]
Hi @p-foucht, 

Sorry for the late reply, I wasn't able to reproduce this on the demo. It was probably something on my end. I've since updated from 1.5.0 to 1.6.0 and haven't had any problems. I'll reopen this issue if I encounter this again.
