### ISSUE TITLE
meetingManager.selected[AudioInput/AudioOutput/VideoInput]Device is not updated

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#321]
**Describe the bug**
When calling meetingManager.selectedVideoInputDevice (or any of the others), it returns the id of said device correctly. 
However, after selecting another device by calling meetingManaager.audioVideo?.chooseVideoInputDevice(deviceId), the entry is not updated and returns the same id of the initially chosen device. 

**To Reproduce**
1. Start a meeting. 
2. console.log(meetingManager.selectedVideoInputDevice)
3. choose a different device with meetingManager.audioVideo?.chooseVideoInputDevice(deviceId)
4. console.log(meetingManager.selectedVideoInputDevice)

**Expected behavior**
The second time calling the device id, it should contain the newly chosen one. 

**Desktop (please complete the following information):**
 - OS: Mac OS 11.0.1
 - Browser: Chrome 87.0.4280
 - Version 1.4

**Comment by p-foucht** [comment]
Accessing the audioVideo instance directly means that we MeetingManager won't update the selected device. I've opened a PR (linked above) for exposing hooks to select audio input and output devices that will be released in the next NPM version

If you need an immediate fix, you can use the `meetingManager.selectAudioInputDevice`/`selectAudioOutputDevice` methods which should update the selected devices
