### ISSUE TITLE
CloudFormation Deployment in chat demo throws error on create TriggerChimeAppInstanceLambda

### ISSUE THREAD

**Issue by Xyloboard** [aws/amazon-chime-sdk-component-library-react#324]
Following the instructions in demo>chat>README.md for Cloudformation Deployment both from the command line and from the console, throws an error on creating the TriggerChimeAppInstanceLambda

Example command line:
aws cloudformation create-stack --stack-name chime-chat-demo-3 --template-body file://src/backend/serverless/template.yaml --parameters ParameterKey=DemoName,ParameterValue=chime-chat-demo-3-app --capabilities CAPABILITY_NAMED_IAM --region us-east-1

![image](https://user-images.githubusercontent.com/40793144/101888876-a1c35b80-3b96-11eb-99fd-35eb2c7b387a.png)

Looking a the Cloudwatch logs, we get a "Conflict: Resource creation in progress or has already been created." error:

![image](https://user-images.githubusercontent.com/40793144/101889083-e7802400-3b96-11eb-9b28-6e06c1d5a305.png)

I can't see where a conflict might lie...

Notes. I have previously installed the meeting demo app in my AWS account and have the Chime client set-up.

**Comment by anuranduttaroy** [comment]
The fix for this issue is being deployed and should be available early next week.

**Comment by p-foucht** [comment]
I tested the deployment using @Xyloboard's command and the `TriggerChimeAppInstanceLambda` event now passes, so I believe the fix has been pushed

Closing this, but if you still run into the issue please reopen and let us know

**Comment by Xyloboard** [comment]
This is great, thank you!
