### ISSUE TITLE
ContentShare hook throws error on iPad

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#325]
**Describe the bug**
When trying to share content on an iPad, the hook 
`
useContentShareControls()
`
results in the following error: 
Unhandled Promise Rejection: TypeError: navigator.mediaDevices.getDisplayMedia is not a function. (In 'navigator.mediaDevices.getDisplayMedia(e)', 'navigator.mediaDevices.getDisplayMedia' is undefined)

**To Reproduce**
1. Start meeting 
2. Click button to fire contentShareControls.toggleContentShare()

**Expected behavior**
A dialog popping up asking which screen or app the user wants to display.

**Smartphone (please complete the following information):**
 - OS: iPad 14.2

**Comment by ltrung** [comment]
As mentioned in JS SDK [FAQs](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md), Content Share uses webRTC getDisplayMedia which is not supported in mobile browser currently.
