### ISSUE TITLE
Missing devices on iPad

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#326]
**Describe the bug**
When trying to view the list of devices with 
`meetingManager.[audioInput/audioOutput/videoInput]Devices`
only the default iPad devices are listed and for audioOutputs, no device at all is displayed. 

**To Reproduce**
1. Start meeting
2. List devices of any type with meetingManager.[audioInput/audioOutput/videoInput]Devices

**Expected behavior**
After connecting headphones (with an audio input), the list should contain said headphones.

**Smartphone (please complete the following information):**
 - Device: iPad 14.2

**Comment by ltrung** [comment]
As mentioned in our JS SDK [FAQs](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md), [Safari](https://bugs.webkit.org/show_bug.cgi?id=179415) has known issue which prevents allowing speaker selection. The browser only uses the default device.
