### ISSUE TITLE
video[Send/Receive]BandwidthDidChange not called in Firefox

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#332]
**Describe the bug**
The observers are never updated when using Firefox, independent of whether the video is activated from the beginning or toggled later during the meeting. 

**To Reproduce**
1. Start meeting
2. Add observers to meetingManager.audioVideo?.addObserver(observer)
3. Toggle video

**Expected behavior**
The observer logging the newBandwidthKbps.

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1
 - Browser: Firefox 83.0

**Additional context**
It is working perfectly fine on Chrome.

**Comment by p-foucht** [comment]
I think this belongs under the SDK repo, but unfortunately I don't believe Firefox currently supports bandwidth estimation so it won't be called on FF
