### ISSUE TITLE
Change Camera and Speaker At Runtime

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#341]
@codeslinger I am trying to change camera and speaker at runtime of the Meeting. I found "AudioInputControl" and "VideoInputControl" which serves the same purpose. How can I make the same functionality work in my custom designed Audio and Video Icons ?

**Comment by p-foucht** [comment]
I pushed a commit that adds hooks for selecting devices [here](https://github.com/aws/amazon-chime-sdk-component-library-react/commit/3fac6f064f94e3895c9ca682ff7dab6ff84eca03). It has not been released to NPM yet though, so in the meantime you could copy the behavior in the hooks (utilize `meetingManager.selectXdevice`)

Closing, but feel free to reopen if that does not address use case
