### ISSUE TITLE
Attendee with No Camera 

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#342]
@codeslinger I am trying to show a alert message to the attendees who have joined the meeting with No camera and Speaker Permission. Is there any function in chime library which can tell whether we have joined with camera and speaker permission or not.

Also I am using the Roaster function provided in the Chime Library itself. But I found that the Roaster Attendee do not include the attendees joined in the meeting without camera and speaker permission unless the person shares his screen. How can we show the list of Attendees who have joined the meeting without camera and Speaker permission or on whose system camera and speaker is not available?

**Comment by p-foucht** [comment]
You can reference [this hook in the demo](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/meeting/src/hooks/useDevicePermissionStatus.tsx#L9)

This value gets updated when device permissions prompt is triggered - [seen here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L260)

The roster does not store details around attendee's device permissions. You would need to build that functionality outside of Chime
