### ISSUE TITLE
Cannot override microphone property in RosterAttendee as documentation suggests

### ISSUE THREAD

**Issue by cgarcian** [aws/amazon-chime-sdk-component-library-react#347]
**Describe the bug**
Documentation for RosterAttendee states that you can override property microphone to render your own microphone component, by default it renders MicrophoneActivity

**Expected behavior**
Passing microphone in props of RosterAttendee should render the custom microphone component and not a MicrophoneActivity.

**Fix**
Move "{...rest}" to be after microphone in RosterAttendee props

```
return (
    <RosterCell
      name={attendeeName}
      muted={muted}
      videoEnabled={videoEnabled}
      sharingContent={sharingContent}
      microphone={<MicrophoneActivity attendeeId={attendeeId} />}
      {...rest}
    />
);
```

**Comment by RidipDe** [comment]
Pending Rebase https://github.com/aws/amazon-chime-sdk-component-library-react/pull/348

**Comment by ltrung** [comment]
The issue has been fixed and merged
