### ISSUE TITLE
Serverless deploy script is outdated

### ISSUE THREAD

**Issue by ahmet-tas** [aws/amazon-chime-sdk-component-library-react#349]
### What are you trying to do?

I'm trying to deploy the ReactJS demo app on AWS using the readme.

### How can the documentation be improved to help your use case?

Update documentation and deploy scripts for serverless deployment

### What documentation have you looked at so far?

README.md

**Comment by p-foucht** [comment]
Thanks for bringing this up and for submitting a PR! I'll verify the deployment and merge in the fix on Monday

**Comment by p-foucht** [comment]
Merged, thanks again!
