### ISSUE TITLE
Handle AudioJoinedFromAnotherDevice case

### ISSUE THREAD

**Issue by maidinhkhoa92** [aws/amazon-chime-sdk-component-library-react#354]
Is it posible to handle AudioJoinedFromAnotherDevice case?

I'm facing a issue when attendees join from many devices. My suggestion is that we can have more meetingStatus in useMeetingStatus hook.

https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemeetingstatus--page

**Comment by p-foucht** [comment]
Hi @maidinhkhoa92 

That's a good idea, I agree that it should probably be added as a value in the useMeetingStatus hook. I'll put a PR out soon to get that added in.

If you need a fix immediately, you can access the `audioVideo` instance and handle the status code directly.

```
const audioVideo = useAudioVideo();
const observer = audioVideoDidStop = (sessionStatus: MeetingSessionStatus) => {
    const sessionStatusCode = sessionStatus.statusCode();
    if (sessionStatusCode === MeetingSessionStatusCode.AudioJoinedFromAnotherDevice ) {
      // Handling here
    } 
  };

audioVIdeo.addObserver(observer);
```

**Comment by p-foucht** [comment]
PR merged, it will be available in the next release

**Comment by p-foucht** [comment]
PR has been merged into `amazon-chime-sdk-component-library-react@2.0.1`. Resolving

**Comment by maidinhkhoa92** [comment]
Thanks @p-foucht . That 's awesome.

**Comment by maidinhkhoa92** [comment]
hi @p-foucht p
I'm changing my code to use your hooks.
I'm using `"amazon-chime-sdk-component-library-react": "2.1.1"`

However, I can't see meeting status for AudioJoinedFromAnotherDevice case

<img width="669" alt="Screen Shot 2021-04-15 at 10 43 43 AM" src="https://user-images.githubusercontent.com/19201485/114811015-7ddb8500-9dd7-11eb-9812-445a788e5a30.png">

In my log, it only has 0, 1 and 4.
