### ISSUE TITLE
Device selection on Andriod

### ISSUE THREAD

**Issue by jkelting** [aws/amazon-chime-sdk-component-library-react#355]
**Describe the bug**
On a an android smartphone/tablet it is not possible to change devices using the device selection provided by these components. The dropdown lists are all without any data, even though the neede right were granted. Also the camera and micophone were not in use by anything else.

**To Reproduce**
1. open a meeting app with a device selction component using android
2. try to change devices 

**Expected behavior**
The possible devices should be visible in the list, at least the default options. I read about bluetooth devices not shown, but here were none at all.

**Screenshots**

![Screenshot_20210106-101641_Permission controller-1](https://user-images.githubusercontent.com/68275770/103789582-7b32fc00-5040-11eb-833b-89c8ffb87baf.jpg)
![Screenshot_20210106-101706_Chrome](https://user-images.githubusercontent.com/68275770/103789585-7c642900-5040-11eb-9092-b57c137ffb57.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note20 Ultra5G & Samsung Galaxy A40
 - OS: Android 11
 - Browser Chrome

**Comment by RidipDe** [comment]
That is an expected behavior on the Android Chrome Browser. 
The webrtc example does not list the external devices. You can try it here: https://webrtc.github.io/samples/src/content/devices/input-output/
