### ISSUE TITLE
4 missing regions in demo/meeting

### ISSUE THREAD

**Issue by aJoohongKim** [aws/amazon-chime-sdk-component-library-react#369]
The latest document have 18 regions, and there are 4 missing regions.

https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html
https://docs.aws.amazon.com/chime/latest/APIReference/API_Meeting.html

**Comment by RidipDe** [comment]
Pending Merge https://github.com/aws/amazon-chime-sdk-component-library-react/pull/370
