### ISSUE TITLE
Dial-In Capability in chime meeting

### ISSUE THREAD

**Issue by yogendra-chetu** [aws/amazon-chime-sdk-component-library-react#371]
@codeslinger, @Pfoucht , I am working on to create a chime meeting and have done it successfully. I am able to share screen, share video and everything just like a zoom call. Now I need to implement dial-in capability for all participants.I am stuck with some queries like how to allow attendee to dial-in to the chime call?Do I need to use other AWS services for this? I went through some documents also but still did not find any proper solution.

I took clone from amazon chime sdk js and made it running. I got a number when I am joining meeting via SIP with meeting title and voice connector id like this-
sip:+17035550122@123456;transport=tls;X-joinToken=ZjFiNzRjMTgtMTBmMy94ZmQ3LTljM2YtNGY5MTg1NWE2YzYyOmJhNTkwODk0LTNhZWMtNGU4MS05Y2UyLWIyOTc2NDA3YzY0Mg

When I am trying to join this meeting by dialing-in 17035550122 from dialer then I am getting response like this number is currently busy so I am not sure which number I need to dial-in. Do I need to do something else to join this meeting from dialer. Please guide.

**Comment by yogendra-chetu** [comment]
Hi Everyone, Any updates on this? @michhyun1 , @nicklera1 , @bradmanAWS ,  @p-foucht . I am still stuck on it.

**Comment by p-foucht** [comment]
Hi @yogendra-chetu 

Have you come across [this repo](https://github.com/aws-samples/amazon-chime-sdk-pstn-integration) that demonstrates Chime/PTSN integration?

**Comment by ltrung** [comment]
@yogendra-chetu Doesnt seem like the sip link is valid (123456 is supposed to be the voice connector ID).
You would need to setup some voice infrastructure (like PBX). For more information, please refer to this wiki: https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-cvc.html and the demo that @p-foucht linked above.

**Comment by ltrung** [comment]
We close it for now but feel free to reach out if you have any additional questions.
