### ISSUE TITLE
Suppress device permission request

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#379]
Whenever a user joins a meeting, he is asked to grant permission for microphone and camera. 

Is it possible to suppress this behavior, e. g. when the user is not supposed to use his microphone and webcam during the whole meeting and just to join as a viewer?

**Comment by richnew10** [comment]
This behavior is triggered in order to get device labels:

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/0d84475db0eb74da5acb9f5746a0d77c563c4141/src/providers/MeetingProvider/MeetingManager.ts#L265

I don't see a good approach to controlling that through the component library interface, only through the lower-level SDK interface, but I'll follow up with someone closer to the code to see if they have a suggestion.

**Comment by p-foucht** [comment]
This is a shortcoming of the library, as this isn't something you can easily do. We'll take note of this critique and try to put flexibility/extensibility onto our roadmap

There are a few ways you could try to workaround this, but they are not the most straightfoward or have been thoroughly tested

1. Mock the `getUserMedia` API: `navigator.mediaDevices.getUserMedia = () => true` which will remove the device permission prompt
2. Override the `MeetingManager`'s `join` method ([seen here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L129)) with your own implementation, removing the device calls that trigger the `getUserMedia` call in the first place

**Comment by jrowny** [comment]
This is also biting us. We have users who enter as spectators and don't expect to have to enabled audio/video. You could have a simple flag to pass into join that disables the calls to listAndSelectDevices();

**Comment by xuesichao** [comment]
Hi guys, we raise this PR [#499](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/499) to fix this issue. 

We add an optional parameter `isDevicePreviewSkipped` in `meetingManager.join()` and a new function `meetingManager.invokeDevicePermissionRequests()` . 

* To suppress the device permission request, you could set `isDevicePreviewSkipped` to true when user joins a meeting (calling `meetingManager.join()`)
* Later If user wants to grant device permission, you could call `meetingManager.invokeDevicePermissionRequests()` function. If the device permission is unset, the device permission request should pop up

Feel free to try it and give us some feedback!

**Comment by vidya-mohan** [comment]
Resolving as issue fixed and released
