### ISSUE TITLE
VideoTileGrid not displayed on iPad

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#397]
**Describe the bug**
After joining a meeting and having the useMeetingStatus hook return a success, the videotilegrid does not display the other participants nor the iPad user himself. 

**To Reproduce**
1. Join meeting 
2. Start local video tile

**Expected behavior**
The videotilegrid should display other participants and the user himself.

**SDK**
Tried all versions from 1.4 to 1.6.

**Smartphone (please complete the following information):**
 - Device: iPad 4th generation
 - OS: 14.3
 - Browser: Safari

**Comment by henlamk** [comment]
I checked on Mac using Safari, the same problem occurs.

**Comment by firdausmaarof** [comment]
@henlamk did u manage to solve this?

**Comment by tiendungtcu** [comment]
I got the same problem with Safari on Mac. How can you solve this?  @henlamk , @firdausmaarof

**Comment by ameriles** [comment]
Have the same issue on Safari Mac and Safari iOS

**Comment by xuesichao** [comment]
SDK v1.4 and v1.6 are pretty old. We recommend you to upgrade the latest version and see if the issue still exists.
Also the `VideoTileGird` is not supposed to display anything unless any user enable their camera or share their screen.

Close the issue due to inactivity, but feel free to reopen it.
