### ISSUE TITLE
useMeetingStatus is not correct once leave the meeting.

### ISSUE THREAD

**Issue by asc0910** [aws/amazon-chime-sdk-component-library-react#401]
**useMeetingStatus is not correct after leave the meeting**
If we call meetingManager.leave(), the useMeetingStatus is not working anymore because we clear all subscribers.

**To Reproduce**
meetingManager.leave()

**Expected behavior**
useMeetingStatus should always be correct.

**Comment by p-foucht** [comment]
PR to address this has been merged, we will release in the next release. Thanks for pointing this out

**Comment by p-foucht** [comment]
The PR been released in version `amazon-chime-sdk-component-library-react@2.0.1`. Resolving
