### ISSUE TITLE
No camera: setupDeviceLabelTrigger fails

### ISSUE THREAD

**Issue by arty-name** [aws/amazon-chime-sdk-component-library-react#409]
**Describe the bug**
Cannot join the meeting when a computer doesn’t have a webcam at all. When joining, [`setupDeviceLabelTrigger` requests audio and video](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/aac1cab8a5fd79b375cc5dae26d07902780693e3/src/providers/MeetingProvider/MeetingManager.ts#L266-L269), and the call fails even before asking for permissions.

**To Reproduce**
1. Connect external monitor, keyboard and mouse to your MacBook (haven’t tested on other OSes), but no external webcam.
2. Close the lid, this makes the webcam unavailable.
3. Try to start a meeting or join an existing one.

**Expected behavior**
Joining the meeting should be possible with audio only, so when a computer doesn’t have a webcam at all, or it is disabled like in the realistic example above, the user is still able to connect.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari
 - Version: 1.5.0

**Comment by p-foucht** [comment]
Hi @arty-name,

Looks like you're right. We will address this following our 2.0 version release early next week.

As an immediate fix, you could manually override the method in MeetingManager. You could use `this.audioVideo.listVideoInputDevices` to check if for video inputs, and make a getUserMedia request with `video: false` in cases where there are no video inputs

**Comment by arty-name** [comment]
Thank you for the update! The timeline looks very good for me!

**Comment by p-foucht** [comment]
PR has been merged into `amazon-chime-sdk-component-library-react@2.0.1`. The deviceLabelTrigger will only request video permissions if there is an available video input device provided by the `enumerateDevices` API

Resolving, but feel free to reopen if needed

**Comment by arty-name** [comment]
The issue is solved for me, thanks!
Sorry it took me so long to verify.
