### ISSUE TITLE
Blank black screen after starting local video immediately after meetingManager.start()

### ISSUE THREAD

**Issue by k-ahn** [aws/amazon-chime-sdk-component-library-react#420]
I am trying to port my working native Chime SDK code to use the React Chime SDK. My meeting join screen presents the user with two opions: 1) Join with Audio and 2) Join with Audio and Video. Selecting the latter requires the local video is automatically started. 

Using the Chime SDK my working code is:

```
async startMeetingWithAudioAndVideo() {
    const session = this.state.meetingSession;
    await this.startMeeting(); // This sets up the audio bindings, observers and then runs session.audioVideo.start()
    await session.audioVideo.chooseVideoInputDevice(this.state.videoDevices[0]);
    await session.audioVideo.startLocalVideoTile();
}
```
Translated to using this SDK, my code is

```
async startMeetingWithAudioAndVideo() {
        await meetingManager.start();
        toggleVideo();
}
```

**ISSUE**: The localvideo window appears, however, i just get a black screen. If i toggle the video off and on it appears correctly. 

I think the issue is that `toggleVideo()` runs too soon. In the original code i think it may work because the act of binding the device and then starting local video introduces some time delay. I may be wrong. 

So my question is - how can i only start the local video tile once the meeting has fully started?

![image](https://user-images.githubusercontent.com/53981218/107849433-0dbe7c00-6df3-11eb-98da-589217bcd95f.png)

Tested on:
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by p-foucht** [comment]
We'll look into this -- Might be a race condition somewhere when we are initializing the meeting. Until we get it sorted out, you could introduce an articial timeout delay (obviously not ideal)

Once we root cause we may be able to offer a better workaround until we get an actual fix out

**Comment by henlamk** [comment]
I have tried calling toggleVideo() with a timeout and the behaviour seems the same.

**Comment by k-ahn** [comment]
I think i've found a better workaround than a timeout (or maybe this is the answer):

```
const status = useMeetingStatus()

useEffect(() => {
    if (status === 1) {
        if (startWithVideo) toggleVideo();
    }
},[status]);

```
This effectively mimics what i was expecting to achieve with `await meetingManager.start();` - toggleVideo only executes once the meeting is started.

The `startWithVideo` boolean means the code only runs when a user selects Join with Audio and Video (as per my use case). It isn't fully tested yet but i've yet to see an issue in development.

**Comment by henlamk** [comment]
Splendid, working just fine.

**Comment by k-ahn** [comment]
Thanks @henlamk and @p-foucht
