### ISSUE TITLE
MicrophoneActivity doesn’t support className

### ISSUE THREAD

**Issue by arty-name** [aws/amazon-chime-sdk-component-library-react#423]
### What are you trying to do?

I am trying to customize the look of `MicrophoneActivity`

### How can the documentation be improved to help your use case?

It could be updated to reflect that `MicrophoneActivity` doesn’t support `className` prop anymore, only `css`

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-microphoneactivity--page

**Comment by devalevenkatesh** [comment]
Hello @arty-name,

Thanks for reporting the issue. Upon checking, I found that the `MicrophoneActivity` renders `MicVolumeIndicator` component which is overriding the passed `className` prop with the `ch-mic-volume-indicator` class name, check [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/MicVolumeIndicator/index.tsx#L33). We will work on a fix for this, until then, can you please check If you are able to customize using the `ch-mic-volume-indicator` class name.

**Comment by devalevenkatesh** [comment]
We have merged in a fix this issue. Closing it, please feel free to re-open if you still face any issue.
