### ISSUE TITLE
selectVideoInputDevice swallows error

### ISSUE THREAD

**Issue by jrowny** [aws/amazon-chime-sdk-component-library-react#433]
**Describe the bug**
selectVideoInputDevice catches errors, so I can't react to a problem selected an input device.

**To Reproduce**
```
meetingManager.selectVideoInputDevice(devices[newIndex].deviceId).then(()=> {
        console.log("This always fires, even if it failed");
        meetingManager.audioVideo?.startVideoPreviewForVideoInput(previewVideoNode);
      }).catch(()=> {
       console.log("This never fires");
});
```
**Expected behavior**
Need a way to get the error so we can react. I can use the lower level chooseVideoInput but then it does not update `selectedDevice` in the context.

**Comment by devalevenkatesh** [comment]
Yes, you are correct thanks for reporting this out. Currently our library does not throw errors in functions like `selectAudioInputDevice`, `selectAudioOutputDevice` and `selectVideoInputDevice`. We just catch and log it.

We will check on how best to handle this since throwing an error looks like an breaking change here.

**Comment by alanhoff** [comment]
Just checking, any news related to this issue? I'm having a very odd behavior where attendees are able to join but wont see no one in the meeting if `selectAudioInputDevice` is selected.

**Comment by grydstedt** [comment]
Also wondering about this

**Comment by rossng** [comment]
This is a problem for me too. In my case, I'd like to detect when selecting a device has failed, then choose no device (so I can display something useful in the UI) and a toast message explaining the issue to the user.

My workaround for now is to do this:

```typescript
const changeAudioInputDevice = useCallback(
    async (deviceId: string) => {
        try {
            await audioVideo?.chooseAudioInputDevice(deviceId);
            await selectAudioInput(deviceId);
        } catch (e) {
            toast({
                title: "Could not change audio input device",
                description: <PermissionInstructions />,
                isClosable: true,
                duration: null,
                status: "error",
            });
            try {
                await selectAudioInput("none");
            } catch (e) {
                console.error("Failed to unselect audio device", e);
            }
        }
    },
    [audioVideo, selectAudioInput, toast]
);
```

Which is, of course, terrible on many levels. But maybe it will be helpful to someone else until this issue gets fixed.

**Comment by xuesichao** [comment]
Hi guys, we raised this [PR](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/493) to fix the issue. You may want to give it a try. Let us know if you have any questions or comments.

**Comment by ltrung** [comment]
#493 has been merged so closing this issue for now. Please open new issues if you run into new issue.
