### ISSUE TITLE
Streamed video not displayed in video grid

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-component-library-react#444]
**Describe the bug**
After starting sharing content via 
`  
    await meetingManager.audioVideo?.startContentShare(mediaStream)
`
the video is displayed correctly in the video grid of the user playing the video. 
Other participants only get a black screen where the video should be displayed.
However, the sound is being transmitted. 

**To Reproduce**
1. Join meeting with more than one user
2. One user starts content share with video 

**Expected behavior**
The video should be displayed in the other participant's video grids.

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Chrome (89.0.4), Firefox (86.0)
 - Chime react lib: 2.1.0, Chime SDK: 2.5.0

**Comment by RidipDe** [comment]
Hi @henlamk,
Thanks for opening the issue.
Just to double check "Other participants only get a black screen where the video should be displayed." which browser is the participant who turned on the content share on and the participant viewing the black screen using? 

You mentioned Chrome and Firefox. So is the issue in Chrome cross Firefox or it occurs in Chrome - Chrome and Firefox - Firefox as well?

Also, how frequently do you encounter the issue?

**Comment by henlamk** [comment]
I have rechecked just to be sure, and it seems that
- a video played from firefox is displayed perfectly on other browsers
- a video played from chrome is only visible for the playing user himself

This behavior occurs every time. 

Thanks for the quick response.

**Comment by RidipDe** [comment]
I tried to reproduce the issue at my end.

While screen sharing when using the Component Library worked fine in all the following combinations:

- Chrome cross Firefox 
- Chrome cross Chrome
- Firefox cross Firefox 

However, I was able to repro a similar bug using custom media stream.
1. User A joins from Firefox (v85)
2. User B joins from Chrome (v88)
3. User A runs the following command in the browser console

```
const video = document.createElement('video');
video.src = 'https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Big_Buck_Bunny_4K.webm/Big_Buck_Bunny_4K.webm.360p.vp9.webm';
await video.play();
mediaStream = video.mozCaptureStream();
await app.audioVideo?.startContentShare(mediaStream)

```
4. User B on Chrome sees black screen on the content share video element and no sound is heard.

Can you please confirm if this is what you are observing too? 


---
### User A on Firefox:
<img width="1041" alt="Screen Shot 2021-03-05 at 4 10 51 PM" src="https://user-images.githubusercontent.com/15669836/110187521-7f279400-7dcd-11eb-8af2-94550645b64b.png">


### User B on Chrome:
<img width="1440" alt="Screen Shot 2021-03-05 at 4 11 05 PM" src="https://user-images.githubusercontent.com/15669836/110187536-8f3f7380-7dcd-11eb-99af-5339dea26814.png">

**Comment by henlamk** [comment]
@RidipDe At the point of testing the setup you described it works as previously: playing a video from Firefox to other browsers works fine. The issue I encounter is the other way around, when a chrome user plays a video to other browsers.

@ltrung  I have disabled the hardware acceleration and boy oh boy does it work now. 

Thanks for looking into this, guys, much appreciated.
