### ISSUE TITLE
Meeting demo does not work with npm 7

### ISSUE THREAD

**Issue by rossng** [aws/amazon-chime-sdk-component-library-react#479]
**Describe the bug**

The meeting demo does not work when using npm 7 or later. In my case, I am running NPM 7.8.0. This is due to a change in the way that NPM treats mismatched peer deps.

**To Reproduce**

1. Update your NPM installation to a new version (e.g. 7.8.0)
2. Follow the instructions to run the meeting demo
3. Observe that, when running `npm run start`, the `npm install` call fails with a peer dependency error. Specifically, it cannot reconcile React 16 (specified in the meeting demo `package.json`) with React 17 (specified in the sdk `package.json`).

**Expected behavior**

Following the README instructions should work flawlessly.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3, MacBook Air (M1, 2020)
 - Browser: N/A
 - Version: N/A

**Additional context**

I resolved this problem by modifying the meeting demo `package.json` to use React 17. There is also a `--legacy-peer-deps` NPM flag available, but this is a less optimal solution.

**Comment by ltrung** [comment]
@rossng Thank you for reporting. We will migrate to npm 7 soon and update the React version in the demo to 17 too.

**Comment by ltrung** [comment]
The demos have been updated to React 17 in #488. Closing this issue now.
