### ISSUE TITLE
My Meeting is refreshed automatically

### ISSUE THREAD

**Issue by maidinhkhoa92** [aws/amazon-chime-sdk-component-library-react#482]
**Describe the bug**
In preview screen, my screen refreshes automatically many times. It makes a bug called AudioJoinedFromAnotherDevice

**Expected behavior**
Is it possible to turn off refreshing in preview page ?

**Screenshots**
<img width="1405" alt="Screen Shot 2021-04-14 at 11 57 16 AM" src="https://user-images.githubusercontent.com/19201485/114656767-e152ad80-9d18-11eb-9b9d-8f3c168300e3.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by michhyun1** [comment]
@maidinhkhoa92 hi there, quick note: I see that your get request is returning 500 - I noticed maybe a type in your url - you have 'attentdee' instead of 'attendee'.

This is not reproduce-able in the current repo meeting demo, could you tell us what your use case is here?

**Comment by maidinhkhoa92** [comment]
Hi @michhyun1 , I found issue. It refreshes many times because I used meeting.start() in preview screen. I moved this functionality into onClick event of Join button.
<img width="614" alt="Screen Shot 2021-04-15 at 10 31 08 AM" src="https://user-images.githubusercontent.com/19201485/114810191-c003c700-9dd5-11eb-827f-609a6604960f.png">

**Comment by RidipDe** [comment]
Thanks for letting us know.
