### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by GiovanniIncammicia** [aws/amazon-chime-sdk-component-library-react#483]
**Describe the bug**
Whenever the app unmounts, I get errors on "removeEventListener".
They refer to the following files:
/src/hooks/useFocusIn/index.tsx
/src/hooks/useMouseMove/index.tsx

It seems the `useEffect return` is trying to call `removeEventListener` from `el.current` without checking if it's null first.
(shouldn't it be something like `el.current?.removeEventListener(...)` ?)

I'm running the latest version of all the libraries demo/meeting. I didn't manage to run the demo, so I rewrote it from a fresh CRA project. The code is pretty much the same.

**To Reproduce**
1. Enter a meeting
2. Refresh page (which triggers NoMeetingRedirect and goes to Home)
3. See error

**Expected behavior**
No error should appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 89

**Comment by devalevenkatesh** [comment]
Hello, we already have an issue #476 for this. Closing this one as duplicate. Thanks for reporting the issue.
