### ISSUE TITLE
Feature request: change nameplate of LocalVideo component inside VideoTileGrid

### ISSUE THREAD

**Issue by nceresole** [aws/amazon-chime-sdk-component-library-react#485]
### What are you trying to do?

I'm trying to change the nameplate of the LocalVideo component rendered by the VideoTileGrid component.

So my application needs to be translated to Spanish, and when I turn on my local video, the nameplate of the LocalComponent is "Me" and I want to replace it with something else or just remove it.

Is there a direct way to do it or I will have to implement a custom LocalVideo outside the VideoTileGrid?

### How can the documentation be improved to help your use case?

If it exists, provide documentation about how to change this via the component API.

### What documentation have you looked at so far?

This repository and  the Amazon Chime React Component Library Guide

**Comment by michhyun1** [comment]
@nceresole Hey there, and thanks or using the React Component Library - for your use case, you'll most likely want to use the [LocalVideo](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-localvideo--page) component along with the [VideoGrid component](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-video-videogrid--video-grid). You can look at the [VideoTileGrid](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-videotilegrid--page) for an example of how to use the two components to build a video grid. 

It looks like we do use the "Me" nameplate inside the video tile grid - I'll mark this an enhancement and perhaps we can bubble up that nameplate prop up to the VideoTileGrid. Let us know if you

**Comment by nceresole** [comment]
@michhyun1 thanks for the response and for this awesome library!

We'll probably go with the` VideoGrid` component since it will provide us more flexibility for future use cases too.

**Comment by michhyun1** [comment]
Okay thats great to hear - let us know how it goes :)

**Comment by vidya-mohan** [comment]
Resolving as based on the current response, VideoGrid is meeting your needs
