### ISSUE TITLE
Unable to record the meetings

### ISSUE THREAD

**Issue by nchandupatla** [aws/amazon-chime-sdk-component-library-react#495]
**Describe the bug**

I followed the documentation to set up and host serverless meetings using ReactJS

https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting

But the problem is that I cannot record the meetings using the steps in this README (https://aws.amazon.com/blogs/business-productivity/how-to-enable-client-side-recording-using-the-amazon-chime-sdk/). 
I do not see any bot/recorder joining the meeting. It works fine with native javascript demo meetings but not with this React version

Please let me know how to record meetings when using react chime SDK

**Comment by devalevenkatesh** [comment]
Hello, the React SDK demo currently does not support the recording as shown in the JS SDK demo. This will be an enhancement to make on the current demo.

**Comment by rakesh-eltropy** [comment]
@devalevenkatesh Do we have any recommendation to record video using AWS Chime React SDK?

**Comment by michhyun1** [comment]
@rakesh-eltropy We don't have a component to start/stop recording, you'll have to refer to the SDK [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) to get an idea of how to create your own React component to create the recording feature.

**Comment by vidya-mohan** [comment]
@rakesh-eltropy we have launched better support for recording with server side capture. See https://github.com/aws/amazon-chime-sdk-js/issues/1011 so I am resolving this as duplicate.

[What's new?](https://aws.amazon.com/about-aws/whats-new/2021/07/the-amazon-chime-sdk-adds-media-capture-pipelines-to-enable-capture-of-meeting-video-audio-and-content-streams/)
[Blog post and demo](https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/)
