### ISSUE TITLE
Hovering over icons on Roster components introduces a jumpy behaviour on Dark Theme

### ISSUE THREAD

**Issue by grega-jelenc** [aws/amazon-chime-sdk-component-library-react#497]
**Describe the bug**
Hovering over icons on Roaster component introduces a jumpy behaviour

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-roster--roster-header
2. Select Dark Theme
3. Hover over search icon, three dots icon
4. Observe

**Version**
Tried on 2.2.0 and 2.3.0

**Expected behavior**
No change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox, possibly others

**Comment by grega-jelenc** [comment]
Tested in storybook. Its working. Thank you.

Tested in: Chrome, Firefox, Safari

**Comment by devalevenkatesh** [comment]
The fix is merged in, thanks for your confirmation.
