### ISSUE TITLE
Modal component does not cleanup 'keydown' event listener

### ISSUE THREAD

**Issue by justindarc** [aws/amazon-chime-sdk-component-library-react#503]
**Describe the bug**
Modal component does not cleanup 'keydown' event listener.

**To Reproduce**
1. Create a `<Modal />` instance
2. Remove the `<Modal />` instance
3. A "keydown" event listener will leak

**Expected behavior**
The "keydown" event listener should be cleaned up when the `<Modal />` instance is removed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
This can cause the "keydown" event listener to run multiple times if a single `<Modal />` instance is added and removed from the DOM.

**Comment by ltrung** [comment]
@justindarc Thanks for fixing this. Closing the issue now.
