### ISSUE TITLE
Need example of how to wire and use postLogConfig in MeetingProvider

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-component-library-react#505]
### What are you trying to do?

Need a demonstrative example of using postLogConfig. There is a reference to it as an option in https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-meetingprovider--page but there is no example.

This internally sets the https://aws.github.io/amazon-chime-sdk-js/classes/meetingsessionpostlogger.html. THe example on the JS SDK demo application currently demonstrate it. https://github.com/aws/amazon-chime-sdk-js/blob/050457e82fcbe88f0d149c2aacde483b9ff612e8/demos/browser/app/meetingV2/meetingV2.ts#L1291

### How can the documentation be improved to help your use case?

Link to sample code or updating React demo to use it

### What documentation have you looked at so far?

*ReadMe, Storybook

**Comment by devalevenkatesh** [comment]
Closing this issue as the PR addressing this is merged now.
