### ISSUE TITLE
No selectedDeviceError

### ISSUE THREAD

**Issue by jrowny** [aws/amazon-chime-sdk-component-library-react#506]
**Describe the bug**
selectedDeviceError seems to always be null. If I deny camera permissions, I should be able to capture that error somehow. Instead selectedDeviceError in useVideoInputs is always null.

**To Reproduce**
1. Disallow camera access
2. Try to select video input camera
3. selectedDeviceError is still null

Additionally, I received a hard crash when trying to set the camera input a second time.

**Expected behavior**
There should be no unhandled errors, there should be an error in selectedDeviceError when permissions are denied.

**Screenshots**
<img width="748" alt="Screen Shot 2021-05-17 at 4 57 10 PM" src="https://user-images.githubusercontent.com/367710/118555994-5b6bbd00-b731-11eb-8964-63dbee4cfa31.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrowny** [comment]
ah, okay, I kind of got it working by using the `useSelectVideoInputDevice` hook, but it doesn't actually show me the real error, which is that permissions were denied.

**Comment by devalevenkatesh** [comment]
Hello, Thanks for reporting the issue.

The errors will be given out from the respective hooks like [`useAudioInputs`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useaudioinputs--page) and so on similarly for the audio output and video input.

Could you please help us with the browser console logs to troubleshoot more when you ran into a crash? We will try your reproducing steps to debug more.

**Comment by ltrung** [comment]
@jrowny I tried to reproduce this issue and I think i might have an idea what happened.
If you check the console.log, did you see any 'Failed to get device permissions' error?
If so, could you try to use [useDevicePermissionStatus](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/hooks/sdk/useDevicePermissionStatus.tsx) to see if the permission is set to Denied? 
Meeting Manager tries to setup devices as part of the initialization step https://github.com/aws/amazon-chime-sdk-component-library-react/blob/0b64162ef541ad8db9dedecd21ca6b33d4ee7a85/src/providers/MeetingProvider/MeetingManager.ts#L291, so if it fails there, it would not get to select video input device and thus, the error message is empty.

**Comment by jrowny** [comment]
Ah, thanks will try that. 

To get the crash, I used `meetingManager.selectVideoInput` instead of the useSelectVideoInputDevice hook. once I switched, the crash went away.

I'll close this for now as I think I'm covered.

FYI, your documentation code example for useDevicePermissionStatus is wrong, it has an example of meeting status.
