### ISSUE TITLE
The React library documentation is broken when click the story tab of UI components

### ISSUE THREAD

**Issue by jing-chen1** [aws/amazon-chime-sdk-component-library-react#511]
**Describe the bug**
As we saw in the stand up, the React library documentation is broken when click on the story tab of Canvas on any of UI components. And even if you go back to the previous page(any other tab of UI component), it is still broken.

**To Reproduce**
1. Go to [React library documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
2. Click on any of the UI component, let's say Badge
3. Click on the story tab on the bottom
4. See the bland screen

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version 90.0.4430.212

**Comment by HamzaKV** [comment]
Facing same issue.

Desktop:
- OS: Windows 10 - 64 bit
- Browser: chrome
- Version 90.0.4430.212

**Comment by jing-chen1** [comment]
Hi @HamzaKV 

We have fixed the issue by [this PR](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/525). Please feel free to check it out.
