### ISSUE TITLE
Aspect ratio issue from mobile video..

### ISSUE THREAD

**Issue by rakesh-eltropy** [aws/amazon-chime-sdk-component-library-react#528]
**Describe the bug**

The aspect ratio of video input from mobile portrait view is completely off. Please see the attached screenshot. 

**Expected behavior**

The aspect ratio of 16:9 or 4:3 in the video grid for the remote video.

**Screenshots**
PFB screenshot. 

![image](https://user-images.githubusercontent.com/11676761/120937452-1bde3280-c72b-11eb-864f-7d6b8a721598.png)

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Version: 90.0.4430.212

**Smartphone:**
 - Device: Samsung galaxy
 - OS: Android
 - Browser: Chrome
 - Version : 90

**Additional context**

**Comment by simmkyu** [comment]
Other attendees also see the video in the portrait aspect ratio when enabling the mobile video in portrait mode.

<img width="1648" alt="Screen Shot 2021-06-10 at 3 36 04 PM" src="https://user-images.githubusercontent.com/36240708/121605754-c7c0a000-ca01-11eb-854c-d36668693ee9.png">


To fill in the video, you may apply the `object-fit` CSS property to fill in your video tile element. See the following FAQ for more information.
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-create-a-video-tile-layout-for-my-application

**Comment by vidya-mohan** [comment]
@rakesh-eltropy resolving this - you can manipulate the layout with CSS as suggested
