### ISSUE TITLE
PreviewVideo also stops LocalVideo without setting isVideoEnabled to false

### ISSUE THREAD

**Issue by alabianca** [aws/amazon-chime-sdk-component-library-react#529]
**Describe the bug**

`audioVideo.stopVideoPreviewForInput` also ends LocalVideo, but `isVideoEnabled` of `useLocalVideo` still remains true.

**To Reproduce**
1. Run meeting demo in this forked repo https://github.com/alabianca/amazon-chime-sdk-component-library-react
2. Enter the call and enable your local video
3. In the ControlBar click the `Open for Settings` button
4. Close the modal that contains the VideoPreview
5. Notice how the local video stream ended, but the isVideoEnabled is still true. It's easy to spot due to the Video icon in the controlbar being set to 'on'

**Expected behavior**
1. Either the local video not stopping after PreviewVideo unmounts
2. Or... isVideoEnabled to be set to false. I could create a useEffect to turn the local video on again if it is set to false and but selectedDevice of `useVideoInputs` is not null.

**Screenshots**

<img width="979" alt="Screen Shot 2021-06-07 at 5 39 02 PM" src="https://user-images.githubusercontent.com/25507518/121096683-4c1fe280-c7b8-11eb-8f04-033a33d4032d.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Chrome
 - Version 91.0.4472.77 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Additional background context:
Our app currently allows a user to open up a modal during the call in which the user can make some device selections. In the modal we display a preview of their video (in case they change their video input). When the user closes the modal, it also turns off their local video, but the Video Input icon is set to 'on'.

**Comment by ltrung** [comment]
This is because JS SDK does not support to have video preview and local video to be on at the same time. Could you try a similar workaround as suggested in https://github.com/aws/amazon-chime-sdk-js/issues/502 (basically have another meeting provider with a different device controller)?

**Comment by xuesichao** [comment]
Hi @alabianca, thanks for bringing us this issue, we raised this PR #556 to fix the issue.

>Either the local video not stopping after PreviewVideo unmounts

Due to the limitation of JS SDK, it's hard to do achieve this. `LocalVideo` and `PreviewVideo` shares the same stream from selected camera, unmounting `PreviewVideo` closes `LocalVideo` as well.

> Or... isVideoEnabled to be set to false. I could create a useEffect to turn the local video on again if it is set to false and but selectedDevice of useVideoInputs is not null.

In this PR #556, we set the `isVideoEnabled` to `false` after unmounting the `PreviewVideo` to achieve it. Could you please check the fix and let us know the effect?

**Comment by alabianca** [comment]
Hi @xuesichao I tested it on your branch and it's working as I would expect. My plan is to now create a useEffect and re-enable the local video if `isVideoEnabled` is false, but there is still a selected device from `useVideoInputs`

**Comment by xuesichao** [comment]
Hi @alabianca , glad the fix works.

> Hi @xuesichao I tested it on your branch and it's working as I would expect. My plan is to now create a useEffect and re-enable the local video if `isVideoEnabled` is false, but there is still a selected device from `useVideoInputs`

Sorry, I don’t get what you mean, could you please explain it further? Thanks!
* I think you are trying to restart `LocalVideo` after closing the `PreviewVideo`, right?
* Where are you gonna use this `useEffect`, in meeting page?
* What is the problem with a selected device from `useVideoInputs`?

**Comment by alabianca** [comment]
@xuesichao sorry for the confusion. There are no problems with the `useVideoInputs` hook. It's all working as I expected. 

* Yes, I am trying to restart the `LocalVideo` after closing the `PreviewVideo`
* I will add a `useEffect` in our applications VideoPage

**Comment by xuesichao** [comment]
@alabianca No problem, thanks for your clarification!

**Comment by xuesichao** [comment]
PR #556 fixed the issue. Closed.
