### ISSUE TITLE
ContentShare / ScreenShare does not work anymore following introduced support for sourceId

### ISSUE THREAD

**Issue by ElielCohen** [aws/amazon-chime-sdk-component-library-react#538]
**Describe the bug**
Content Share (screen share), share again the video on safari browsers and cause error on Chrome browsers (promise rejected).

**To Reproduce**
Try to share your screen on Chrome or Safari, while using latest version of the library and meeting demo.

**Expected behavior**
Screen sharing should work on both browsers.

**Desktop (please complete the following information):**
 - Reproduced on both Windows 10 and macOS Big Sur, on both Safari and Chrome.

**Additional context**
Have identified the problematic commit, reverting this commit (that introduced support for sourceId) solves the problem.

Revert "Pass sourceId to toggleContentShare (#523)"

This reverts commit fe41d881a1e6bcf93685490b6d87d3aaf9a13397.

Thanks,

Eliel Cohen
Head of WebRTC solution @TytoCare

**Comment by jing-chen1** [comment]
Hi @ElielCohen 

Thanks for reporting. We have merged the [fix](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/539). Closing this issue now, please feel free to reopen it if you encounter this again.
