### ISSUE TITLE
Enabling Voice Focus

### ISSUE THREAD

**Issue by AlexMCarv** [aws/amazon-chime-sdk-component-library-react#543]
### What are you trying to do?

I am trying to enable voice focus in our application that is built using the chime-sdk-component-library-react. I browsed through the amazon-chime-sdk documentation on Voice Focus, but I am finding it very challenging to follow, because the implemetation of the app using the react library is very different than simply using the amazon-chime-sdk directly.

Is there a future plan to add support for voice focus in this library? Or could the documentation be updated to include how we could enable it? 

### How can the documentation be improved to help your use case?
Page on how to enable voice focus.

### What documentation have you looked at so far?
https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html

**Comment by merryblack** [comment]
Could I know when this case will be done?

**Comment by ldai1** [comment]
Hi,

We are targeting to release this feature by end of next week.

**Comment by jing-chen1** [comment]
Hi, Thank you for your interests. Here is the corresponding PR: [Add voice focus feature](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/583). This feature will be released soon.

**Comment by jing-chen1** [comment]
Amazon Chime SDK for JavaScript team has released a new version: 2.9.0 on [NPM](https://www.npmjs.com/package/amazon-chime-sdk-component-library-react) with Amazon Voice Focus feature.

**What’s new?**
* In this version, we extend the ability of React component library to accept Device and AudioTransformDevice as audio input.
* We add a new provider [VoiceFocusProvider](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-voicefocusprovider--page) to initialize noise suppression and transform a normal audio input device to an Amazon Voice Focus transform device.
* We create a new UI component [AudioInputVFControl](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-meetingcontrols-audioinputvfcontrol--page) to provide Amazon Voice Focus option to users.

To try this new feature, please checkout the [Meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting). Run the demo following the ReadMe and join a meeting, then you can find Amazon Voice Focus option at the bottom of the dropdown list next to Microphone icon. 

<img width="437" alt="Screen Shot 2021-08-31 at 2 35 10 PM" src="https://user-images.githubusercontent.com/82910472/131584744-f86176fe-de28-4216-a01a-6d6ec03adbae.png">
