### ISSUE TITLE
Is it possible to keep camera on in start?

### ISSUE THREAD

**Issue by subhendukundu** [aws/amazon-chime-sdk-component-library-react#544]
**Describe the bug**
I am trying to keep the camera on while start/join the meeting. Is that possible ATM?

**To Reproduce**
1. Clone the repo
2. Followed the readme to start the example meeting application
3. Changed the following code in `MettingForm`
```
await meetingManager.join({
  meetingInfo: JoinInfo.Meeting,
  attendeeInfo: JoinInfo.Attendee,
  deviceLabels: isSpectatorModeSelected === true ? DeviceLabels.None : DeviceLabels.Video,
});
```

**Expected behavior**
It should keep the camera on as soon as an attendee joins.

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.7
 - chrome

**Comment by xuesichao** [comment]
Hello @subhendukundu .

The `deviceLabels` parameter in `meetingManager.join()` is to control the content in `deviceLabelTrigger`. With your code, `DeviceLabels.Video` will set the `constraints` in `getUserMedia()` to `{audio:false, video:true}`. When `deviceLabelTrigger` is triggered, the browser will only ask the permission for video devices.  

If I'm not wrong, I think what you want to do is to open the camera as soon as user joins a meeting. You could try the `useLocalVideo` hook to implement this function. Try the code below:

For meeting demo in React SDK, in `MeetingJoinDetails.tsx`

```tsx
import { useLocalVideo } from 'amazon-chime-sdk-component-library-react';

const MeetingJoinDetails = () => {
  const { isVideoEnabled, toggleVideo } = useLocalVideo();

  const handleJoinMeeting = async () => {
    try {
      await meetingManager.start();
      history.push(`${routes.MEETING}/${meetingId}`);
      
      // If you want to try in your own project, make sure to
      // call `toggleVideo()` after `await meetingManager.start()` and the route changes
      if (!isVideoEnabled) {
        toggleVideo();
      }

    } catch (error) {
      setError(error.message);
    }
  };
};
```

You may want to give this a try and let us know if this can meet your needs. Thanks!

**Comment by subhendukundu** [comment]
Hmm, it does work. I forgot to mention that I had tried this with a different application I was using. Seems I am doing something wrong.

But thank you for clarifying. Yes, it does work calling `toggleVideo`.

**Comment by subhendukundu** [comment]
So for my other application, I am calling it from `useEffect` could that be an issue, from the same component.

```
export default function ChimeView({
  meeting,
  attendee,
}) {
  const meetingManager = useMeetingManager();
  const { isVideoEnabled, toggleVideo } = useLocalVideo();

  console.log('isVideoEnabled', isVideoEnabled); // this rendering twice even for any action on ControlBar's button. Could be an issue?

  useEffect(() => {
    const join = async () => {
      await meetingManager.join({
        meetingInfo: meeting,
        attendeeInfo: attendee,
        deviceLabels: DeviceLabels.Video,
      });
      await meetingManager.start();
      if (!isVideoEnabled) {
        toggleVideo();
      }
    };
    if (meeting && attendee) {
      console.log('joining now!');
      join();
    }
  }, [attendee, meeting]);
  return (
    <>
      <Box display="flex" flexDirection="column" flex={1} position="relative">
        <AttendeeChimeVideo />
      </Box>
    </>
  );
}
```

then AttendeeChimeVideo looks like

```
export default function AttendeeChimeVideo() {
  function onEndClick() {}
  return (
    <>
      <Box height="400px">
        <LocalVideo />
      </Box>
      <Box
        position="absolute"
        zIndex={2}
        bottom="50px"
        left="50px"
        width="300px"
        height="200px"
      >
        <ControlBar
          className="controls-menu"
          layout="undocked-horizontal"
          showLabels
        >
          <VideoInputControl />
          <ControlBarButton
            icon={<Phone />}
            onClick={onEndClick}
            label="Leave"
          />
        </ControlBar>
      </Box>
    </>
  );
}
```

**Comment by subhendukundu** [comment]
#420 sorry!
