### ISSUE TITLE
useMediaStreamMetrics is sending an empty videoStreamMetrics object

### ISSUE THREAD

**Issue by alexis-ld** [aws/amazon-chime-sdk-component-library-react#545]
**Describe the bug**
useMediaStreamMetrics is sending an empty videoStreamMetrics object even when multiple attendees have active video feeds.

**To Reproduce**
1. Connect to a meeting with multiple attendees with active videos
2. `	const metrics = useMediaStreamMetrics();
	console.log(metrics.videoStreamMetrics);
`
3. Check the console
4. See empty objects

**Expected behavior**
Have the object specified in the documentation  : 
```
videoStreamMetrics {
  attendeeId:{ // remote attendees will have downstream metrics
    ssrc: {
      videoDownstreamBitrate: number;
      videoDownstreamPacketLossPercent: number;
      videoDownstreamFramesDecodedPerSecond: number;
      videoDownstreamFrameHeight: number;
      videoDownstreamFrameWidth: number;
      videoDownstreamGoogFrameHeight: number;
      videoDownstreamGoogFrameWidth: number;
    }
  }
  attendeeId: { // local attendee will have upstream metrics
    ssrc: {
      videoUpstreamBitrate: number;
      videoUpstreamPacketsSent: number;
      videoUpstreamFramesEncodedPerSecond: number;
      videoUpstreamFrameHeight: number;
      videoUpstreamFrameWidth: number;
      videoUpstreamGoogFrameHeight: number;
      videoUpstreamGoogFrameWidth: number;
    }
  }
}
```

**Screenshots**
![Screenshot 2021-06-18 at 18 23 58](https://user-images.githubusercontent.com/3480526/122590962-8b74eb80-d062-11eb-8659-ae054d12d293.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser Tested on Chrome 91 & Firefox 89
 - Version 2.6.0

**Comment by ldai1** [comment]
Hi, 

Thanks for using the this new feature. Can you try to print out the metrics by using `console.log(JSON.stringify(metrics.videoStreamMetrics));`, or using 
```
const metrics = useMediaStreamMetrics();
metrics.forEach(attendeeId => { console.warn(metrics[attendeeId])});
```

**Comment by alexis-ld** [comment]
Hi @ldai1 . Thank you for you answer.

I managed to get the data. I don't really know why it just started working. Thank you for your help though.

I was wondering if there is a way to access content sharing metrics in there, for now I only see camera video feed metrics in the returned object. I need to figure out the content share dimensions (width / height) and I was expecting these data to be in videoStreamMetrics somehow. 
Not sure that is the scope of this ticket though, should I create a new ticket ?
