### ISSUE TITLE
How to switch between rooms?

### ISSUE THREAD

**Issue by subhendukundu** [aws/amazon-chime-sdk-component-library-react#549]
Let's say I am making an interview app. The app will always have two chime rooms(let's call them Interview room and lobby) which are always on in the same screen. No rerouting, like [breakoutrooms](https://github.com/aws-samples/amazon-chime-sdk-meetings-breakout-rooms).
There is one moderator(No audio-video require), one interviewer, and 10 attendees.
Moderator's job is to send one attendee at a time to the interview room. Once one attendee is done with the interview, comes back to Lobby again.
What is the best way to achieve this?

So far I have done, 

```
// App.ts
<MeetingProvider>
  <InterviewerView />
</MeetingProvider>

<MeetingProvider>
  <ModeratorView />
</MeetingProvider>
```
then
```
// InterviewerView.ts
const meetingManager = useMeetingManager();
const shortlistedUser = useSubscription(GET_SHORTLISTED_USER_FROM_APPSYNC); // This is what let this app know with who the new call going to be

useEffect(() => {
    const join = async () => {
        const meetingDetails = await api(`/get-meeting-details?shortlistedUser=${shortlistedUser}&interviewer=${interviewer}`); // This make sure i get meeting details and store to my database
       const joinData = {
          meetingInfo: meetingDetails.MeetingInfo,
          attendeeInfo: meetingDetails.AttendeeInfo,
          deviceLabels: DeviceLabels.Video,
        };
        await meetingManager.join(joinData);
        await meetingManager.start();
    };
    join();
}, [shortlistedUser]);

return(
   <FancyUiForInterviewer />
);

```

and 
```
// ModeratorView.ts
const meetingManager = useMeetingManager();
const meetingDetails = useSubscription(GET_LOBBYROOM_DETAILS);
useEffect(() => {
    const join = async () => {
       const joinData = {
          meetingInfo: meetingDetails.MeetingInfo,
          attendeeInfo: meetingDetails.AttendeeInfo,
          deviceLabels: DeviceLabels.Video,
        };
        await meetingManager.join(joinData);
        await meetingManager.start();
    };
    join();
}, [meetingDetails]);


const pushAttendee = (attendeeId) => async() => {
  const nextUser = attendees.find(
    item => item.chimeAttendeeId === attendeeId,
  );
  mutation({
    nextAttendeeToBeInterviewd: nextUser.attendeeId;
  });
}

const videos = Object.keys(attendeeIdToTileId).map(attendeeId => (
    <Box position="relative">
      <RemoteVideo key={attendeeId} tileId={attendeeIdToTileId[attendeeId]} />
        <Button
          variant="contained"
          color="primary"
          component="span"
          className={classes.pushButton}
          onClick={pushAttendee(attendeeId)}
        >
           Push attendee to Interview room
       </Button>
    </Box>
  ));

  return <>{videos}</>;

```

This works for sure. But there are a couple of issues.
1. Takes a bit of time to switch rooms for an attendee from one room to other (7-15secs). The same goes for the interviewer as well, Looks flickering.
2. Even the user has given access to device audio, video but for a room change, it asking/checking if permission is granted? Could be a reason for the delay in joining.
3. It might okay of 7-15 secs waiting time, for an interview app but we plan on extending this to other fields, where we need smooth transitions between rooms. A quick on especially.

Any help would be really helpful as we are close to prod and this kinda bothering our stakeholders. TIA.

**Comment by michhyun1** [comment]
@subhendukundu Hi there, have you checked out the components breakout room [blog post](https://aws.amazon.com/blogs/business-productivity/breakout-room-amazon-chime-sdk-react-component-library/)?

**Comment by subhendukundu** [comment]
Yes I had a chance. :) Like I pointed out in the comment, [line49](https://github.com/aws-samples/amazon-chime-sdk-meetings-breakout-rooms/blob/cdf5e885f9945e02b145ee3b42ddd77aa62274c8/front-end-resources/react-meeting/src/containers/BreakoutControls/BreakoutRoster.tsx#L49) is using a redirect, which kind of making user to wait till the page loads.
But in my case its a single page.
So each time, a user switch or pushed to interview room, there is a 7-10s loading time till the user join the meeting room. That's where I need help to make the experience better and smoother. The last few points in my above comment.

**Comment by michhyun1** [comment]
@subhendukundu the second time you join a meeting, you should be calling getUserMedia a second time - it shouldn't need to prompt you to allow the device permissions again.  Can you come through the support queue: https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support

Perhaps we can give you better support through a private channel.

**Comment by subhendukundu** [comment]
Sure I can do that.
Also, have you faced any issue with permission using `DeviceLabels.Video` with Firefox and Safari?
```
const joinData = {
    meetingInfo: meetingDetails.MeetingInfo,
    attendeeInfo: meetingDetails.AttendeeInfo,
    deviceLabels: DeviceLabels.Video,
};
```
Asking for permission for both video and audio. First Video, once accepted it is asking for audio too.

The same code doesn't ask permission for Audio in Chrome. Is there a way to stop this?

**Comment by devalevenkatesh** [comment]
Yes, I think that is browser specific behavior respective to Chrome and Firefox when they ask for device permissions.

You can try the same at the WebRTC demo here: https://appr.tc and check if you get the same behavior.

**Comment by subhendukundu** [comment]
I have tried using chime sdk directly with
```
meetingSession.audioVideo.setDeviceLabelTrigger(async () => {
    return await navigator.mediaDevices.getUserMedia({
      audio: false,
      video: true,
    });
      });
 ```
 Both the browser not asking for audio access now. So [MeetingManager.ts#L290](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L290)should say specifically not to take access like so
 ```
 switch (deviceLabels) {
    case DeviceLabels.Audio:
      constraints.audio = true;
      constraints.video = false;
      break;
    case DeviceLabels.Video:
      constraints.audio = false;
      constraints.video = true;
      break;
    case DeviceLabels.AudioAndVideo:
      constraints.audio = true;
      constraints.video = true;
      break;
  }
```
Please let me know if this okay. :) More than happy to create a PR as well.

**Comment by xuesichao** [comment]
> I have tried using chime sdk directly with
> 
> ```
> meetingSession.audioVideo.setDeviceLabelTrigger(async () => {
>     return await navigator.mediaDevices.getUserMedia({
>       audio: false,
>       video: true,
>     });
> });
> ```
> 
> Both the browser not asking for audio access now. So [MeetingManager.ts#L290](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L290)should say specifically not to take access like so
> 
> ```
> switch (deviceLabels) {
>    case DeviceLabels.Audio:
>      constraints.audio = true;
>      constraints.video = false;
>      break;
>    case DeviceLabels.Video:
>      constraints.audio = false;
>      constraints.video = true;
>      break;
>    case DeviceLabels.AudioAndVideo:
>      constraints.audio = true;
>      constraints.video = true;
>      break;
>  }
> ```
> 
> Please let me know if this okay. :) More than happy to create a PR as well.

Hi @subhendukundu, this issue is known to us. And the cause of it is the difference of permission design between different browsers.
You can check the code here [MeetingManager.ts#L347to#L349](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L347to#L349), we tried to use these boolean variables to control the later `select*Device` function calls. But the behavior of `enumerateDevices()` varies. 

Let's say, we only grant `audio` permissions to the browser and call `await navigator.mediaDevices.enumerateDevices() `. 

**Firefox** will expose all the device info for all kinds of devices. 
![image](https://user-images.githubusercontent.com/20471438/124319995-f1b44080-db2f-11eb-97d7-871d96c74dc9.png)

**Safari** will expose all the device info except `groupId` for all kinds of devices. 
![Safari Permission](https://user-images.githubusercontent.com/20471438/124319898-c598bf80-db2f-11eb-9de3-e4c16feeb0e5.png)

**Chrome** will expose the completed device info of the requested type.
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/20471438/124319874-bd408480-db2f-11eb-87c4-341f15991866.png">

That's why the current solution works only in Chrome.

It seems there is no one-for-all solution to check the device permission in different browsers. Maybe we could store the `constraints` of `getUserMedia` in the SDK and check depend on it.
