### ISSUE TITLE
individual one-one Chat feature instead of channel and room or a meeting instance.

### ISSUE THREAD

**Issue by syedshahabPTG** [aws/amazon-chime-sdk-component-library-react#551]
1. I'm trying to implement the Chat feature into an application. i'm having trouble understanding and implementing chat between 2 users instead of creating a channel or room i want to make the 2 users chat like a typical chatting application.
i'm unable to find any API request which helps me with this or any sample application with this feature implementation.
the sample code application provided in here also only has chat using channels and not directly chatting with users without adding them to a room. i've tried the data messages it doesn't fit my requirement because from my understanding the data message requires an active meeting session. i want the users to chat with and without an active meeting session.

2. there is no clear documentation on how to replace the AWS amplify and cognito services with other authentication and users from my database.

3. i'm unable to find both of the above in [amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react) either.

4. are there any react hooks available to implement the chat features?

**Comment by dpwspoon** [comment]
Hey, hope the following helps:

> 1. I'm trying to implement the Chat feature into an application...

The Chime Messaging API is channel based.  You can setup a 2 person channel.  See https://github.com/aws-samples/amazon-chime-sdk/issues/18#issuecomment-872583962 for some overview how to do this.  With chat (as opposed to data messages), the messages could be persisted and members would be able to send messages out side of a meeting.

> 2. there is no clear documentation on how to replace the AWS amplify and cognito services with other authentication and users from my database.

See this blog article for a better understanding of your options on how to integrate with your auth: https://aws.amazon.com/blogs/business-productivity/integrate-your-identity-provider-with-amazon-chime-sdk-messaging/.  TL;DR, the messaging SDK is driven by temporary IAM creds you grant to end user client applications.  Cognito Identity Pools can integrate with standards based Identity Providers to do this serverlessly.  Alternatively, you can run a small lambda (Backend process) that your users calls, you do any custom auth logic you want and then return them temporary creds.  Both options are demoed here: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat

> 3. i'm unable to find both of the above in amazon-chime-sdk-component-library-react either. and 4. are there any react hooks available to implement the chat features?

The Messaging SDK consists of two low level parts, REST APIs and websocket library on which realtime events are delivered.  The REST APIs ship with the standard AWS SDK.  The websocket library for javascript is in amazon-chime-sdk-component-library-react.  There are no react component UI for messaging in side of amazon-chime-sdk-component-library-react (yet).  But you might be able to re-use pieces from the chat demo mentioned above: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat

**Comment by syedshahabPTG** [comment]
TypeError: Cannot read property 'ChannelArn' of undefined
ChatWindow
src/components/ChatWindow.js:224
  221 | currentMember={member}
  222 | setChannelList={setChannelList}
  223 | channelList={channelList}
> 224 | channelArn={activeChannelRef.current.ChannelArn}
      | ^  225 | setChannelMessageToken={setChannelMessageToken}
  226 | activeChannelRef={activeChannelRef}
  227 | channelName={activeChannel.Name}
View compiled
▶ 18 stack frames were collapsed.
(anonymous function)
src/Routes.js:23
  20 | const assessLoggedInState = () => {
  21 |   Auth.currentAuthenticatedUser().then((sucess) => {
  22 |     console.log("logged in")
> 23 |     setloggedIn(true);
     | ^  24 |   })
  25 |     .catch(err => {
  26 |       console.log("unable to login", err)
  
  
  getting the above error as soon as i reach the chat screen.

**Comment by dpwspoon** [comment]
Please file a different issue with steps to reproduce under the demo repository you are trying?  Presumably you are trying this demo: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat?  Or are you modifying demo and hitting issue?
