### ISSUE TITLE
ContentShareProvider allows a single Share tileId

### ISSUE THREAD

**Issue by prashanthacharyam** [aws/amazon-chime-sdk-component-library-react#555]
**Describe the bug**
ContentShareProvider allows a single Share tileId.

**Expected behavior**
Chime SDK allows 2 simultaneous content shares per meeting. So should't the ContentShareProvider provider 2 tileIds to bind to?

**Comment by ldai1** [comment]
Hi,

Thanks for using Chime React SDK. Can I get some context about where you are seeing supporting 2 simultaneous content shares per meeting? It seems like in our current implementation，we only support one content share per meeting.

**Comment by devalevenkatesh** [comment]
Marking this as duplicate to keep one feature request issue on allowing  2 content shares.
Please find the other reported issue:
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/606
