### ISSUE TITLE
How to find person who is currently speaking in the meeting?

### ISSUE THREAD

**Issue by pawanlakhera77** [aws/amazon-chime-sdk-component-library-react#563]
### What are you trying to do?

I am trying to find the speaker who is currently speaking in the meeting. If no one is speaking then it should return empty.
 
### How can the documentation be improved to help your use case?
I found there is something like useActiveSpeakersState but it does not return the speaker who is currently speaking in the meeting. Also when no one is speaking it still returns the array.

### What documentation have you looked at so far?

I have looked at the Amazon Chime React SDK storybook so far. 
@p-foucht @justindarc @alpjor

**Comment by ltrung** [comment]
@pawanlakhera77 I documented the default behavior of the active speaker detector here https://github.com/aws/amazon-chime-sdk-js/blob/master/integration/js/pages/AppPage.js#L389.
You can create your own speaker detector policy and tweak them to fit your need and specify them in the audio video provider similar to here https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L343
