### ISSUE TITLE
Preview the local feed without creating a session

### ISSUE THREAD

**Issue by Arman-AP** [aws/amazon-chime-sdk-component-library-react#565]
Currently, it seems like that in order to actually preview the users camera settings you need to have joined a meeting already. Otherwise, the device list are not populated and camera feed is not active. 

What is the correct and efficient way to preview the devices (truly preview) without creating a meeting session ?

I realize that     deviceController.listVideoInputDevices();  has the data that i need, and based on this [demo here](https://github.com/aws/amazon-chime-sdk-js/blob/4ac2b02c7ef6118de425a486d764ba7221773f15/demos/browser/app/meetingReadinessChecker/meetingReadinessChecker.ts#L414) I could create custom functions that manually modify the UI.... 

But I was wondering if there is an easier way through the component library? I would like to create a simple "Device Settings" page where regardless of any active meeting or what not, I can let the user select and preview their devices.

**Comment by jing-chen1** [comment]
Hi @Arman-AP, thanks for your interest in React component library.

Unlike the JS SDK, a meeting session should be created so the user can preview and select their devices. Here is the [device provider](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/src/providers/DevicesProvider) in React library, you can see all these providers need the `meetingManager`. We first create a meeting and initialize a `meetingManager`, so the functions like `meetingManager.selectedAudioInputDevice`, `meetingManager.selectedAudioOutputDevice` can be called to select devices.

**Comment by ltrung** [comment]
@Arman-AP Unfortunately, the current device setup is tied to meeting provider join function (https://github.com/aws/amazon-chime-sdk-component-library-react/blob/5f3e8df79d9769165e3431c9465fcde64623e127/src/providers/MeetingProvider/MeetingManager.ts#L162). However, you can workaround this problem by passing a dummy meeting and attendee info (thus, you do not need to create a meeting beforehand). 
After the device preview, you can call `createMeeting` and `createAttendee` and call join again with the valid meeting and attendee info.
Let me know if that works for you.

**Comment by Arman-AP** [comment]
Thank you very much. The dummy meeting does the job. I am having another unique problem which I saw a lot of discussion on in the javascript sdk about: [#1](https://github.com/aws/amazon-chime-sdk-js/issues/423) [#2](https://github.com/aws/amazon-chime-sdk-js/issues/914) but couldn't figure out the problem on the sdk or rather a solution to it. On iphone safari, preview workes on and off, i saw my preview but then its not been working and has been throwing these errors: 

![image](https://user-images.githubusercontent.com/47894868/126590136-0892d053-5bb9-463c-b1b9-c03fb21f6b38.png)

Any idea? (sorry if I should have made a new issue for it)

**Comment by devalevenkatesh** [comment]
hi @Arman-AP ,

Sorry, but could you please create a new issue for your error if you are still facing it. It is very easy to lose if it is a different error places inside a different issue. Sorry for the inconvenience. We would also like you to please create the issue using the bug template. Request you to also provide complete browser console logs (not only error ones) to better understand the issue.

**Comment by dodsky** [comment]
> However, you can workaround this problem by passing a dummy meeting and attendee info (thus, you do not need to create a meeting beforehand).
@ltrung can you please elaborate on the exact details of what a dummy meeting and attendee is in this context? I'm not seeing the code in any examples, or docs. Thank you.
