### ISSUE TITLE
Is the client created with this react component library compatible with the server created from chime-sdk?

### ISSUE THREAD

**Issue by RaviVinnakota** [aws/amazon-chime-sdk-component-library-react#568]
Hi,

I have created server from the serverless of https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless

But, I would like to build a client with ReactJS, so landed here in this repo amazon-chime-sdk-component-library-react
I see that there is different in the way these 2 libraries are implemented. In this react library in the serverless/src/template.yml there is ChimeSdkAttendeeLambda. But this is missing in the amazon-chime-sdk-js repo.

Could you please let me know if there is compatibility between these repos?

Thanks,
Ravi V.

**Comment by ltrung** [comment]
@RaviVinnakota They are similar with few minor differences. In this case, `chimeSdkAttendeeLambda` was a lambda to retrieve the attendee name from the DynamoDB table. 
When we create a meeting and attendee, we put the meetingId and attendee info in a DynamoDB table. So if you rejoin we will fetch that information. In the JS SDK meeting demo, we only store the meetingId and thus, there is no attendee lambda.

**Comment by ltrung** [comment]
I think its probably faster for you to just use the react library template in this case.

**Comment by RaviVinnakota** [comment]
Thanks @ltrung for quick response. When you mentioned it is probably faster to use react library template in my case, did you mean using this specific folder for client implementation ? https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting/src
