### ISSUE TITLE
setIsVideoEnabled from useVideoLocal is coming up as "undefined"

### ISSUE THREAD

**Issue by thlee1122** [aws/amazon-chime-sdk-component-library-react#582]
### What happened and what did you expect to happen?

I am in the process of implementing "pagination" for the grid in my web application. 
![Screen Shot 2021-08-02 at 3 30 41 PM](https://user-images.githubusercontent.com/18387214/127913559-dfe64f9c-d511-4d93-858e-cc1482ddea99.png)

When I go to the next page, it would automatically turn localVideo "OFF".
Therefore, I wanted to use "setIsVideoEnabled" to turn localVideo "ON"
const { isVideoEnabled, setIsVideoEnabled } = useLocalVideo();

However, setIsVideoEnabled comes up as "undefined" and get "TypeError: setIsVideoEnabled is not a function"

Observation:
- When I look into https://github.com/aws/amazon-chime-sdk-component-library-react/blob/d4c837f653912ddda1c3034da76a1b64c5181cf6/src/providers/LocalVideoProvider/index.tsx 
"setIsVideoEnabled" is not passed as part of the "value" in the "provider". (line 77)

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

1. In any components that are wrapped around with MeetingProvider, import "useLocalVideo" from 'amazon-chime-sdk-component-library-react'

2. const { setIsVideoEnabled } = useLocalVideo();

3. Try to use "setIsVideoEnabled", you will get "TypeError: setIsVideoEnabled is not a function"

### Amazon Chime SDK React Components Library version

^2.4.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

91.0.4472.164

### Device Information

MacOS, Windows, Android

### Browser console logs

![Screen Shot 2021-08-02 at 3 41 41 PM](https://user-images.githubusercontent.com/18387214/127914728-50b98d47-5dc0-478a-9a0a-3ce6586ace5f.png)

**Comment by devalevenkatesh** [comment]
Hi @thlee1122 ,

Thanks for reporting the issue and we apologize for the delay. Could you please confirm which version of React SDK are you trying to use? The version you mentioned says `^2.4.0` but check if you are using version `2.7.0` as the change which adds the `setIsVideoEnabled` to `LocalVideoProvider` was introduced in [`v2.7.0`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/CHANGELOG.md#added-1).

Your linked `LocalVideoProvider` is actually linking the `amazon-chime-sdk-component-library-react`'s [`2.2.0`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/d4c837f653912ddda1c3034da76a1b64c5181cf6/package.json#L3) version.

Also, this `setIsVideoEnabled` function only sets the value of the video being enabled or disabled. If you want to start or toggle the video you have to use `toggleVideo()` from `useLocalVideo()` hook.

Please let us know if you are still running into the issue.

**Comment by thlee1122** [comment]
Hello @devalevenkatesh 

Thank you for the response.
I did check the version of the `amazon-chime-sdk-component-library-react` that I am using in my app. I am using 2.4.0 version.

I am still running into the issue.
Whenever, I go to the next page, my local video doesn't get displayed on the page.
By using `isVideoEnabled` in `useLocalVideo()` hook, I can see that `isVideoEnabled` is coming up as `true` and my computer's camera is still on.
However, my local video doesn't get displayed on the page.
Although, I don't see my local video on the page, other attendees on the same call is able to see my video.
Do you know why this might be happening?

**Comment by devalevenkatesh** [comment]
Could you please more elaborate on "I am still running into the issue."?
- Are you still seeing `setIsVideoEnabled` as `undefined`? If yes you have to upgrade the library version to 2.7.0.

For the local video not showing up:
- Could you please elaborate on how you render the `LocalVideo` and paginate?
- What if you force set the `isVideoEnabled` to false and then use `toggleVideo()` from `useLocalVideo()` hook?

I am suspecting if there is a bug in unmounting `LocalVideo` (if your `LocalVideo` is unmounting, which may not be the case as remote attendees are still able to see your video. When `LocalVideo` unmounts we unbind the local video stream from local video element reference hence remote attendee should not be able to see your video). Currently, we do not set `isVideoEnabled` to false when the `LocalVideo` component unmounts.

**Comment by devalevenkatesh** [comment]
Hello, I am closing this issue due to in-activity please feel free to re-open and request you to check my last comment on the same.
