### ISSUE TITLE
The `audioVideoDidStop()` callback is not called when meeting has ended/failed

### ISSUE THREAD

**Issue by amardeep24** [aws/amazon-chime-sdk-component-library-react#605]
### What happened and what did you expect to happen?

The `MeetingManager.audioVideo.addObserver()` method accepts an `AudioVideoObserver` implementation, which has a callback `audioVideoDidStop()`. This callback should have been called when the meeting has been ended or the meeting failed due to network disruption.

### Have you reviewed our existing documentation?

- [x] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

Step1: Join the meeting `MeetingManager.join(joinInfo)`

Step 2: Start audio video `MeetingManager.start()

Step 3: Disconnect network for > 10 mins, `audioVideoDidStop()` not called when meeting ended.

### Amazon Chime SDK React Components Library version

2.8.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 93.0.4577.63 (Official Build) (x86_64)

### Device Information

macOS Big Sur 11.4

### Meeting and Attendee ID Information.

```
{
  "meeting": {
    "meetingId": "dcd32ca2-34bf-4049-a7b5-925be0eb0706",
    "externalMeetingId": "ad927913-fedb-4ddd-8506-840f7cf28ddb",
    "mediaPlacement": {
      "audioHostUrl": "0307003aa242bb954d28cbd581b9dba3.k.m2.ue1.app.chime.aws:3478",
      "audioFallbackUrl": "wss://haxrp.m2.ue1.app.chime.aws:443/calls/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenDataUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/v2/screen/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenSharingUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/v2/screen/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenViewingUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "signalingUrl": "wss://signal.m2.ue1.app.chime.aws/control/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "turnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions",
      "eventIngestionUrl": null
    },
    "mediaRegion": "us-east-1"
  },
  "attendee": {
    "externalUserId": "9130354383887926",
    "attendeeId": "4b45c6b4-ff2d-d60c-6aa1-be4936ca1d58",
    "joinToken": "NGI0NWM2YjQtZmYyZC1kNjBjLTZhYTEtYmU0OTM2Y2ExZDU4OjM0N2RmYmRmLTQxYzYtNDkwNS04YjA0LWU3NWZlNjRmNjhmOA"
  }
}
```

### Browser console logs

[MeetingManager audioVideoDidStop] session stopped with code 19

**Comment by jing-chen1** [comment]
Hi @amardeep24, thanks for pointing this out! 

We tried on the [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting), the function `audioVideoDidStop()` will be called if the network is not available for about 3 mins. But if you leave normally, the `audioVideoDidStop()` has not been called. The root issue is that we remove all observers before the `audioVideoDidStop()` being called in the `audioVideo.stop()` [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f74f0e14948c486953daa2da77478a490d370a16/src/providers/MeetingProvider/MeetingManager.ts#L232). We are working on it.

**Comment by vidya-mohan** [comment]
@amardeep24 - fix has been merged and will be available in the next release

**Comment by devalevenkatesh** [comment]
Closing this issue as we have released the new version.
