### ISSUE TITLE
useActiveSpeakersState hook return someone continuously when all attendees are muted

### ISSUE THREAD

**Issue by merryblack** [aws/amazon-chime-sdk-component-library-react#609]
### What happened and what did you expect to happen?

Hi, I am using useActiveSpeakersState hook to display active speaker.

But when all attendees are not speaking or even when all attendees muted their mic, hook still return array include someone's id continuously.

I expect to get return empty array in this case, so I want to clear activeSpeaker in a quiet moment!

(or if there is another way to solve this case, please let me know!)

Thanks! :)

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

```
  const activeSpeakers = useActiveSpeakersState();

  useEffect(() => {
    console.log('activeSpeakers -> ', activeSpeakers);
    if (activeSpeakers) {
      setActiveSpeakerId(activeSpeakers[0]);
    } else {
      setActiveSpeakerId(null);
    }
  }, [activeSpeakers]);
```

### Amazon Chime SDK React Components Library version

2.9.1

### What browsers are you seeing the problem on?

chrome

### Browser version

93.0.4577.63

### Device Information

macOS

### Browser console logs

https://user-images.githubusercontent.com/12963185/132654758-ae0129c4-453e-4d1b-be62-fb01c1cf1ea2.mov

<img width="1122" alt="screenshot" src="https://user-images.githubusercontent.com/12963185/132654794-a4257411-d96e-48a3-b584-56669e2cdeb4.png">

**Comment by ltrung** [comment]
It is not an issue for the React Component Library but is a behavior from the main JS library. Please refer to this  https://github.com/aws/amazon-chime-sdk-js/issues/1132#issuecomment-800790372 as it explains how active speaker works. Maybe you can use `useAttendeeAudioStatus` to see whether everyone is muted.

**Comment by ltrung** [comment]
Feel free to reopen if you need more help.

**Comment by merryblack** [comment]
Thanks! :)
