### ISSUE TITLE
set VoiceFocusSpec and options when using useVoiceFocus

### ISSUE THREAD

**Issue by merryblack** [aws/amazon-chime-sdk-component-library-react#612]
This is my previous code when I was not using chime with react.
```
      transformer = await VoiceFocusDeviceTransformer.create(
        { variant: 'c10' },
        { logger: chimeSDKLogger },
      );
     ...
     await transformer.createTransformDevice(audioDeviceId)
```
{ variant: 'c10' } was very good experience for our users. but now It seems to be set to default, c100. and I cannot find the way to set this.
I want to set this option when use useVoiceFocus hook, too! :)

**Comment by jing-chen1** [comment]
Hi @merryblack, thanks for your interest! 

You can set the `VoiceFocusSpec` in the `VoiceFocusProvider`:
```
<VoiceFocusProvider spec={{ variant: 'c10' }}>
  ...
</VoiceFocusProvider>
```
Then the model complexity should be 10. Hope this helps.

**Comment by merryblack** [comment]
Thanks for your kind answer :)
