### ISSUE TITLE
Video settings are not saved

### ISSUE THREAD

**Issue by cruffinoni** [aws/amazon-chime-sdk-component-library-react#613]
### What happened and what did you expect to happen?

Device settings are not saved : 
- Device selection is reset on each page refresh.
- Video quality is not saved between the device selection screen before and during a meeting

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

Select device and refresh your webpage. You have to select the devices again.

### Amazon Chime SDK React Components Library version

2.9.1

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

93.0.4577.63

### Device Information

Windows 10

### Browser console logs

N/A

**Comment by simmkyu** [comment]
The Chime SDK React Components Library does not use any browser's storage, such as `localStorage`, to store data. You can use these browser's storage APIs to save and load a previously selected device ID or quality in your client application.

**Comment by devalevenkatesh** [comment]
Closing this issue as we do not use any local storage, request you to please re-open if you face any further issues. We also want to rely on `enumerateDevices` from Browser's mediaDevices as it might return new devices on refresh for some browsers.
