### ISSUE TITLE
[FEATURE REQUEST] Audio volume control

### ISSUE THREAD

**Issue by svrtelka** [aws/amazon-chime-sdk-component-library-react#622]
## Audio volume control

I'm sorry if this is already done somewhere, but I just can't find it. We have to be able to adjust the volume of a speaker with some slider component. Before we migrated to Chime, it was possible to adjust speaker volume in a meeting session and we don't want to introduce a regression by scraping this feature, since it can be useful for some users. 

We noticed that Chime renders the `<audio>` element , so would it be possible to access the element reference  through API? Thanks!

### Current workaround

There is a possible workaround by finding this element in DOM and changing the volume attribute, but it would be much better to be able to use the API for volume changes.

**Comment by devalevenkatesh** [comment]
Hi @svrtelka ,

Yes, you are correct we can only provide a workaround and do not have any API in Amazon Chime SDK for JavaScript. 

Here is a similar issue reported:
https://github.com/aws/amazon-chime-sdk-js/issues/1391#issuecomment-868774249

Closing this issue as we do not have any API.
