### ISSUE TITLE
Memory leak in LocalVideoProvider observer

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-component-library-react#626]
### What happened and what did you expect to happen?

In src/providers/LocalVideoProvider/index.tsx:72, there appears to be a memory leak in the audioVideo observer. It is not being removed in the useEffect hook when the component is unmounted.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

1. import the LocalVideoProvider and useLocalVideo() hook.
2. React reports memory leak when the component is unmounting.

### Amazon Chime SDK React Components Library version

2.8.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

93.0.4577.82

### Device Information

macOS Catalina 10.15.7

### Browser console logs

...
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in LocalVideoProvider (created by MeetingProvider)
    in RemoteVideoTileProvider (created by MeetingProvider)
    in RosterProvider (created by MeetingProvider)
    in VideoInputProvider (created by DevicesProvider)
    in AudioOutputProvider (created by DevicesProvider)
    in AudioInputProvider (created by DevicesProvider)
    in DevicesProvider (created by MeetingProvider)
    in AudioVideoProvider (created by MeetingProvider)
    in MeetingProvider (created by Meeting)
...

**Comment by xuesichao** [comment]
Raised PR #631 to fix the issue and it's merged. Close this issue and feel free to open it if you have any other questions. Thanks for using our SDK!

**Comment by Nanosync** [comment]
Hi @xuesichao, thank you for the response! I think there's a bug in the fix... Shouldn't the observer object be stored as a variable and added/removed as its own reference?

I checked the underlying audioVideo code which stores observer objects in a Set.

Fix in PR #631 :
```
const a = new Set();
const myObj = "hello";
a.add({ myObj });
a.delete({ myObj }); // returns false
console.log(a); // a contains Set(1)
```

Intended fix:
```
const a = new Set();
const myObj = "hello";
const objRef = { myObj };
a.add(objRef);
a.delete(objRef); // returns true
console.log(a); // a contains Set(0)
```

**Comment by xuesichao** [comment]
@Nanosync Hi, thanks for pointing this out, I will fix it tomorrow morning 🤝

**Comment by xuesichao** [comment]
@Nanosync Hi, really appreciate your help. I confirmed this bug exists and it might be an issue in other places in the code. we will check and keep this issue posted once we get a fix out. I will open this issue for now. Thanks for all your help!

**Comment by xuesichao** [comment]
@Nanosync Raised the above PR #634 to fix the bug and it's merged. We appreciate your patience and help and thanks for using our SDK!
