### ISSUE TITLE
useAudioInputs returns empty array

### ISSUE THREAD

**Issue by akap97** [aws/amazon-chime-sdk-component-library-react#628]
### What happened and what did you expect to happen?

After accepting the prompt to allow microphone access, useAudioInputDevices hook still shows empty array.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

join a meeting, accept permission prompt and call useAudioInput hook to get list of input devices.

### Amazon Chime SDK React Components Library version

2.9.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

 93.0.4577.63 (Official Build) (64-bit)

### Device Information

Ubuntu 20

### Browser console logs

N/A

**Comment by xuesichao** [comment]
Hi @akap97 thanks for bringing up this issue. I couldn't reproduce it in our [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting). Could you please try to reproduce it there? Let us know how it goes and what's your steps.

In addition to the above, could you please give us more information about:
* Did you use `MeetingProvider`? If so how?
* Things may be different in your App. Could you give use some more detailed retro steps? e.g. what do you exactly mean by 'join the meeting', is that an API call or something else? How did you triggered the permission prompt?

**Comment by jing-chen1** [comment]
Hi @AlexMCarv,

We use the `MicSelection` and `CameraSelection` provided by React Library in the preview page of meeting demo. And in these 2 components, we call the `useAudioInputs` and `useVideoInputs` hooks. In the 2.9.0, we add `MeetingEventProvider`, so you would see some logs on the browser if audio & video are available
```
Received meeting event in MeetingEventObserver {name: 'audioInputSelected'....
Received meeting event in MeetingEventObserver {name: 'videoInputSelected'....
```
The possible reason is we move `this.publishAudioVideo()` up like you said
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L314 #

I create a new branch named `useVideoInputs`, could you please checkout that branch? Then pack it as a tar file and install this tar file as the new dependency for `amazon-chime-sdk-component-library-react` and see if it works?
(Just in case you are not familiar with this process: 1. git clone React Library 2. `git checkout useVideoInputs` 3. `npm run build`, `npm run pack` 4. go to your app 5. npm install path-to-tarball)
