### ISSUE TITLE
Additional Devices should be optional

### ISSUE THREAD

**Issue by subhendukundu** [aws/amazon-chime-sdk-component-library-react#629]
### What happened and what did you expect to happen?

This is more of a feature request.
```
const videoInputConfig: DeviceConfig = {
  additionalDevices: true,
};
```
[VideoInputControl.tsx#L21](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/sdk/MeetingControls/VideoInputControl.tsx#L21) 

We should make this configurable. We have requirement where we don't need the extra devices. Of course I can use `useVideoInputs` my own and make it as it should work. Then we have to write few additional functionality which already there.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

Use VideoInputControl directly with Controlbar.

### Amazon Chime SDK React Components Library version

2.9.1

### What browsers are you seeing the problem on?

All

### Browser version

Not important

### Device Information

Not important

### Browser console logs

Not important

**Comment by michhyun1** [comment]
@subhendukundu thanks for calling this out - we can certainly make this configureable on our end.

**Comment by LeviSklaroff** [comment]
This is now a feature in the newest version in the react library. Going to close this issue, if this feature does not work for your use case please feel free to reopen this issue.
