### ISSUE TITLE
ControlBarButton button focus issue

### ISSUE THREAD

**Issue by kishan-tocca** [aws/amazon-chime-sdk-component-library-react#642]
### What happened and what did you expect to happen?

I used this element for controllbar view , while clicking any button the focus was on that button and its getting fired by keyboard keys (Enter and Spacebar)
I expect to event don't get fired on keyboard keys

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

just once click on any controllbar button and after that click on keyboard Enter or Spacebar keys

### Amazon Chime SDK React Components Library version

2.1.0

### What browsers are you seeing the problem on?

Google chrome , firefox

### Browser version

Version 94.0.4606.61 (Official Build) (64-bit)

### Device Information

Ubuntu 20.04.3 LTS

### Browser console logs

![screenshot-localhost_3000-2021 10 08-15_36_25](https://user-images.githubusercontent.com/66630960/136538341-b8061df2-8093-4b8a-97f0-b7f766546d57.png)

**Comment by ldai1** [comment]
Hi,

Thanks for using Amazon Chime SDK Component Library. Just to confirm that you want to prevent the button from receiving focus on click, right? This might has some implications for accessibility and we need to double check if this is the consistent focus state for all our buttons and inputs before we can make any changes. Will come back to you once we are done with our research.

**Comment by kishan-tocca** [comment]
> Hi,
> 
> Thanks for using Amazon Chime SDK Component Library. Just to confirm that you want to prevent the button from receiving focus on click, right? This behavior might has some implications for accessibility and we need to double check if this is the consistent focus state for all our buttons and inputs before we can make any changes. Will come back to you once we are done with our research. Thanks for bringing this up.

thanx for your response. yes I want to prevent that focus because click event getting trigger by other keyboard buttons
