### ISSUE TITLE
Clarify that useAudioOutputs hook will only return devices on some browsers

### ISSUE THREAD

**Issue by TheMoonDawg** [aws/amazon-chime-sdk-component-library-react#650]
### What are you trying to do?

I was trying to list the available audio output devices for my browser, but the hook never returned any devices. It took some digging, but I discovered it was because browsers like Firefox and Safari/iOS disallow the user to change the default audio output as discussed here: https://github.com/aws/amazon-chime-sdk-js/issues/1499 

### How can the documentation be improved to help your use case?

Specify that the `useAudioOutputs` will not return any devices for Firefox or Safari/iOS.

### What documentation have you looked at so far?

I read the documentation on the `useAudioOutputs` hook: https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useaudiooutputs--page

**Comment by michhyun1** [comment]
Sure, we can include this in our documentation for the React Library. Its also mentioned here: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue
