### ISSUE TITLE
toggleVideo not working with useEffect

### ISSUE THREAD

**Issue by davidshq** [aws/amazon-chime-sdk-component-library-react#659]
### What happened and what did you expect to happen?

I have a button which launches a new meeting. The meeting is successfully created, I can see the camera is enabled (red recording icon on Chrome tab) but `<LocalVideo />` shows nothing.

This is implemented using React's `useEffect` like so:
```js
   useEffect(
    () => {
      setTimeout(toggleVideo, 100);
    }, []
  );
```

If I lengthen the timeout, e.g.:
```js
   useEffect(
    () => {
      setTimeout(toggleVideo, 1000);
    }, []
  );
```

After around 8 seconds I get a black window, but it never populates with the actual video. I've tried making the timeout longer and waiting around 1 minute, but no change.

I've also setup a button which when clicked calls on toggle, like so:

```js
  const handleToggleVideo = () => {
    toggleVideo();
  };
```
Clicking on it shows `LocalVideo` populated with my camera's view almost immediately.

I have tried both on the same page. If I do this I have to click the button twice, first to turn the toggle off and then to turn it back on again. It works fine after doing so.

This seems to indicate that the toggle is being triggered but for some reason rendering is not occurring.

I've tried updating my amazon-chime-sdk-js and amazon-chime-sdk-component-library-react packages to the latest available (2.20.0 and 2.11.1 respectively) but this makes no difference (I was using 2.17.0 and 2.9.1 respectively).

When useEffect is triggered it is creating the following in the DOM:
```js
<div class="sc-eggMyH fyvIHI sc-fbkiRW jykPXa" data-testid="video-tile">
  <video class="ch-video"></video>
</div>
```

When it is manually triggered via a button we see the following:
```js
<div class="sc-eggMyH fyvIHI sc-fbkiRW jykPXa" data-testid="video-tile">
  <video class="ch-video" 
    disablepictureinpicture="" 
    disableremoteplayback="" 
    autoplay="true" 
    playsinline="true" 
    muted="true" 
    style="transform: rotateY(180deg); object-fit: cover;"
   >
   </video>
</div>
```

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

This is difficult to reproduce. Under some circumstances this works correctly, but under others it does not display. I have been unable to find a distinguishing factor thus far regarding when it works / doesn't.

### Amazon Chime SDK React Components Library version

2.11.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

 95.0.4638.54

### Device Information

Ubuntu Desktop 20.04

### Browser console logs

[MeetingManager audioVideoDidStart] Meeting started successfully

**Comment by arpitmittal-lab** [comment]
@devalevenkatesh I have used toggle video as described, but sometimes I am getting the black video of the user on other end.

Can you please check logs? 
Issue URL with logs: https://github.com/aws/amazon-chime-sdk-component-library-react/issues/694

**Comment by devalevenkatesh** [comment]
Hi @arpitmittal-lab ,

Request you to please create a new issue since this is addressed and does not come up in triaging as it is closed one.

The toggleVideo is for the local attendee only for the remote you have to use the `RemoteVideo` component and can check following this repo I created for this purpose:
https://github.com/devalevenkatesh/test-amazon-chime-sdk-react-components/blob/main/src/Home.tsx

Request again to create a new issue to discuss more if run into more problems.

**Comment by ArianHamdi** [comment]
> Hi @davidshq ,
> 
> Thank you for reporting the issue, I see that your use case is to toggle the video ON once the meeting starts if I understand correctly. The `setTimeout` wont work as you are not listening on when the meeting is successfully started.
> 
> I have created a repo which showcases how to toggle the local video once meeting starts. Could you please checkout the repo: https://github.com/devalevenkatesh/test-amazon-chime-sdk-react-components
> 
> Basically, you have to use [`useMeetingStatus`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemeetingstatus--page) hook and toggle the video once you get a "Succeeded" `MeetingStatus`.
> 
> ```
> import {
>   LocalVideo,
>   useLocalVideo,
>   useMeetingStatus,
>   MeetingStatus,
> } from 'amazon-chime-sdk-component-library-react';
> 
> function App() {
>   const meetingStatus = useMeetingStatus();
>   const { toggleVideo } = useLocalVideo();
> 
> useEffect(() => {
>     async function toggle() {
>       if (meetingStatus === MeetingStatus.Succeeded) {
>         await toggleVideo();
>       }
>     }
>     toggle();
>   }, [meetingStatus]);
> 
> return (
>     <div className="Home">
>       <div style={{height:'300px', width: '400px'}}>
>         <LocalVideo />
>       </div>
>       </div>
>   );
> }
> ```
> 
> Please let me know if you run into any issue.

Thanks a lot
