### ISSUE TITLE
How to show video tile with attendee name and mute status for attendees without video

### ISSUE THREAD

**Issue by Rambarani** [aws/amazon-chime-sdk-component-library-react#664]
### What are you trying to do?

I need to show participant name, profile pic or default pic or video mute icon and audio mute/un-mute status over the video tile.

I tried all components FeaturedRemoteVideos, VideoTileGrid, RemoteVideos. they show the video tile with name but can't able to add mute un mute  status over there. and also these will disappear  when participant turned off video.

I tried `getAllRemoteVideoTiles`  `getAllVideoTiles` API's these will return array with data for only who turned on video.

I got stuck with this. how can we show video tiles with name mute and unmute status even if video is turned off. 

![image](https://user-images.githubusercontent.com/51265513/140944973-9c689caf-8e3d-48ef-bdc9-1a3951713fef.png)

**Comment by xuesichao** [comment]
Hi @Rambarani. React Component Library doesn't have such a component for this use case. For now it only renders video tiles for those attendees who turn on the camera.

I think you goal is to assign a video tile for all attendees regardless of camera status. To do this, you need to build your own video tile for those turn off the video and your own video grid to render all the video tiles.

I didn't try this, but I think the general idea could be:
1. Get the number of attendees using [`useRosterState`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-userosterstate--page) hook and set the size of [`VideoGrid`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-video-videogrid--video-grid)
2. Build a component to generate the video tiles for all attendees, e.g., `AllVideoTiles`. 
   1. For those turn on the videos, you could just use [`RemoteVideo`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-remotevideo--page) and [`LocalVideo`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-localvideo--page) component.
   2. For those turn off the videos, you need to build your own video tile with icon, e.g., `EmptyVideoTile`. Refer to [`VideoTile`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-video-videotile--video-tile) and `RemoteVideo` component for help. 
      1. For those mute/unmute icon, the logic is similar to the [`MeetingRoster`](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/containers/MeetingRoster.tsx) component in our [React meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting). It use the [`useAttendeeState`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useattendeestatus--page) hook to get the `muted`, `videoEnabled`, `sharingContent` and `signalStrength` states. Check here to see the [usage](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/sdk/RosterAttendee/index.tsx#L20)
   3. Example of `MeetingRoster`:
   ![Roster](https://user-images.githubusercontent.com/20471438/141845245-41d32ff2-5efe-44b3-99b0-1161e4a0ee3c.png)
3. Use `VideoGrid` to render your `AllVideoTiles` component in a grid.


So a high level component tree structure is like:
```
<YourOwnVideoTileGrid>
  <VideoGrid>
    <AllVideoTiles>
      <LocalVideo/>
      <RemoteVideo/>
      <RemoteVideo/>
      ... a list of <RemoteVideo/>
      <EmptyVideoTile />
      <EmptyVideoTile />
      ... a list of <EmptyVideoTile/>
    </AllVideoTiles>
  </VideoGrid>
</YourOwnVideoTileGrid>
```
Some useful hook/component:
* [`useRemoteVideoTileState`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useremotevideotilestate--page) hook returns the remote attendees who turn on the video
* [`useRosterState`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-userosterstate--page) returns a list of attendees
* [`VideoTileGrid`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/sdk/VideoTileGrid/index.tsx#L43-L70) is a good example of the whole flow. You might want to start your exploration from here.

**Comment by Rambarani** [comment]
@xuesichao Thank you!. I will try.

**Comment by Oscarato** [comment]
Please some progress about this??

**Comment by suresh174** [comment]
@Rambarani  can you please share the components that you created for this feature to work?

**Comment by arpitprod** [comment]
I updated few components for this screen.  
<img width="1084" alt="Screenshot 2024-05-07 at 9 13 20 AM" src="https://github.com/aws/amazon-chime-sdk-component-library-react/assets/19798516/02e26acd-a370-4eb3-a937-1555e4098c37">

**Comment by xuesichao** [comment]
Hi @moezashfaq, in Chime SDK terms, a "video tile" is an object containing an attendee ID, a video stream, etc. To view a video in your application, you must bind a tile to a <video> element. When remote user turns off the video, SDK removes the tile for that user like you said.

I guess the name of `EmptyVideoTile` might get you confused. Basically you need to implement a component when `videoEnabled` is `false`.

![image](https://github.com/aws/amazon-chime-sdk-component-library-react/assets/20471438/315a39f3-6e68-44be-bfc0-e8654f04f91d)

**Comment by moezashfaq** [comment]
Thanks @xuesichao for the reply but the issue is I am using useAttendeeStatus and getting videoEnabled attribute but it always gives me a true value even tile is hiding for the remote user. 

For code reference:

```
function RemoteTiles() {
    const remoteTileState = useRemoteVideoTileState();
    const { tiles, tileIdToAttendeeId } = remoteTileState;
    const { roster } = useRosterState();
    const attendees = Object.values(roster);
    return (
        <>
            {tiles.map((tileId) => (
                <RemoteTile key={tileId} tileId={tileId} tileIdToAttendeeId={tileIdToAttendeeId} attendees={attendees}/>
            ))}
        </>
    );
}


function RemoteTile({ tileId, tileIdToAttendeeId, attendees}) {
    var attendeeId = tileIdToAttendeeId[tileId];
    const attendee = attendees.find(attendee => attendee?.chimeAttendeeId === attendeeId);
    const userName = attendee?.externalUserId.split("#")[1];
    const {
        muted,
        videoEnabled,
        sharingContent,
        signalStrength
    } = useAttendeeStatus(attendeeId);

    return (
        <div className="video-container-main">
            <RemoteVideo tileId={tileId} />
            <div className="roster-cell">
                <RosterCell
                    name={userName}
                    muted={muted}
                    sharingContent={sharingContent}
                    signalStrength={signalStrength}
                    videoEnabled={videoEnabled}
                />
            </div>
        </div>
    );
}
```

Can you please guide me, Where am I doing something wrong?

**Comment by xuesichao** [comment]
@moezashfaq I just tested that the `useAttendeeStatus` hook does update `videoEnabled` properly. Could you refer to this code for help? Your code looks good to me.
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/520c2d53c3b986f50701eb60f4272ad7fb158741/integration/app/test-demo/src/pages/RosterTestApp.tsx#L43-L71

And what does hiding mean?
> it always gives me a true value even tile is hiding for the remote user.

Is the remove video turned off or you just don't render it for local attendee?
