### ISSUE TITLE
I am trying to get the remote & local video separately. Earlier I was using VideoTileGrid component.

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#667]
### What are you trying to do?

I am trying to get the remote & local video so that I can add conditions like render the user image if it's camera permission is denied or camera is off.

Eg.
```
<div>
{localVideoPresent ? <MyLocalVideo /> : "No Local Video"}
</div
<div>
{remoteVideoPresent ? <MyRemoteVideo /> : "No Remote Video"}
 </div>

```
### What documentation have you looked at so far?
Amazon Chime Component React Library.

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue.

You can refer to [this](https://github.com/devalevenkatesh/test-amazon-chime-sdk-react-components/blob/main/src/Home.tsx) sample repo on using only the `LocalVideo` and `RemoteVideo` component.

```
const Home = () => {
  const { isVideoEnabled } = useLocalVideo();

  // Get remote video tiles if available and enabled by remote attendees.
  // You can use `RemoteVideos` component if you do not want to manage remote tiles and handle the remote tileId.
  // Simply, remove these two lines and the second useEffect which sets the remote tileId.
  // Change the {remoteTileId && <RemoteVideo tileId={remoteTileId} />} in return method to just <RemoteVideos />
  // `RemoteVideos` internally will handle the same for you but wont be limited to just one tileId.
  const { tiles } = useRemoteVideoTileState();

// UseEffect to set the remote video tile once remote attendee join with video already started.
  useEffect(() => {
    if (tiles && tiles.length) {
      setRemoteTileId(tiles[0]);
    } else {
      setRemoteTileId(undefined);
    }
  }, [tiles]);

return (
    <div className="Home">
      <div style={{height:'300px', width: '400px'}}>
        <LocalVideo />
      </div>
      <div style={{height:'300px', width: '400px'}}>
        {remoteTileId && <RemoteVideo tileId={remoteTileId} />}
      </div>
    </div>
  );
}
```

If you want to make it permission dependent then you can use [`useDevicePermissionStatus`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usedevicepermissionstatus--page) hook (it has limitations mentioned in the documentation) and get the status to enable `LocalVideo` but `LocalVideo` internally takes care of this and it won't show unless and until you have given permissions.

Please let me know if you need further help.

**Comment by arpitmittal-lab** [comment]
Thanks for your help @devalevenkatesh. Is there any way to get the call duration?

**Comment by devalevenkatesh** [comment]
You can use [`useMeetingEvent`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemeetingevent--page) hook which should give you various Amazon Chime SDK meeting events with corresponding attributes. Some meeting events will have the duration with it, check for "meetingDurationMs" in the Amazon Chime SDK Meeting Events [guide](https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html#meeting-attributes).

Resolving this issue now, please feel free to re-open if any issue.
