### ISSUE TITLE
Overriding `activeSpeakerPolicy` requires undocumented steps

### ISSUE THREAD

**Issue by kaizau** [aws/amazon-chime-sdk-component-library-react#668]
### What are you trying to do?

Override `ActiveSpeakerPolicy` with a custom instance.

### How can the documentation be improved to help your use case?

The docs from [MeetingManager > activeSpeakerPolicy](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-providers-meetingprovider--page) are incomplete.

In addition to passing`meetingConfig` to `<MeetingProvider>`, it's necessary to also pass it to `meetingManager.join({meetingManagerConfig: meetingConfig})`.

Otherwise the meeting continues to use the `DefaultActiveSpeakerPolicy`.

### What documentation have you looked at so far?

- https://aws.github.io/amazon-chime-sdk-js/interfaces/activespeakerpolicy.html
- https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-providers-meetingprovider--page

Ultimately, I was only about to figure this out by digging through the source.

Inserting a breakpoint at [`setupActiveSpeakerDetection()`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L491) revealed that `this.meetingManagerConfig.activeSpeakerPolicy` was still the default, despite passing a custom override via `<MeetingProvider>`.

I'm not sure if this is intended, so this one is arguably a bug. Either way, following the example given didn't work.

**Comment by devalevenkatesh** [comment]
@kaizau thanks for reporting this issue and sorry for the delay, we missed adding props through the MeetingProvider, added those now and you should be able to use the custom active speaker policy. 

Please note that if you pass a meetingManagerConfig prop through the meetingManager.join then that overrides any existing config passed through the MeetingProvider. That is already documented. 

We have merged the PR now and will be available in next release.

**Comment by jing-chen1** [comment]
Closing the issue since the fix is in released version.
