### ISSUE TITLE
How to get the device type (Mobile/Desktop) of other user?

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#672]
### What are you trying to do?

I am trying to know the device details of other user with whom I will be on call. Any Help?

**Comment by devalevenkatesh** [comment]
I think there is no way to know whether the remote attendee is an desktop or mobile user on the local side. Could you please elaborate on your use-case to check further?

**Comment by arpitmittal-lab** [comment]
I actually wanted to control the UI. Currently when some user is calling from mobile then on desktop i am getting a big vertical screen. If I can get the device of the caller then I can adjust it's UI comfortably.

**Comment by devalevenkatesh** [comment]
No, sorry we do not have any API on providing remote attendee details, probably you can still listen and check the video pixels from [`videoTileState`](https://aws.github.io/amazon-chime-sdk-js/classes/videotilestate.html) from `videoTileDidUpdate` observer callback. It has few attributes like width and height which can help knowing the aspect ratio and then if you find height > width or how you see fit for the video dimensions then handle the UI accordingly.

**Comment by devalevenkatesh** [comment]
Closing this due to no-activity. Please feel free to re-open if you still need help. Thanks.
