### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bgd') 

### ISSUE THREAD

**Issue by christiansaavedra** [aws/amazon-chime-sdk-component-library-react#675]
### What happened and what did you expect to happen?

Hello,

I've using Chime on my react app for months and it went well. Today, I updated react to version 17.0.2, and also Material UI to v5. Since then, I've been receiving this error when joining a meeting.

I also updated to the latest chime and react chime versions, but the error appeared on the old ones I had too.

I didn't received any errors on the network endpoints, they all returned 200.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Join a meeting

### Amazon Chime SDK React Components Library version

2.11.1 and my aws-chime-js is 2.21.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 96.0.4664.45 (Official Build) (arm64)

### Device Information

Desktop

### Browser console logs

TypeError: Cannot read properties of undefined (reading 'bgd')
push../node_modules/amazon-chime-sdk-component-library-react/lib/index.esm.js.gridData.usingGrid
node_modules/amazon-chime-sdk-component-library-react/lib/index.esm.js:5482
  5479 | var landscapeStyles = "\n  @media (max-height: 600px) {\n    grid-template-areas: 'ft ft' 'ft ft';\n    grid-template-rows: repeat(2,1fr);\n    grid-template-columns: 25%;\n    grid-auto-columns: 25%;\n    grid-auto-flow: column;\n  }\n";
  5480 | var StyledGrid$1 = styled.div(templateObject_1$f || (templateObject_1$f = __makeTemplateObject(["\n  position: relative;\n  display: grid;\n  height: 100%;\n  width: 100%;\n  overflow: auto;\n  background-color: ", ";\n\n  ", "\n  ", ";\n"], ["\n  position: relative;\n  display: grid;\n  height: 100%;\n  width: 100%;\n  overflow: auto;\n  background-color: ", ";\n\n  ",
  5481 |     "\n  ",
> 5482 |     ";\n"])), function (props) { return props.theme.videoGrid.bgd; }, function (_a) {
  5483 |     var size = _a.size, featured = _a.featured;
  5484 |     return ratioStyles["" + size + (featured ? '.featured' : '')] || '';
  5485 | }, function (_a) {
View compiled
Ne
src/utils/flatten.js:80
  77 |     }
  78 | 
  79 |     return flatten(result, executionContext, styleSheet, stylisInstance);
> 80 |   } else return chunk;
     | ^  81 | }
  82 | 
  83 | if (chunk instanceof Keyframes) {
View compiled
e.generateAndInjectStyles
src/models/ComponentStyle.js:90
  87 |   css += partRule;
  88 | 
  89 |   if (process.env.NODE_ENV !== 'production') dynamicHash = phash(dynamicHash, partRule + i);
> 90 | } else if (partRule) {
     | ^  91 |   const partChunk = flatten(partRule, executionContext, styleSheet, stylis);
  92 |   const partString = Array.isArray(partChunk) ? partChunk.join('') : partChunk;
  93 |   dynamicHash = phash(dynamicHash, partString + i);
View compiled
(anonymous function)
src/models/StyledComponent.js:80
  77 |   componentStyle: ComponentStyle,
  78 |   isStatic: boolean,
  79 |   resolvedAttrs: T,
> 80 |   warnTooManyClasses?: $Call<typeof createWarnTooManyClasses, string, string>
  81 | ) {
  82 |   const styleSheet = useStyleSheet();
  83 |   const stylis = useStylis();
View compiled
(anonymous function)
src/models/StyledComponent.js:125
  122 | 
  123 | const [context, attrs] = useResolvedAttrs(theme || EMPTY_OBJECT, props, componentAttrs);
  124 | 
> 125 | const generatedClassName = useInjectedStyle(
      | ^  126 |   componentStyle,
  127 |   isStatic,
  128 |   context,
View compiled
O
src/models/StyledComponent.js:174
  171 | 
  172 |   propsForElement.ref = refToForward;
  173 | 
> 174 |   return createElement(elementToBeCreated, propsForElement);
  175 | }
  176 | 
  177 | export default function createStyledComponent(
View compiled
▶ 18 stack frames were collapsed.
_callee4$
src/pages/pages/Train.tsx:378
  375 | async function toggle() {
  376 |   if (meetingStatus === MeetingStatus.Succeeded) {
  377 |     await toggleVideo();
> 378 |     setIsLoading(false);
      | ^  379 |   }
  380 | }
  381 | toggle();
View compiled
▶ 5 stack frames were collapsed.

**Comment by devalevenkatesh** [comment]
So can you once verify if before doing the Material UI and React library you still run into this issue?

Are you extending and providing your custom theme where some element is missing a "bdg" attribute?

**Comment by devalevenkatesh** [comment]
Closing this due to no-activity. Please feel free to re-open if you still need help. Thanks.

**Comment by kelvin-thinkbean** [comment]
@christiansaavedra , did you ever find a fix for this?

**Comment by christiansaavedra** [comment]
> 

Hi, I've found out that this bug was caused because I deleted the styled-components library (because I've moved to MUI and I tought I didn't need it anymore, but the truth is I still need it because the chime react library uses it).

Hope it helps

**Comment by tamilvendhank-helptap** [comment]
I am facing this issue today. My package.json reads as 

```
...
"amazon-chime-sdk-component-library-react": "^3.2.0",
"amazon-chime-sdk-js": "^3.1.0",
"styled-components": "^5.0.0",
"styled-system": "^5.1.5",
...
```

Node version:
```
% node -v
v18.0.0
```

How can this be solved?

**Comment by pkc189** [comment]
This error mostly occurs if you have missed below code.

```
import { ThemeProvider } from 'styled-components';
import {
  MeetingProvider,
  lightTheme,
  GlobalStyles,
} from 'amazon-chime-sdk-component-library-react';

const Root = () => (
  <ThemeProvider theme={lightTheme}>
    <GlobalStyles />
    <MeetingProvider>
      <MyApp />
    </MeetingProvider>
  </ThemeProvider>
);
```
