### ISSUE TITLE
How to know if the user has left the call because of some error or left the meeting properly?

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#678]
### What are you trying to do?

How to know if the user has left the call because of some error or left the meeting properly?

```
audioVideo.realtimeSubscribeToAttendeeIdPresence((attendeeId, present, externalUserId, dropped) => {
if(dropped) {

}
if(present) {

}
if(!present) {

}
}

```
### What documentation have you looked at so far?

Amazon Chime Component React Library Guide.

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue.

You can use [useMeetingStatus](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemeetingstatus--page) to know the meeting status when it fails or an attendee leaves or if the meeting has ended.

This hook is dependent on `audioVideoDidStop` AudioVideoObserver from the Amazon Chime SDK for JavaScript. The [`MeetingManager`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L362-L413) listens to above observer and vends out the meeting status through the `useMeetingStatus` hook.

Please feel free to re-open or create a new issue if you need more help.
