### ISSUE TITLE
Getting "Your client does not support hardware acceleration"

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#679]
### What happened and what did you expect to happen?

Getting the below error on other users video in Browser - Firefox.

![Screenshot 2021-11-23 at 4 19 42 PM](https://user-images.githubusercontent.com/64121180/143011568-21bc7dbe-fdba-4943-9cc7-7dba4ecec59c.jpg)

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

Just try to call other user. Call gets connected. Voice is audible, but video is showing error.

### Amazon Chime SDK React Components Library version

2.11.1

### What browsers are you seeing the problem on?

Firefox

### Browser version

92.0 (64-bit)

### Device Information

MAC, Desktop

### Browser console logs

2021-11-23T10:57:58.708Z [INFO] sdk - Supported Constraints in this browser {"autoGainControl":true,"browserWindow":true,"channelCount":true,"deviceId":true,"echoCancellation":true,"facingMode":true,"frameRate":true,"groupId":true,"height":true,"mediaSource":true,"noiseSuppression":true,"scrollWithPage":true,"viewportHeight":true,"viewportOffsetX":true,"viewportOffsetY":true,"viewportWidth":true,"width":true}

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. We have an FAQ in the JS SDK repo around this:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-see-a-slate-which-says-quotyour-client-does-not-support-hardware-accelerationquot-when-i-enable-video-on-my-device

As recommended request you to try joining the meeting by enabling simulcast.
```
import { MeetingProvider } from 'amazon-chime-sdk-component-library-react';

const Root = () => {
  const logger = new ConsoleLogger('SDK', LogLevel.INFO);
  const meetingConfig = {
    simulcastEnabled: true,
  };

  return (
    <MeetingProvider {...meetingConfig}>
      <MyApp />
    </MeetingProvider>
  );
};
```

Since, we have an FAQ for this one closing this issue. Please feel free to re-open if you need more help or run into an issue.
