### ISSUE TITLE
How to detect if partners browser is in background?

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#690]
### What are you trying to do?

I am trying to show "video is paused" text based on the browser of the partner.

### What documentation have you looked at so far?

Amazon Chime React Component Library Guide.

**Comment by devalevenkatesh** [comment]
Hello @arpitmittal-lab ,

The chime react component library does not provide such a way to know directly, but you would have to listen to browser's [Page Visibility](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) events to know whether an attendee backgrounded their app. Then, you can use the Amazon Chime SDK for JavaScript data messages feature to notify other attendees. This will require your own implementation as this is a custom case but can done using current SDK offerings I think.

Check "Send and Receive Data Messages" under the component library storybook to learn more on how to use data messages:
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/quick-starts--page

Please let me know if you need more help.

**Comment by devalevenkatesh** [comment]
Closing this issue as no further questions or action is required.
