### ISSUE TITLE
User is not getting reconnected after internet is lost.

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#693]
### What happened and what did you expect to happen?

Getting the below errors at the user who's internet is lost. The other is waiting for the user to join and within 45 seconds the user internet is stable then they should get connected. Is there any limit for reconnection and reconnection timeout? 

**2021-12-08T06:51:30.020Z [WARN] SDK** - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b was canceled due to subtask AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms error: serial group task AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/UpdateSession/SubscribeAndReceiveSubscribeAckTask error: SubscribeAndReceiveSubscribeAckTask got canceled while waiting for SdkSubscribeAckFrame

**2021-12-08T06:52:00.043Z** [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling/OpenSignalingConnectionTask error: OpenSignalingConnectionTask got canceled while waiting to open signaling connection

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

- Join Meeting from User A & User B
- Disconnect internet from User A
- Connect internet of User A (After 25-30 seconds)
- User B trying to reconnect.
- Err: User A & B couldn't connect.

### Amazon Chime SDK React Components Library version

2.12.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

96.0.4664.55 (Official Build) (x86_64)

### Device Information

MAC

### Browser console logs

**2021-12-08T06:51:30.020Z [WARN] SDK** - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b was canceled due to subtask AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms error: serial group task AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/UpdateSession/SubscribeAndReceiveSubscribeAckTask error: SubscribeAndReceiveSubscribeAckTask got canceled while waiting for SdkSubscribeAckFrame

**2021-12-08T06:52:00.043Z** [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling error: serial group task AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling was canceled due to subtask AudioVideoReconnect/f11541d3-ade9-4023-8eff-05e98eb90706/07c1b305-7f39-346e-e39f-7cf562742c0b/Timeout15000ms/Media/Signaling/OpenSignalingConnectionTask error: OpenSignalingConnectionTask got canceled while waiting to open signaling connection

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. Can you please provide us full browser console logs? Those will help us understand if there was reconnection attempted and failed after trying for multiple times.

**Comment by arpitmittal-lab** [comment]
@devalevenkatesh sure will share the browser console logs. You would be needing console logs for both the users?

The maximum amount of time to allow for connecting is 15 seconds. Does this work after internet on-off or just for the initial meeting join. Also, I couldn't find a way to increase the time in Chime react library can you help in that?

**Comment by arpitmittal-lab** [comment]
ConsoleLogger.js:76 2021-12-09T06:55:58.039Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:58.040Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:58.141Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:58.141Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:58.343Z [INFO] sdk - API/DefaultDeviceController/listAudioInputDevices false -> [{"deviceId":"default","kind":"audioinput","label":"Default","groupId":"38a1a6ded44ba15de308f6c35b7d3134dd53b9c0ef535b5e7fd0b25fcc17317b"},{"deviceId":"f3aea3a14e1bc82d1336380a9b15c070afd67106f779225eaafb9aad0c1ac64b","kind":"audioinput","label":"Built-in Audio Analog Stereo","groupId":"04147d24da8a61c7205700e483168101d75076a035663870b7af9f836d82fa5c"}]

ConsoleLogger.js:76 2021-12-09T06:55:58.347Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:58.347Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:58.406Z [INFO] sdk - API/DefaultDeviceController/listVideoInputDevices false -> [{"deviceId":"6c4818d90b5af7995fe31414982320f7be8b00ff0e812733b6d565119cb709c2","kind":"videoinput","label":"HP HD Camera (04ca:7095)","groupId":"5aa7a5c78a692c8f74a78e53365a801e5c3c4ed3b776b95e9822e7271feb55a6"}]

ConsoleLogger.js:76 2021-12-09T06:55:58.408Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:58.409Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:58.420Z [INFO] sdk - requesting new video device with constraint {"video":{"deviceId":{"exact":"6c4818d90b5af7995fe31414982320f7be8b00ff0e812733b6d565119cb709c2"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15}}}

ConsoleLogger.js:76 2021-12-09T06:55:59.062Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.063Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:59.192Z [INFO] sdk - got video device for constraints {"video":{"deviceId":{"exact":"6c4818d90b5af7995fe31414982320f7be8b00ff0e812733b6d565119cb709c2"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15}}}

ConsoleLogger.js:76 2021-12-09T06:55:59.192Z [INFO] sdk - Starting devicechange listener.

ConsoleLogger.js:76 2021-12-09T06:55:59.193Z [INFO] sdk - API/DefaultDeviceController/chooseVideoInputDevice "6c4818d90b5af7995fe31414982320f7be8b00ff0e812733b6d565119cb709c2"

ConsoleLogger.js:76 2021-12-09T06:55:59.194Z [INFO] sdk - API/DefaultDeviceController/startVideoPreviewForVideoInput ""

ConsoleLogger.js:76 2021-12-09T06:55:59.257Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.258Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:59.384Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.385Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:59.520Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.521Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:59.568Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.569Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:55:59.696Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:55:59.696Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:56:58.518Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:56:58.519Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:57:58.542Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:57:58.542Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:58:58.725Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:58:58.726Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T06:59:58.518Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T06:59:58.518Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

ConsoleLogger.js:76 2021-12-09T07:00:58.526Z [INFO] sdk - DefaultDeviceController video dimension 960 x 540

ConsoleLogger.js:76 2021-12-09T07:00:58.527Z [INFO] sdk - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}

**Comment by jing-chen1** [comment]
Hi @arpitmittal-lab,

The 15 seconds is the connection timeout, which means there is a 15 seconds delay before the re-connection establishes except the `SignalingClientEventType` is `WebSocketFailed`, `WebSocketError`, `WebSocketClosing` and `WebSocketClosed` according to [this PR](https://github.com/aws/amazon-chime-sdk-js/pull/1474). The [default value](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L67) of reconnection timeout in mid-meeting is [2 minutes](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L67). And you can use the [ConnectionHealthPolicyConfiguration](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/connectionhealthpolicy/ConnectionHealthPolicyConfiguration.ts) to change the behavior of reconnection, this can help retries happen quicker.
```
import {
  ConnectionHealthPolicyConfiguration,
  ConsoleLogger,
  DefaultDeviceController,
  DefaultMeetingSession,
  LogLevel,
  MeetingSessionConfiguration
} from 'amazon-chime-sdk-js';

const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
const deviceController = new DefaultDeviceController(logger);
const healthPolicyConfiguration = new ConnectionHealthPolicyConfiguration();

//Set up your own healthPolicyConfiguration

const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);

// Override the default health policy configuration.
configuration.connectionHealthPolicyConfiguration = healthPolicyConfiguration;

const meetingSession = new DefaultMeetingSession(
  configuration,
  logger,
  deviceController
);
```

**Comment by arpitmittal-lab** [comment]
@jing-chen1 / @devalevenkatesh  How to do so in AWS Chime React Library?

**Comment by arpitmittal-lab** [comment]
`import { LogLevel } from "amazon-chime-sdk-js";
import {
	MeetingProvider,
	lightTheme,
	UserActivityProvider,
	MeetingManager,
} from "amazon-chime-sdk-component-library-react";

const meetingManager = new MeetingManager({
	logLevel: LogLevel.INFO,
	configuration: {
		connectionHealthPolicyConfiguration: { 
			connectionWaitTimeMs: 20000, 
			connectionUnhealthyThreshold: 20, 
			missedPongsUpperThreshold: 3 
		},
	},
});

const meetingConfig = {
	simulcastEnabled: true,
	meetingManager,
};

ReactDOM.render(
	<ThemeProvider theme={lightTheme}>
		<MeetingProvider {...meetingConfig}>
			<UserActivityProvider>
				<Router>
					<App />
				</Router>
			</UserActivityProvider>
		</MeetingProvider>
	</ThemeProvider>,
	document.getElementById("root")
);
registerServiceWorker();`

Please suggest the changes needed in the above code for a faster retry after internet connection is lost.

**Comment by arpitmittal-lab** [comment]
@jing-chen1 / @devalevenkatesh Kind reminder. Waiting for the update on this.

**Comment by jing-chen1** [comment]
Hi @arpitmittal-lab,

Unfortunately, meeting session configuration currently is not accessible through React component library. There is a PR on it: https://github.com/aws/amazon-chime-sdk-component-library-react/pull/697

**Comment by arpitmittal-lab** [comment]
@jing-chen1 what's best can we do for improving the reconnecting time after internet is lost in react library?

**Comment by vitiaaap29** [comment]
@jing-chen1 How fast PR https://github.com/aws/amazon-chime-sdk-component-library-react/pull/697 will be released?

**Comment by LeviSklaroff** [comment]
This PR has now been merged and has been released in the newest version of the react library. I'm going to go ahead and close this issue, but if you still have issue please feel free to reopen this.
