### ISSUE TITLE
How to extend the re-connection and connection time?

### ISSUE THREAD

**Issue by harshitappinventiv** [aws/amazon-chime-sdk-component-library-react#695]
What's the default reconnection time and how many times does it try to reconnect when the internet goes off? 
Is there any way to tell the other user that my internet connection is back and I am here?

**Comment by jing-chen1** [comment]
Hi @harshitappinventiv,

Thanks for your interest. The default reconnection timeout is [2 minutes](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L67). It will keep trying until it reaches the timeout. 

In our React meeting demo, the icon of Mic will turn red if the user experience bad connection and turn black if the network recovers. Please check our demo here: [React Meeting Demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting)

**Comment by devalevenkatesh** [comment]
Could you please check the JS SDK linked FAQs to know more about the reconnection logic: 
- [When does the Amazon Chime SDK retry the connection? Can I customize this retry behavior?](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior)
- [What is the timeout for connect and reconnect and where can I configure the value?](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-is-the-timeout-for-connect-and-reconnect-and-where-can-i-configure-the-value)

For network related issues JS SDK does not have a specific observer, but there are observers on telling the meeting session state on connectivity or video unavailability and so on, please check below guide on that:
https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html

Closing this issue, feel free to re-open if you need more information.
