### ISSUE TITLE
useDevicePermissionStatus initial value

### ISSUE THREAD

**Issue by svrtelka** [aws/amazon-chime-sdk-component-library-react#734]
### What happened and what did you expect to happen?

useDevicePermissionStatus hook does not reflect initial value correctly. It always sets the initial value to ```DevicePermissionStatus.UNSET``` and value is updated only when observers detect change in device permissions. 

This means that if my let's say Chrome browser remembers my permissions and does not ask me again, useDevicePermissionStatus is going to return ```DevicePermissionStatus.UNSET``` instead of ```DevicePermissionStatus.GRANTED``` until I change permissions manually again. I cannot even force users to confirm manually each time because ```meetingManager.invokeDeviceProvider(DeviceLabels.AudioAndVideo)``` does nothing when called on Chrome with permissions already granted. 

Can the hook be changed to return initial values depending on the outcomes of ```navigator.mediaDevices.getUserMedia```?

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1.  Log in to meeting using Chrome
2. Make sure both audio and video is allowed in the browser
3. `import {  useDevicePermissionStatus } from 'amazon-chime-sdk-component-library-react'`
4. `const permissionStatus = useDevicePermissionStatus();`
5. permissionStatus will always be `DevicePermissionStatus.UNSET` until you change the permissions in the browser

### Amazon Chime SDK React Components Library version

2.14.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.71 

### Device Information

macOS Big Sur 11.6.2

### Browser console logs

[chime-permission-status.log](https://github.com/aws/amazon-chime-sdk-component-library-react/files/8004167/chime-permission-status.log)

**Comment by xuesichao** [comment]
Hi @svrtelka , thanks for reporting this issue. This issue is known to us. The limitation of this hook is documented in the storybook.

> Can the hook be changed to return initial values depending on the outcomes of navigator.mediaDevices.getUserMedia?

In this case, if user has not granted the permission to the browser, this hook will trigger the device permission prompt even before joining meeting/setting up devices. This is not ideal.

We are waiting [`navigator.permissions.query() API`](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) to be supported by browsers, so we can update this hook.
Currently only Chrome and Edge support the query to 'camera'. https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

**Comment by ltrung** [comment]
We will rework this in the next major version. For now if you want to retrieve user permission you can either use `navigator.permissions.query()` as @xuesichao suggested or just manually handle it from using audioVideo.listAudioInputDevices() or audioVideo.listVideoInputDevices().

**Comment by svrtelka** [comment]
@ltrung Thanks for these suggestions, they won't help in our case unfortunately. As @xuesichao mentioned above, `navigator.permissions.query()` isn't supported by all browsers yet and `audioVideo` can't be used here either. We are trying to create a welcome page that would force users to allow audio/video permissions before accessing our application. We can't make this dependent on device lists only, because users may not have camera devices at all for example.

**Comment by ltrung** [comment]
So this is not convenience but you can follow our logic and call `await navigator.mediaDevices.enumerateDevices();` and check whether the device has label. If they don't then it means there is no permission given yet.

**Comment by mmarekbb** [comment]
@ltrung We're trying this out right now and so far it's looking good. We will keep you posted. Thanks!

**Comment by svrtelka** [comment]
@ltrung So when we combined `enumerateDevices` with `DevicePermissionStatus` and we were able to get our use case working. There is still a way to break this logic though. 

When you go to Safari > Preferences > Websites and pick camera on the left, you can explicitly allow it for any website. If you access the chime application with this setting, all `enumerateDevices()` results are going to have a label. Even without giving audio permissions, audio devices have labels as well.

**Comment by xuesichao** [comment]
We have renamed the following interfaces in the V3 version to avoid confusion:

| Before in 2.x                                                         | After in 3.x                                                          |
| --------------------------------------------------------------------- | --------------------------------------------------------------------- |
| <code>DevicePermissionStatus</code>                                   | <code>DeviceLabelTriggerStatus</code>                                 |
| <code>DevicePermissionStatus.UNSET</code>                             | <code>DevicePermissionStatus.UNTRIGGERED</code>                       |
| <code>useDevicePermissionStatus</code>                                | <code>useDeviceLabelTriggerStatus</code>                              |
|                                                                       |                                                                       |
| <code>MeetingManager.devicePermissionStatus</code>                    | <code>MeetingManager.deviceLabelTriggerStatus</code>                  |
|                                                                       |                                                                       |
| <code>MeetingManager.devicePermissionsObserver</code>                 | <code>MeetingManager.deviceLabelTriggerStatusObservers</code>         |
| <code>MeetingManager.subscribeToDevicePermissionStatus()</code>       | <code>MeetingManager.subscribeToDeviceLabelTriggerStatus()</code>     |
| <code>MeetingManager.unsubscribeFromDevicePermissionStatus()</code>   | <code>MeetingManager.unsubscribeFromDeviceLabelTriggerStatus()</code> |
|                                                                       |                                                                       |
| <code>MeetingManager.deviceLabelTriggerChangeObservers</code>         | <code>MeetingManager.deviceLabelTriggerObservers</code>               |
| <code>MeetingManager.subscribeToDeviceLabelTriggerChange()</code>     | <code>MeetingManager.subscribeToDeviceLabelTrigger()</code>           |
| <code>MeetingManager.unsubscribeFromDeviceLabelTriggerChange()</code> | <code>MeetingManager.unsubscribeFromDeviceLabelTrigger()</code>       |

And we have documented the limitation of this hook in the storybook:
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usedevicelabeltriggerstatus--page

>We are waiting [navigator.permissions.query() API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) to be supported by browsers, so we can update this hook.
Currently only Chrome and Edge support the query to 'camera'. https://developer.mozilla.org/en-US/docs/Web/API/Permissions

Once the above API is well supported by major browsers, we can update this hook.

Close the issue for now.
