### ISSUE TITLE
React Native Android Issue

### ISSUE THREAD

**Issue by PaulGobin** [aws/amazon-chime-sdk-component-library-react#754]
### What happened and what did you expect to happen?

We are facing an issue with Android mostly  and very intermittent on iOS, please note that we are using React Native.

(Guys, please keep me honest here)
What’s happening is when an attendee leaves a meeting the attendee’s video tiles remains on the others screen and shows as blank—a blank video. The team traced it down and believe they found the culprit, I attached the details which we believe is causing the issue, and this issue correlates with the events below, whenever it happens.

Notice that we receive the leave attendee and a few log lines later we get an add video. Whenever this sequence occurs, we get the blank video issue. 
However, when the “add video” event does not occur after the leave attendee (only the “leave event” occurs) then everything works great.

Please advise.

![image](https://user-images.githubusercontent.com/9370041/157550375-b92bd963-2076-4f74-a0ea-bd442703791f.png)

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Join a meeting with 3 or more participants 
Join with Android
Leave the meeting on Android
The meeting tile of the user that left stays on the screen as a blank tile.

### Amazon Chime SDK React Components Library version

React Native SDK

### What browsers are you seeing the problem on?

React Native SDK

### Browser version

React Native SDK

### Device Information

Android (not sure if this is also happening with iOS but cannot reproduce on iOS))

### Browser console logs

see attached image above

**Comment by ltrung** [comment]
@PaulGobin Hi This is the react library and not react native sdk. Should you submit the issue on the mobile repo? Do you use [amazon-chime-sdk-android](https://github.com/aws/amazon-chime-sdk-android/blob/master/guides/01_Getting_Started.md) or [amazon-chime-sdk-ios](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/01_Getting_Started.md) ?
