### ISSUE TITLE
DeviceLabels.None failed to disable end user's audio

### ISSUE THREAD

**Issue by jhawkins11** [aws/amazon-chime-sdk-component-library-react#774]
### What happened and what did you expect to happen?

Our application uses Chime as a video broadcasting service and we disable all audio and video when joining the meeting from the consumer facing site. We have a separate application that an employee uses to broadcast video from. We had an instance where a consumer's audio inadvertently turned on when connecting to car's bluetooth in the middle of a broadcast. We've ran hundreds of broadcasts and this is the only occurrence of this issue.

We are disabling audio via the device labels as shown in the quick starts page.
[Quick Starts Page](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/quick-starts--page)

```
const joinData = {
        meetingInfo: data.Meeting,
        attendeeInfo: data.Attendee,
        deviceLabels: DeviceLabels.None
      }
      // Use the join API to create a meeting session using the above data
      await meetingManager.join(joinData)
```

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

We haven't been able to reproduce the issue. The end user stated that it occurred when he connected his phone to his vehicle's bluetooth. We have looked at the meeting events log via the media capture pipeline and have verified that the customer had ActiveSpeaker events attached to their user ID. Please advise if there are any workarounds to prevent this from happening in the future.

### Amazon Chime SDK React Components Library version

2.15.0

### What browsers are you seeing the problem on?

Unknown

### Browser version

Unknown

### Device Information

Mobile

### Meeting and Attendee ID Information.

Meeting ID: 7b858efd-b5c2-4ae9-a9b4-bf7bf83a0706
Attendee ID: a75963c7-4deb-9091-6295-7d4d2a5faa67
Media Capture Pipeline: 85f902b1-c64c-405c-ab12-965aea740fbf

### Browser console logs

Unable to access these as this happened on a customer's mobile device.

**Comment by simmkyu** [comment]
## Chime SDK server logs

The Chime SDK server logs indicate that the attendee `a75963c7-4deb-9091-6295-7d4d2a5faa67` joined a meeting 4 times. At 11:28:40, the attendee was dropped from the meeting and re-joined 7 seconds later.

Time (PST) | Action
--|--
04/02/22 11:24:01| Created with CreateAttendee, BatchCreateAttendees, or CreateMeetingWithAttendees API in your server application
04/02/22 11:24:06| Joined the meeting (1st)
04/02/22 11:24:26| Left the meeting
04/02/22 11:24:26| Joined the meeting (2nd)
04/02/22 11:27:31| Left the meeting
04/02/22 11:27:34| Joined the meeting (3rd)
**04/02/22 11:28:40**| **Dropped from the meeting**
04/02/22 11:28:47| Joined the meeting (4th)
04/02/22 11:30:16| Left the meeting

⠀

## Suggestion

- After joining a meeting with **DeviceLabels.None**, you can mute yourself using the [`useToggleLocalMute` hook](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usetogglelocalmute--page) or call the `meetingSession.audioVideo.realtimeMuteLocalAudio` API ([Use case #7 in the Chime SDK for JavaScript README.md](https://github.com/aws/amazon-chime-sdk-js#audio)). Muting yourself  ensures that the Chime SDK does not send any audio signal even if the user has accidentally chosen the microphone. 
- When this incident happens again, please include Chime SDK INFO-level browser logs. The upcoming version of the Chime SDK for JavaScript and the React Component Library will include the enhanced POST logger. You can use the POST logger to send browser logs to Amazon CloudWatch or your logging backend.

⠀

## Questions

1. An attendee (or your application) should have selected a microphone to enable audio.Does your application have any logic that automatically allows an attendee to leave and re-join the meeting? Is there a chance that an attendee has re-joined the meeting with a microphone?
2. When an attendee is dropped from the meeting, the Chime SDK retries the connection until re-joining the meeting. Do you have any custom logic for the drop event or poor network (e.g., [connectionDidBecomePoor](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#connectiondidbecomepoor) implementation)?

**Comment by xuesichao** [comment]
Close the issue due to inactivity. Feel free to reopen it.
