### ISSUE TITLE
MeetingManager is re-initialising twice / audioVideo is resetting to null when creating a new meeting while previous is ending

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-component-library-react#793]
### What happened and what did you expect to happen?

Chime is unselecting devices on meeting end, but we are unable to await this. Currently, when a meeting ends, we create a new meeting which automatically selects devices, but it unselects all devices as the previous meeting is not finished. The new meeting will then have null audioVideo although a new one was already been created automatically but replaced. This results in a blank video tile to be shown with error `cannot bind video preview since video input device has not been chosen`.

In detail, we have a use-case where we have two views:

1. Setup screen for device selection
2. Meeting screen

but they don't share the same meeting ID details, because at the Setup screen there is no meeting information requested yet.

In the setup screen, the Chime SDK requires dummy meeting information in order to use `audioVideo` so that previewing local video is possible. The meeting screen uses actual meeting details.

A component is set up inside MeetingProvider which contains the following code below.
```
const isDummyMeeting = // meeting information === dummy meeting information
const startMeeting = () => {
  if (!isDummyMeeting) {
    meetingManager.start();
  };
};

const endMeeting = () => {
  if (!isDummyMeeting) {
    meetingManager.leave();
  };
};
```

It joins a meeting and leaves, but does not call `meetingManager.start()` until actual meeting information is supplied. In setup, it also does not call `meetingManager.leave()` as we want to retain existing device information.

```
<MeetingProvider>
  <ChimeWrapper>
    {...}
  </ChimeWrapper>
</MeetingProvider>
```

Upon exiting the actual meeting by calling meetingManager.leave(), meetingManager re-initialises twice. We await the first `leave()` call on button press. Once it returns to the Setup screen, a new dummy meeting is started - device information is reset and a video preview appears briefly with new device settings but `audioVideoDidStop` observer is called and causes everything to be unselected `cannot bind video preview since video input device has not been chosen`.

Is there a recommended way to
1. Retain the device selection state, and
2. Recreate audioVideo, ensuring that it is not overridden by the `audioVideoDidStop` observer?

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Create a meeting provider and a wrapper inside it
```
<MeetingProvider>
  <ChimeWrapper>
    {...}
  </ChimeWrapper>
</MeetingProvider>
```

2. Start a video preview from Setup
```
const isDummyMeeting = // meeting information === dummy meeting information
const startMeeting = () => {
  if (!isDummyMeeting) {
    meetingManager.start();
  };
};

const endMeeting = () => {
  if (!isDummyMeeting) {
    meetingManager.leave();
  };
};

useEffect(() => {
  startMeeting();
  return () => endMeeting();
}, [meetingManager, meetingInfo]);
```

3. Enter the meeting, Leave the meeting.
4. Return to Setup, video preview shows briefly then disappears / does not appear at all.

### Amazon Chime SDK React Components Library version

2.12.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

100.0.4896.127 (Official Build) (x86_64)

### Device Information

macOS Monterey 12.2.1

### Meeting and Attendee ID Information.

Meeting ID: 598ab124-9c54-4728-9193-2421bffa0706
Attendee ID: c6aba013-1b0c-dcc6-a0dc-11053dbe50f6

### Browser console logs

[swm-localhost-20220425-1722.log](https://github.com/aws/amazon-chime-sdk-component-library-react/files/8553255/swm-localhost-20220425-1722.log)

**Comment by xuesichao** [comment]
> In detail, we have a use-case where we have two views:
> 
> * Setup screen for device selection
> * Meeting screen
> 
> but they don't share the same meeting ID details, because at the Setup screen there is no meeting information requested yet.
> 

Hi @Nanosync . Is there any specific reason that you don't want to request meeting information in the Setup screen and have to use a dummy meeting?

Usually our flow is:
```ts
// Create or join a meeting
await meetingManager.join(...);

// At this point you could let users setup their devices
...

// Start the session to actually start or join the meeting
await meetingManager.start();
```

Could you call `await meetingManager.join(...)` before redirecting to setup view?

**Comment by Nanosync** [comment]
Hi @xuesichao ,

Sorry for the confusion, the issue was very verbose. Actually the meeting information is independent of the issue, but briefly, we don't request meeting info because a user could spend a lot of time in the Setup screen.

The main issue I was facing was when calling `await meetingManager.leave()` and immediately creating a new meeting, the cleanup is not isolated to the previous meeting as observer `audioVideoDidStop` also calls `meetingManager.leave()`. So when a new meeting is immediately created with a new audioVideo after leaving the old meeting, the old observer is delayed when running and audioVideo is set to null.

**Comment by Nanosync** [comment]
Hi @devalevenkatesh , thank you for the response.

Waiting for the event works when returning from the Meeting to Setup screen.

However, I have observed that in the Setup screen where the meeting is not connected*, calling `await meetingManager.leave()` before immediately starting a new meeting does not trigger the `MeetingStatus.Left` event. Based on the code in `DefaultAudioVideoController.ts`, there is no event being signalled to call `audioVideoDidStop` or to change the meeting status when calling `audioVideo.stop()`, so there is no way to know when the device streams have been cleaned up successfully.

*`meetingManager.start()` is not called for this screen as it would trigger connection requests to server URLs

**Comment by ltrung** [comment]
@Nanosync Sorry for not replying late but could you clarify your use case a bit more? From the code sample in the original post, it does not seem like you call `meetingManager.leave()` from the Setup screen (as you use dummy meeting)? If you just want to make sure the device stream is cleaned up succesfully then can you just check whether it is a dummy meeting and if so do not wait for `MeetingStatus.Left`?

**Comment by ltrung** [comment]
@Nanosync Just to clarify but is this your current workflow:
```
meetingManager.join(dummyMeeting);
meetingManager.leave();
const meetingResponse = await createMeeting();
meetingManager.join(meetingResponse); //actual meeting
meetingManager.start();
```

Have you tried to put await in front of the API calls? I believe then it should finish cleaning up everything once the call finishes.

**Comment by Nanosync** [comment]
Hi @ltrung ,

The workflow generally uses the following:

```
await meetingManager.join(dummyMeeting);
await meetingManager.leave();

const meetingResponse = await createMeeting();
await meetingManager.join(meetingResponse); //actual meeting
await meetingManager.start();
```

The wrapper ends the meeting in a `useEffect` when current `meetingId` changes.

In the call in `await meetingManager.leave();` where `this.audioVideo.stop()` is called,

DefaultAudioVideoController.ts
```
  stopReturningPromise(): Promise<void> {
    // In order to avoid breaking backward compatibility, when only the
    // signaling connection is established we appear to not be connected.
    // We handle this by simply disconnecting the websocket directly.
    if (this.sessionStateController.state() === SessionStateControllerState.NotConnected) {
      // Unfortunately, this does not return a promise.
      this.meetingSessionContext.signalingClient?.closeConnection();

      // Clean up any open streams.
      return new ReleaseMediaStreamsTask(this.meetingSessionContext).run();
    }
    
    ... otherwise signal MeetingSessionStatusCode.Left
```

Here, this task runs asynchronously and when a meeting has already been created, this task finishes running, causing the unintended behaviour.

**Comment by ltrung** [comment]
So I think this would be solved if you update to v3 version since audioVideo.stop() no longer release the media stream.

**Comment by xuesichao** [comment]
Close the issue due to inactivity. Feel free to reopen it.
