### ISSUE TITLE
How we can detect all the attendees whose audio is muted ?

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-component-library-react#797]
### What are you trying to do?

We are trying to render a mute icon on video tile for all attendees who are muted. Somehow I am not able to determine or find any hook which can provide me  attendees mute status. Is there a way we can achieve that ?

### What documentation have you looked at so far?
So far only positive thing I found is this one,
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useattendeestatus--page

**Comment by michhyun1** [comment]
@Saifak34 yes, you may use that hook to know if the attendee is muted or not - here is an example: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/4775ac64c33c120fd270d59a67d5b1bfda203b44/src/components/sdk/RosterAttendee/index.tsx#L23

**Comment by Saifak34** [comment]
this helped thank you !!

**Comment by michhyun1** [comment]
@Saifak34 No problem - closing this ticket now. Let us know if you need anything else.
