### ISSUE TITLE
Content share tile is displaying for the same user who is sharing screen

### ISSUE THREAD

**Issue by araju57** [aws/amazon-chime-sdk-component-library-react#805]
Hi,
I am using `VideoTileGrid` component for videos display, where it is also displaying content share tile automatically so that same user who is sharing screen is also able to view the content share tile in which screen is mirroring.

![image](https://user-images.githubusercontent.com/79351195/171326605-8111042b-623a-4467-8d0b-7f1dc0b7317a.png)

I need an option to separate content share tile which i don't want to display to same user, I also want to use `VideoTileGrid` component in which i need any option if we have not to include content share tile.

using below code in MeetingView

```
<UserActivityProvider>
      <StyledLayout showNav={showNavbar} showRoster={showRoster}>
        <StyledContent>
          <VideoTileGrid
            className="videos"
            noRemoteVideoView={<MeetingDetails />}
          />
          <MeetingControls />
        </StyledContent>
      </StyledLayout>
    </UserActivityProvider>
```

I tried  using `ContentTile` UI component which is not working.

`import { ContentTile } from 'amazon-chime-sdk-component-library-react';`

Please someone give a solution for above

Thank you...

**Comment by xuesichao** [comment]
Hi @araju57. `ContentTile` is just a UI component, it does not have any functionality. The one you are looking for is [`ContentShare`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-contentshare--page) SDK component.

>I need an option to separate content share tile which i don't want to display to same user, I also want to use VideoTileGrid component in which i need any option if we have not to include content share tile.

Unfortunately, `VideoTileGrid` component does not support this for now. However you can implement your own `VideoTileGrid` component, let's call it `CustomVideoTileGrid`. You can use the `isLocalUserSharing` returned by [`useContentShareState` hook](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usecontentsharestate--page) to implement this logic.

```tsx
// Whether or not the local user is screen sharing
isLocalUserSharing: boolean;
```

Simply copy the [`VideoTileGrid` implementation](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/components/sdk/VideoTileGrid/index.tsx) from our library and paste in your application.

```tsx
...
...
export const CustomVideoTileGrid: React.FC<Props> = ({
  noRemoteVideoView,
  layout = 'featured',
  ...rest
}) => {
  const { tileId: featureTileId } = useFeaturedTileState();
  const { tiles } = useRemoteVideoTileState();
  const { tileId: contentTileId, isLocalUserSharing } = useContentShareState();  // import `isLocalUserSharing`
  const { isVideoEnabled } = useLocalVideo();
  const featured =
    (layout === 'featured' && !!featureTileId) || !!contentTileId;
  const remoteSize = tiles.length + (contentTileId ? 1 : 0);
  const gridSize =
    remoteSize > 1 && isVideoEnabled ? remoteSize + 1 : remoteSize;

  return (
    <VideoGrid {...rest} size={gridSize} layout={featured ? 'featured' : null}>
      {!isLocalUserSharing && <ContentShare css="grid-area: ft;" />}  // Render `<ContentShare />` component only one local user is not sharing
      {layout === 'featured' ? <FeaturedRemoteVideos /> : <RemoteVideos />}
      <LocalVideo
        nameplate="Me"
        css={gridSize > 1 ? fluidStyles : staticStyles}
      />
      {remoteSize === 0 && noRemoteVideoView}
    </VideoGrid>
  );
};

export default CustomVideoTileGrid;
```

>I also want to use VideoTileGrid component in which i need any option if we have not to include content share tile.

You can also add another Props to `CustomVideoTileGrid` to achieve this.

```tsx
interface Props extends BaseProps {
  /** A component to render when there are no remote videos present */
  noRemoteVideoView?: React.ReactNode;
  /** The layout of the grid. */
  layout?: Layout;
  /** Whether or not to render content tile for sharer. */
  isContentHiddenForSharer: boolean; 
}

export const CustomVideoTileGrid: React.FC<Props> = ({
  noRemoteVideoView,
  layout = 'featured',
  isContentHiddenForSharer = false, // set to false by default
  ...rest
}) => {
  const { tileId: featureTileId } = useFeaturedTileState();
  const { tiles } = useRemoteVideoTileState();
  const { tileId: contentTileId, isLocalUserSharing } = useContentShareState();
  const { isVideoEnabled } = useLocalVideo();
  const featured =
    (layout === 'featured' && !!featureTileId) || !!contentTileId;
  const remoteSize = tiles.length + (contentTileId ? 1 : 0);
  const gridSize =
    remoteSize > 1 && isVideoEnabled ? remoteSize + 1 : remoteSize;

  return (
    <VideoGrid {...rest} size={gridSize} layout={featured ? 'featured' : null}>
      {(!isContentHiddenForSharer || !isLocalUserSharing) && (
        <ContentShare css="grid-area: ft;" />
      )}
      {layout === 'featured' ? <FeaturedRemoteVideos /> : <RemoteVideos />}
      <LocalVideo
        nameplate="Me"
        css={gridSize > 1 ? fluidStyles : staticStyles}
      />
      {remoteSize === 0 && noRemoteVideoView}
    </VideoGrid>
  );
};

export default CustomVideoTileGrid;
```

I haven't tested this yet, but it should work. Please let us know if this helps you.

**Comment by xuesichao** [comment]
Close the issue due to inactivity. Feel free to reopen it if you still have issue.

**Comment by araju57** [comment]
Thank you for the support, given example worked for me.
