### ISSUE TITLE
LocalVideo not working on iOS

### ISSUE THREAD

**Issue by its-tuanna** [aws/amazon-chime-sdk-component-library-react#806]
### What happened and what did you expect to happen?

I have a meeting session consisting of 2 people. To join the meeting, camera must be allowed and must be working. My camera is displayed with LocalVideo, the other attendee's camera is displayed with RemoteVideo. I expected that both LocalVideo and RemoteVideo should work with blue custom background. But only RemoteVideo work, LocalVideo show nothing but void black (like picture below). I tested on android and pc and it's work normally, this happen only to iOS
![demo pic](https://user-images.githubusercontent.com/104357991/171325013-826e3d1c-9120-486a-aba3-288a2198df1d.PNG)
324942-d7ea4f57-bff9-45ae-92f1-76243819aa34.png)

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Join a meeting session consisting of 2 people by iOS phone
2. Your iOS camera is display with LocalVideo, the other attendee's camera is displayed with RemoteVideo
In details, i'm using LocalVideo like this: `<LocalVideo nameplate="" />`

### Amazon Chime SDK React Components Library version

2.15.0

### What browsers are you seeing the problem on?

safari

### Browser version

n/a

### Device Information

iPhone X, iOS15.5

### Browser console logs

n/a

**Comment by xuesichao** [comment]
Hey @its-tuanna, thanks for reporting this issue. This is known to us and we have filed this [bug ticket](https://bugs.webkit.org/show_bug.cgi?id=241152) to WebKit. We will try to come out a workaround for this issue in next release.

BTW, do you have a stable way to reproduce this issue on your side? If not could you please let us know the reproduce rate? This would help us a lot, thanks.

**Comment by xuesichao** [comment]
And I notice you are still using 2.15.0 version. We highly recommend you to migrate your project to V3.

**Comment by its-tuanna** [comment]
Sorry @xuesichao, the reproduction steps above is the stable way to reproduce this issue on my side. And the reproduce rate on my side is 100%

**Comment by xuesichao** [comment]
@its-tuanna Could you please try our meeting demo and see if you could reproduce this issue 100%? So far we haven't figured out a stable way to reproduce it, the code in your application may help us debug this issue. Could you also tell us how you implement your application and utilize those components?

**Comment by xuesichao** [comment]
@its-tuanna Could you also try to reproduce this issue using a bigger screen device, e.g., iPad, if possible?

**Comment by its-tuanna** [comment]
> Could you also tell us how you implement your application and utilize those components?

This is how i implement my application:
`import {
  LocalVideo,
  RemoteVideo,
  useLocalVideo,
  useMeetingStatus,
} from 'amazon-chime-sdk-component-library-react';
function StartMeeting() {
  const { isVideoEnabled } = useLocalVideo();
  const meetingStatus = useMeetingStatus();

  React.useEffect(() => {
    // start video 
    if (!isVideoEnabled && meetingStatus === 1) {
      toggleVideo();
    }
  }, [meetingStatus]);

 return (<div>
  <div className="d-flex flex-row">
    <div className="video-container-left">
      <RemoteVideo title={partnerTitle} />
    </div>
    <div className="video-container-right">
      {isVideoEnabled ? <LocalVideo nameplate="" /> :  /*Some placeholder component*/}
    </div>
  </div>
</div>)
}`

**Comment by its-tuanna** [comment]
> And I notice you are still using 2.15.0 version. We highly recommend you to migrate your project to V3.

I have tried to migrate to V3 (```
"amazon-chime-sdk-component-library-react": "^3.2.0",
    "amazon-chime-sdk-js": "^3.3.0",
```) by [this guide](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/amazon-chime-sdk-component-library-react%403.0.0-beta.0/src/components/migrationToV3.stories.mdx) and [this guide](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md), but now it's not working in all devices (PC and mobile). I just change one thing in my code;

Before:
```
import { useMeetingManager} from 'amazon-chime-sdk-component-library-react';
import { MeetingJoinData } from 'amazon-chime-sdk-component-library-react/lib/providers/MeetingProvider/types';

const meetingManager = useMeetingManager();
const joinData: MeetingJoinData = {
      meetingInfo: data.meetingInfo,
      attendeeInfo: data.attendeeInfo,
      meetingManagerConfig: {
        logLevel: LogLevel.ERROR,
      },
};
await meetingManager.join(joinData);
```

After:
```
import { useMeetingManager} from 'amazon-chime-sdk-component-library-react';
import { MeetingSessionConfiguration } from 'amazon-chime-sdk-js';

const meetingManager = useMeetingManager();
const meetingSessionConfiguration = new MeetingSessionConfiguration(data.meetingInfo, data.attendeeInfo);
await meetingManager.join(meetingSessionConfiguration);
```

**Comment by its-tuanna** [comment]
> @its-tuanna Could you also try to reproduce this issue using a bigger screen device, e.g., iPad, if possible?

I tested on every iOS phone that I could found (include iPad mini 6), all of that work in your demo app but not working in my app

**Comment by its-tuanna** [comment]
I tested many times and found out there was some problem when other attendee joins the meeting and start turning on their camera. I wrote another issue [here](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/813)
