### ISSUE TITLE
Do not ask to allow microphone and camera when reloading app

### ISSUE THREAD

**Issue by dodv-its** [aws/amazon-chime-sdk-component-library-react#810]
### What happened and what did you expect to happen?

I tested your demo (https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) on my PC and android phone, I saw that app asked browser to allow camera for first time. But when I reloaded app, I can't open my camera and don't receive request for allowing camera and mic from browser.
I expect to open camera normally after reloading app.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Below is my video I recorded.
https://drive.google.com/file/d/1H_Tud5LDO6kRiVc3vRIP2nb-2T9N95Pb/view?usp=sharing

### Amazon Chime SDK React Components Library version

3.0.0 for JS and 3.2.0 for React

### What browsers are you seeing the problem on?

Browser on Windows, MacOs, Android

### Browser version

Chrome: 102.0.5005.63

### Device Information

MacPro 2018 Pro, Mobile with android 10

### Browser console logs

N/A

**Comment by xuesichao** [comment]
Hi @dodv-its, thanks for reporting this issue. I saw you selected the `join w/o audio and video` when joining the meeting. 

While selecting this option, the demo will skip the device setup flow and DO NOT ask device permission from browser when joining the meeting. After join the meeting, attendee could then request the device permission by clicking that cog button. You could refer to our "Join a Meeting in View-Only Mode" and "Get Device Permissions From the Browser" doc for more information here: https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/quick-starts--page. Basically this option is for those attendees that don't need to use camera or microphone and don't want to grant permission to browser. They are just audience and just need to listen.

For your question, if you de-select `join w/o audio and video` check box, you will get your expected result.

**Comment by dodv-its** [comment]
I get it now, thanks for the comment. I will close the issue.
