### ISSUE TITLE
Camera and microphone do not switch off after disabling permissions or disconnect device

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-component-library-react#815]
### What happened and what did you expect to happen?

In a meeting, if camera or microphone permissions are removed, the camera and microphone buttons do not switch to off state after manually disabling permissions or when the device is disconnected. In Google Meet, the camera and microphone buttons switch to off state and indicate that they have stopped capturing.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Join a meeting using the `amazon-chime-sdk/apps/meeting` demo.
2. While in the meeting, start camera and unmute microphone.
3. Click the lock icon on the browser, then toggle camera and/or microphone permissions to OFF.
4. The camera/microphone remains on (Stop video/Mute buttons still remain) although it is no longer capturing.

### Amazon Chime SDK React Components Library version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

103.0.5060.53

### Device Information

macOS Monterey 12.2.1

### Browser console logs

[0.0.0.0-1656330921632.log](https://github.com/aws/amazon-chime-sdk-component-library-react/files/8991703/0.0.0.0-1656330921632.log)

**Comment by michhyun1** [comment]
@Nanosync thanks for bringing this up. We'll try to add this functionality as soon as we can. Thanks. In the meantime, I found a solution that you might want to try if you need to implement it:  https://www.webrtc-developers.com/how-permissions-apis-help-managing-the-authorizations/#w3c-permissions-api

**Comment by Nanosync** [comment]
Hi @michhyun1 , thanks for the suggestion. I didn't use the permissions API as it's still a work-in-progress, but as a workaround, I am attaching a device change observer for `audioInputStreamEnded`, `videoInputStreamEnded` when the device is disconnected.

**Comment by michhyun1** [comment]
Seems there is a workaround - we'll close this for now. Please create a new issue if this is still an issue for you.
