### ISSUE TITLE
Lobby - Device setup

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-component-library-react#820]
In order not to suffer from the problem of the room ending in 5 minutes, I'm listing the devices using "DefaultDeviceController", inside it there is a ``destroy()`` method. Is it necessary to call this method before calling ``meetingManager.join`` ?

**Comment by xuesichao** [comment]
Hi @Brenerss!

`MeetingManager` will initialize a `DefaultDeviceController` when calling the `join()` method. The `destroy()` method of the `DefaultDeviceController` discards the current video stream and audio stream.

So it is recommended to call `destroy()` in your case to avoid messing up by having two `DefaultDeviceControllers` at the same time.

**Comment by xuesichao** [comment]
Remove the Documentation label because `DefaultDeviceController` is more like a JS SDK concept. React SDK user should not need to know it.

**Comment by Brenerss** [comment]
Thanks
