### ISSUE TITLE
amazon-chime-sdk phone call support.

### ISSUE THREAD

**Issue by AtifTaskin** [aws/amazon-chime-sdk-component-library-react#823]
Can anyone let me know does amazon-chime-sdk-component-library-react provide a phone call feature through web browsers. If there is, kindly share the UI Component name here.

**Comment by xuesichao** [comment]
Hi @AtifTaskin, could you explain the "phone call feature through web browsers" in more detail so we can understand your use cases and better help you?

`amazon-chime-sdk-component-library-react` doesn't have a ready-to-use component for this kind of feature, but `Amazon Chime SDK` does support it. Check below link as a reference:
* Our meeting demo is built on top of `amazon-chime-sdk-component-library-react`. It has "dial-in" feature to allow users to join the meeting using the phone. Check this [SIPMeeting component](https://github.com/aws-samples/amazon-chime-sdk/blob/2b77a2f0340b9674b567895da3ef019c12961b00/apps/meeting/src/components/SIPMeetingForm/index.tsx#L27) and follow the code path, you can learn more details.
* Our official documentation - [Using the Amazon Chime SDK PSTN Audio service](https://docs.aws.amazon.com/chime-sdk/latest/dg/build-lambdas-for-sip-sdk.html)

**Comment by AtifTaskin** [comment]
We have a telehealth web application based on ReactJS the feature is through our web app any doctor can directly call on the patient phone number. We already use amazon-chime-sdk-component-library-react for our video calling feature.

**Comment by xuesichao** [comment]
@AtifTaskin thanks for your info. `amazon-chime-sdk-component-library-react` is more like a frontend library and unfortunately it doesn't have an out-of-box feature for your use case at the moment. But `Amazon Chime SDK  PSTN Audio service` does support it. It's part of the Amazon Chime Service.

You can check:
- [Using the Amazon Chime SDK PSTN Audio service](https://docs.aws.amazon.com/chime-sdk/latest/dg/build-lambdas-for-sip-sdk.html)
- [SipMediaApplication demo](https://github.com/aws-samples/chime-sipmediaapplication-samples)
- [click to call demo](https://github.com/aws-samples/amazon-chime-sdk-click-to-call)
- [Embed Healthcare Appointment Scheduling Widget with the Amazon Chime SDK](https://aws.amazon.com/blogs/business-productivity/embed-healthcare-appointment-scheduling-widget-with-the-amazon-chime-sdk/)
   - Corresponding [telehealth demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/telehealth-widget)

Above resources should provide you enough knowledge to implement such `phone call` feature, along with Amazon Chime SDK Meeting.

**Comment by AtifTaskin** [comment]
Thanks the given links are much helpful.
