### ISSUE TITLE
Mute/Unmute Issue in iOS

### ISSUE THREAD

**Issue by DSp4wN** [aws/amazon-chime-sdk-component-library-react#826]
### What happened and what did you expect to happen?

1) If I keep the microphone by default active, I can hear the iOS user speaking but as soon as he toggles between mute and unmute once his voice activity is frozen no matter how many time he toggles it again.
2) If I keep the microphone muted by default, iOS user won't be able to speak even after unmuting for the first time.
3) If we keep microphone active by default and won't mute it ever it will keep on working but as soon as we interact with mute/unmute button the microphone stops receiving the audio in iOS. (probably something is going around toggleMute /audioVideo realtime mute/unmute)

(Tried Safari as well as Chrome browser on iPhone 13 Pro, iPhone 7 as well as iPad Pro)

Any kind of help will be appreciated.

Current usage: 

I have tried using the useToggleLocalMute hook as well as audioVideo.realtimeMuteLocalAudio and audioVideo.realtimeUnmuteLocalAudio separately too using useAudioVideo hook but the result is the same. 

meetingOptions = = {
            enableWebAudio: true,
            eventController,
};

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

###React Version
17.0.0

### Reproduction steps

Simply using the mentioned hooks on click to toggle with the mute/unmute in a meeting

### Amazon Chime SDK React Components Library version

3.2.0

### What browsers are you seeing the problem on?

Safari, Chrome in iOS

### Browser version

Latest updated

### Device Information

iOS

### Meeting and Attendee ID Information.

meetingId - 93d667bb-97ea-4aa1-8486-5d681bc80706
another meetingId - 82c286f0-880b-416f-bc16-da14015a0706

### Browser console logs

Not available

**Comment by devalevenkatesh** [comment]
I checked the `MeetingId: 82c286f0-880b-416f-bc16-da14015a0706` and the single attendee found in the meeting on the meeting events and find that there is no mute / un-mute event.

| Time                 	| Attendee Id 	| Event                               	|
|----------------------	|-------------	|-------------------------------------	|
| 8/1/2022, 2:24:37 AM 	|             	| Meeting created                     	|
| 8/1/2022, 2:24:38 AM 	| Attendee A  	| Attendee added                      	|
| 8/1/2022, 2:24:38 AM 	| Attendee A  	| Attendee attempted join             	|
| 8/1/2022, 2:24:38 AM 	| Attendee A  	| Meeting connection started          	|
| 8/1/2022, 2:24:39 AM 	| Attendee A  	| Attendee join successful in meeting 	|
| 8/1/2022, 2:26:05 AM 	| Attendee A  	| Meeting session ended               	|
| 8/1/2022, 2:26:05 AM 	| Attendee A  	| Attendee left                       	|
| 8/1/2022, 2:31:37 AM 	|             	| Meeting auto-ended                  	|

Same is observed for `MeetingId: 93d667bb-97ea-4aa1-8486-5d681bc80706`. Could you please once check the [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) using component library and refer the implementation there?

We directly use the [`AudioInputControl`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/components/sdk/MeetingControls/AudioInputControl.tsx#L36) component from `amazon-chime-sdk-component-library-react` which handles the mute/un-mute. Suggest checking its implementation if you are not directly using it.

If you do not want Amazon voice focus, suggest disabling `enableWebAudio` in meeting join options. When `enableWebAudio` is `true`, we use [`AudioInputVFControl`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-meetingcontrols-audioinputvfcontrol--page) over `AudioInputControl` component.

Please let us know if you still have the issue.
