### ISSUE TITLE
Slow network Indication

### ISSUE THREAD

**Issue by UsmanShafaqat007** [aws/amazon-chime-sdk-component-library-react#833]

**Comment by xuesichao** [comment]
Hi @UsmanShafaqat007 , SDK doesn't have an out-of-box network indicator at the moment. 

SDK exposes the metrics from WebRTC stats via [`useMediaStreamMetrics`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemediastreammetrics--page) hook.
You can implement your own network indicator based on below two metrics exposed by useMediaStreamMetrics hook.

```ts
availableOutgoingBandwidth: number | null;
availableIncomingBandwidth: number | null;
```

Alternately, you can subscribe to the `connectionDidBecomeGood`, `connectionDidBecomePoor`, `connectionDidSuggestStopVideo`, `connectionHealthDidChange` events of [`AudioVideoObserver`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#audiovideodidstart) to notify your user about the connection status change.

To access `audioVideoObserver` in React Component Library, you can do it like this:
```tsx
import { AudioVideoObserver } from 'amazon-chime-sdk-js';

const audioVideo = useAudioVideo();

useEffect(() => {
  if (!audioVideo) {
    return;
  }

  const observer: AudioVideoObserver = {
    connectionDidBecomePoor(): void {
      console.log('connection is poor');
    },
    connectionDidSuggestStopVideo(): void {
      console.log('suggest turning the video off');
    },
    connectionDidBecomeGood(): void {
      console.log('connection is good now');
    }
  };

  audioVideo.addObserver(observer);

  return () => audioVideo.removeObserver(observer);
}, [audioVideo]);
```

**Comment by xuesichao** [comment]
You might find this [Quality, Bandwidth, and Connectivity Guide](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html) from Amazon Chime SDK for JavaScript helpful.

I will leave this issue open as a feature request. Thank you.

**Comment by Sotatek-HoangPham2** [comment]
@xuesichao What is the unit of availableOutgoingBandwidth, kbps or bps. 🤔

**Comment by xuesichao** [comment]
HI @Sotatek-HoangPham2 , it's kbps.
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/520c2d53c3b986f50701eb60f4272ad7fb158741/src/hooks/sdk/useMediaStreamMetrics.tsx#L71
