### ISSUE TITLE
Unable to select Bluetooth input audio on android chrome browser

### ISSUE THREAD

**Issue by danishhyt** [aws/amazon-chime-sdk-component-library-react#839]
### What happened and what did you expect to happen?

When a Bluetooth earphone is connected it should be selected as the default audio input device but instead, the phone microphone is selected.

Even after selecting Bluetooth from the audio source dropdown it is still not switching the audio input to the Bluetooth microphone.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Connect Bluetooth earphones and start a meeting and try to talk via a Bluetooth microphone phone but instead, microphone is used also try to switch the audio source from settings but it does not make any difference.
I am able to play audio in Bluetooth earphones by playing audio on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

### Amazon Chime SDK React Components Library version

3.3.0 (Latest version)

### What browsers are you seeing the problem on?

Android Chrome 

### Browser version

105.0.5195.136

### Device Information

S10 5G running on Android 10

### Browser console logs

Since it is on an android device there are no logs Android

**Comment by danishhyt** [comment]
@xuesichao @devalevenkatesh  Can I have your attention, please?

**Comment by danishhyt** [comment]
Found a workaround for this issue. Incase someone is also having the same issue.

` const audioVideo = useAudioVideo()
  const { selectedDevice } = useAudioInputs()
  React.useEffect(() => {
    if (audioVideo && selectedDevice) {
      audioVideo.startAudioInput(String(selectedDevice))
    }
  }, [audioVideo, selectedDevice])`

**Comment by danishhyt** [comment]
Setting `isWebAudioEnabled` to `false` fixed my issue.

**Comment by michhyun1** [comment]
@danishhyt sorry for missing this issue - we'll close this issue now.
