### ISSUE TITLE
[FEATURE REQUEST] Add Node.js LTS (18.12.0) support

### ISSUE THREAD

**Issue by hoolek77** [aws/amazon-chime-sdk-component-library-react#847]
## Community Note

* Please do not add additional comments such as "+1" or "me too" to existing issues - instead please vote on the issue by adding a 👍 to the issue. The Amazon Chime SDK team will prioritize the request based on the number of 👍 the issue has received.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues) to see if your request has already been recommended.
* Please do not use this template to report bugs. This repository has an [issue template](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/new/choose) for issues and [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/quick-starts--page) to help with your development.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

## Tell us about your request

The package is missing support for the current Node.js LTS version, which recently changed to 18.12.0.

### What do you want us to build?

Add support for Node engine ^18.

### How are you currently solving a problem?

Using previous LTS engine.

**Comment by manojkalpana24** [comment]
Kindly add support for Node.js LTS 18.12.0. Not able to build react application right now, the following message is thrown while executing yarn install,
error amazon-chime-sdk-component-library-react@3.2.0: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^15 || ^16". Got "18.12.0"
error Found incompatible module.

**Comment by xuesichao** [comment]
PR for adding Node.js 18 support has been merged: #848 
Please let us know if you have any feedback. Thanks!

**Comment by manojkalpana24** [comment]
> PR for adding Node.js 18 support has been merged: #848 Please let us know if you have any feedback. Thanks!

When this would be released ?
