### ISSUE TITLE
Does Chime sdk support background blur on VDI environments ?

### ISSUE THREAD

**Issue by neeltrivedi** [aws/amazon-chime-sdk-component-library-react#854]
### What are you trying to do?

I am trying to enable blur for video backgrounds. It works fine on normal environment using laptop but does not work on VDI

### How can the documentation be improved to help your use case?

Not supported environments for background blur

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usebackgroundblur--page

**Comment by ltrung** [comment]
@neeltrivedi As long as the meeting app is running on a browser with access to webcam and internet then it should work. Is there any specific error you saw?

**Comment by devalevenkatesh** [comment]
Resolving this issue due to in-activity. Please let us know if any specific errors you are running into and re-open this issue for the same.
