### ISSUE TITLE
How to control the number of videos received

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-component-library-react#856]
## What we want to do

Where the default is to receive video for 25 people, we would like to set the number of people to a smaller number, such as 5.

The background is that it is difficult to test the behavior of more than 25 Attendees when video is enabled, and we want to operate with the number set to a smaller number.

## What we tried

We tried to change the value of videoSubscriptionLimit but did not get the expected result.

The first thing we tried was to clone amazon-chime-sdk-js and try to build it. However, I got an error when I ran `npm run build`.

The second thing I tried was to directly edit the value of videoSubscriptionLimit in amazon-chime-sdk-js installed by npm and run it, but I did not see any change in behavior.

## Questions and help needed

We would like to know how to control the video size we receive

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Originally set to a limit of 25 people and never could be changed.

### Amazon Chime SDK React Components Library version

3.2.0

### What browsers are you seeing the problem on?

chrome, all browser

### Browser version

108.0.5359.98

### Device Information

MacOS(OS X)

### Browser console logs

none

**Comment by akshay-prabhu-github** [comment]
There are couple of ways to achieve that. 
1. You can use the `Priority-Based Downlink Policy` and use the `chooseRemoteVideoSources` api to control the video tiles that you would want to subscribe to. (Reference Documentation: [User Guide for Priority-based Downlink Policy](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html#user-guide-for-priority-based-downlink-policy))
2. Secondly, you can use the `AllHighestVideoBandwidthPolicy` and use the `chooseRemoteVideoSources` api to control the video tiles that you want to subscribe to. (Reference Documentation: [AllHighestVideoBandwidthPolicy](https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html#allhighestvideobandwidthpolicy-default))

**Comment by xuesichao** [comment]
@kodai305 There're two thresholds on this:


* Video streams published per meeting, threshold is 25 and can be increased up to 100
* Video streams subscribed per attendee, threshold is 25 and can not be changed.


Check here for details:
https://docs.aws.amazon.com/chime-sdk/latest/dg/meetings-sdk.html#mtg-limits

---

And for the behavior when reaching the 25 video limit. check our [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-happens-to-the-subsequent-participants-who-try-to-turn-on-the-local-video-when-the-maximum-number-of-video-senders-is-already-reached):
>[What happens to the subsequent participants who try to turn on the local video when the maximum number of video senders is already reached?](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-happens-to-the-subsequent-participants-who-try-to-turn-on-the-local-video-when-the-maximum-number-of-video-senders-is-already-reached)
Once the limit of video senders is reached in a meeting, each subsequent participant that tries to turn on the local video will receive a Meeting Session status code of [VideoCallSwitchToViewOnly = 10](https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html#videocallswitchtoviewonly) which in turn triggers the observer '[videoSendDidBecomeUnavailable](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videosenddidbecomeunavailable)'.

**Comment by kodai305** [comment]
>which in turn triggers the observer '[videoSendDidBecomeUnavailable](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videosenddidbecomeunavailable)'.

Is the event named `videoSendDidBecomeUnavailable`  available for the sender to receive? Can the recipient (who is not trying to turn on the video) receive it?

**Comment by xuesichao** [comment]
@kodai305 It is only available to attendees who try to open the video when the limit is reached.

Check use case 26 [here](https://github.com/aws/amazon-chime-sdk-js#monitoring-and-alerts).

**Comment by kodai305** [comment]
>All attendees are subscribed to this event. But it is only triggered for attendees who try to open the video when the limit is reached.

All attendees are subscribed to this event. But it is only triggered for attendees who try to open the video when the limit is reached.

**Comment by kodai305** [comment]
>All attendees are subscribed to this event. But it is only triggered for attendees who try to open the video when the limit is reached.

Thank you. If we can get the event, we will be able to achieve a lot of functions.

For example, I would like to realize a spotlight function. I would like to create a mechanism to dynamically turn on the camera if the target of the spotlight is the 26th person to turn on the camera.

So, I have one problem and would like to ask a question.
When implementing the process to receive the event that the 26th person failed to turn on the camera, it is inefficient to have 25 people (browsers) actually participate in the meeting. This is because it cannot be implemented by one person.
Is there any way to solve this problem?

Translated with www.DeepL.com/Translator (free version)

**Comment by devalevenkatesh** [comment]
Hi @kodai305 , unfortunately I do not have a better suggestion yet and have requested information within team internally. Amazon Chime SDK though has a blog post on a tool which can automate participant join:
https://aws.amazon.com/blogs/business-productivity/load-testing-applications-built-with-the-amazon-chime-sdk/

Suggest you to go through it and see whether it helps. Once I have more information, I will update the issue.

**Comment by kodai305** [comment]
@devalevenkatesh 
Thank you for introducing me to your blog. We will try this ourselves.

If there is another way, please let me know!

**Comment by ltrung** [comment]
Closing the issue but feel free to reopen if you still need help
