### ISSUE TITLE
How to realize the spotlight function (how to preferentially turn on video for a specific Attendee while the Video reception limit has been reached)

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-component-library-react#857]
### What are you trying to do?

What we want to do:
 - We want to allow certain Attendees with high priority to turn the camera ON, with the maximum number of incoming video people being reached
 - More abstractly, I would like to realize a spotlight function like the one in ZOOM.

What we tried:
We went through the demo app source code (providers/VideoTileGridProvider/Utils.ts) and tried adjusting the VideoPreference that is set in the updateDownLinkPreference.
However, adjusting the priority of the first argument of VideoPreference and the size of the second argument did not change the behavior.

※ We didn't know exactly what I could set in VideoPreference in the first place from reading the documentation, so please let me know.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Can't find the means to make it happen.

### Amazon Chime SDK React Components Library version

3.2.0

### What browsers are you seeing the problem on?

chrome, all browser

### Browser version

103.0.5060.114

### Device Information

MacOS(OS X)

### Browser console logs

none

**Comment by xuesichao** [comment]
Hi @kodai305 , our SDK provides [PriorityBasedDownlinkPolicy](https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html#videoprioritybasedpolicy) which allows you to choose and configure which remote video sources to subscribe to, their relative priorities and preferences. I think it's a good fit for your use case.

Check these guides:
* https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html#user-guide-for-priority-based-downlink-policy
* https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html#case-3-featured-layout
* https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html#case-2-gallery-layout-up-to-25-videos-with-fixed-tile-size

**Comment by devalevenkatesh** [comment]
I am resolving this issue as per Sichao's last response where in he had linked relevant documentation we have from our side. Please feel free to re-open if you still have issue/ or any questions.

Thanks.
