### ISSUE TITLE
How Can we find logs related with meetings 

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-component-library-react#858]
### What happened and what did you expect to happen?

We want to check all logs related with meetings, including bandwidth scenarios and failures. Where we can find that information ?

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

We want to check all logs related with meetings, including bandwidth scenarios and failures. Where we can find that information ?

### Amazon Chime SDK React Components Library version

2.15.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

108.0.5359.71 

### Device Information

Macbook Pro M1 chip

### Browser console logs

this is what we are looking for but in detail

**Comment by schuettc** [comment]
These are a few blogs that might help if you haven't seen them yet:


https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/

https://aws.amazon.com/blogs/business-productivity/server-side-logging-and-monitoring-of-amazon-chime-sdk-events/

**Comment by Saifak34** [comment]
@schuettc Thank you for quick answer, what about this hook "**useMediaStreamMetrics**" ? This will give us at least bandwidth information right ?

https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-usemediastreammetrics--page

We are facing few issues where calls getting disconnected on slower networks and have no idea how to address that

**Comment by schuettc** [comment]
Yes, it looks like that one would give that information in your client.  But looks like that one is updated very frequently.  

https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html

Another option is to remove video when bandwidth drops too low.

**Comment by xuesichao** [comment]
Hi @Saifak34, `useMediaStreamMetrics` returns the stats from `RTCPeerConnection.getStats()` API call. These stats is updated in each second.

You could use `availableOutgoingBandwidth` and `availableIncomingBandwidth` to get the total bandwidth information. 

There're also video specific bandwidth metrics in `videoStreamMetrics`.
```
videoStreamMetrics: {
  remoteAttendeeId: {
    // remote attendees will have downstream metrics
    ssrc: {
      videoDownstreamBitrate: number; // <==============
      videoDownstreamPacketLossPercent: number;
      videoDownstreamPacketsReceived: number;
      videoDownstreamFramesDecodedPerSecond: number;
      videoDownstreamFrameHeight: number;
      videoDownstreamFrameWidth: number;
      videoDownstreamJitterMs: number;
      videoDownstreamDelayMs: number;
    }
  }
  localAttendeeId: {
    // local attendee will have upstream metrics
    ssrc: {
      videoUpstreamBitrate: number; // <==============
      videoUpstreamPacketsSent: number;
      videoUpstreamPacketLossPercent: number;
      videoUpstreamFramesEncodedPerSecond: number;
      videoUpstreamFrameHeight: number;
      videoUpstreamFrameWidth: number;
      videoUpstreamJitterMs: number;
      videoUpstreamRoundTripTimeMs: number;
    }
  }
}

```

**Comment by Saifak34** [comment]
@xuesichao We have a case where if internet connection is slow the call drops , even if video is off for attendees , is this something already known or we need to change code to address that scenario ?

**Comment by xuesichao** [comment]
@Saifak34 Our SDK uses the presence of audio input stream to determine whether an attendee is present in the meeting. If attendee is under a really bad network condition can not even send audio input stream to our server for a while, this attendee will be considered to drop the meeting. This is the design of our SDK it's known.

**Comment by devalevenkatesh** [comment]
Hi @Saifak34 , I am resolving this issue as no further updates are received, please feel free to re-open if you still have open questions around this.
