### ISSUE TITLE
Is there any way we can  pin administrator video tile for all attendees

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-component-library-react#860]
### What are you trying to do?
We are trying to add an option when admin of the call clicks that their video tile should stay largest( featuredIndex) for all patients, but so far we have realized it only changes video tile state for admin side of meeting and other attendees continue to have old video tile state . Is there any documentation which can help us ?

*For example: I'm trying to run the demo app.*
React app
### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure a component.*

### What documentation have you looked at so far?
i have looked all the storybook docs
*For example: README.md, Amazon Chime Component Library Guide, etc.

**Comment by xuesichao** [comment]
Hi @Saifak34 , I think you can use `Amazon Chime SDK Data Messages to do this`, check our guide:
* https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional (JS SDK)
* https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/quick-starts--page, check `Send and Receive Data Messages` section all the way to the end

Basically you can setup a `topic` just for this feature and let all attendees subscribe to this `topic`. When admin pins a video tile, send out a notification to all subscriber with `video tile id` or `attendee id` in the payload. So when subscribers receive the notification, they can pin the same video tile on their side too.

**Comment by Saifak34** [comment]
will subscribers have to pin the video tile ? Is there any option to change all state if only admin pins the video tile ? we have a lot of attendees and can not ask practically everyone to pin it . Considering they are not technically sound and mostly 80 plus year old patients are attendees

**Comment by xuesichao** [comment]
@Saifak34 No subscribers don't need to. Assume you have a method called `pinVideoTile(tileId)`. When admin pins a video tile, admin actually calls this `pinVideoTile(tileId)` method and send out a data message. And when subscribers received this "message"(It's not really a text notification, just a notifier), your application should automatically call `pinVideoTile(tileId)` for the subscribers, of course you can also display a toast notification for attendee to let them know that admin pins a video tile.

Something like this:
```jsx
const Admin = () => {
  const audioVideo = useAudioVideo();

  const sendPinVideoTileMessage = (tileId) => {
    if (!audioVideo) {
      return;
    }
    const DATA_MESSAGE_LIFETIME_MS = 30000;

    const payload = {
      tileId: tileId,
    };

    audioVideo.realtimeSendDataMessage('PinVideoTile', payload, DATA_MESSAGE_LIFETIME_MS);
  };

  return (
    <Button
      label='Pin a video tile'
      onClick={(tileId) => {
        pinVideoTile(tileId);
        sendPinVideoTileMessage(tileId);
      }}
    />
  );
};

const Subscribers = () => {
  const audioVideo = useAudioVideo();

  useEffect(() => {
    if (!audioVideo) {
      return;
    }
    // Subscribes to `PinVideoTile` topic
    audioVideo.realtimeSubscribeToReceiveDataMessage('PinVideoTile', (data) => {
      const receivedData = (data && data.json()) || {};
      const { tileId } = receivedData;

      // When receiving data message, call `pinVideoTile` with `tileId` from payload
      pinVideoTile(tileId);
      showAlert('Your admin pins a video tile');
    });

    return () => {
      audioVideo.realtimeUnsubscribeFromReceiveDataMessage('PinVideoTile');
    };
  }, [audioVideo]);

  return;
};
```

**Comment by Saifak34** [comment]
Hello @xuesichao Thanks for detailed solution , only problem I am facing is I dont think here pinVideoTile() is getting triggered, but I can see the alert stating video tile pinned with tileid itself (see picture)

`
const [attendeeTileId, setAttendeeTileId] = useState(null); 


const pinVideoTile = (tileId) => {
		console.log('pinned function triggered')
		setAttendeeTileId(tileId)
	}


useEffect(() => {
		if (!audioVideo) {
		  return;
		}
		// Subscribes to `PinVideoTile` topic

		audioVideo.realtimeSubscribeToReceiveDataMessage('PinVideoTile', (data) => {
		  const receivedData = (data && data.json()) || {};
		  const { tileId } = receivedData;
		  console.log('tileid',tileId)
		  // When receiving data message, call `pinVideoTile` with `tileId` from payload
		  pinVideoTile(tileId);
		  alert(` video tile pinned is ${tileId}`  );
		});

		
	
		return () => {
		  audioVideo.realtimeUnsubscribeFromReceiveDataMessage('PinVideoTile');
		};
	  }, [audioVideo]);
`



<img width="632" alt="Screen Shot 2022-12-20 at 4 39 36 PM" src="https://user-images.githubusercontent.com/78328030/208772166-128280cf-c0e4-48a6-888b-3413f0364291.png">

**Comment by xuesichao** [comment]
I think it should be executed. Have you tried adding a breakpoint to see if your `pinVideoTile()` is being executed, you can give it a try if you haven't.

**Comment by Saifak34** [comment]
It is working in web thanks , before you close this ticket do you know if this method `realtimeSendDataMessage() ` is same for iOS and android or is it called something else ?

**Comment by xuesichao** [comment]
@Saifak34, we have SDK for iOS and Android which also support Data Message, no native code required:
* [Amazon Chime SDK for iOS - Data Message](https://github.com/aws/amazon-chime-sdk-ios#data-message)
* [Amazon Chime SDK for Android - Data Message](https://github.com/aws/amazon-chime-sdk-android#data-message)

**Comment by Saifak34** [comment]
Hello , Sorry I am pretty new to this  and bugging  you again but  can I do something like this ? 

`const makeAdminPresenter = () => {
		
		  NativeFunction.sendDataMessage('topic',data,1000)
		
    
    }`


and then trigger  `makeAdminPresenter` when admin pins a video tile ?

**Comment by xuesichao** [comment]
@Saifak34 We are not familiar with mobile development since `Amazon Chime SDK React Component Library` repo are for Web/browser development. 

However the API signature is similar for Chime react/iOS/Android SDK. Basically you just need to call below API to send a data message:
```
meetingSession.audioVideo.realtimeSendDataMessage(topic, data, lifetimeMs)
```
Check below guides for mobile SDK:
* [Amazon Chime SDK for iOS - Data Message](https://github.com/aws/amazon-chime-sdk-ios#use-case-23-send-data-message)
* [Amazon Chime SDK for Android - Data Message](https://github.com/aws/amazon-chime-sdk-android#use-case-23-send-data-message)

If you are using Amazon Chime SDK for Android or Amazon Chime SDK for iOS, you could open an issue in the corresponding repos, and our mobile experts will answer your questions.

**Comment by Saifak34** [comment]
Thanks for your help really appreciate this !!
