### ISSUE TITLE
[FEATURE REQUEST] Allow passing nameplate prop to ContentShare with Typescript

### ISSUE THREAD

**Issue by Amethystix** [aws/amazon-chime-sdk-component-library-react#879]
## Tell us about your request
If you add the `nameplate` prop to content share, it appropriately adds the label. I'd like to label the screenshare tile with the user whose screen it belongs to. However, `ContentShare` does not have this in props, despite just being a styled `VideoTile`

No further detail than this. I'd be happy to supply this PR by end of day today.

**Comment by Amethystix** [comment]
@xuesichao Great! I submitted it earlier today over at #880 ; let me know if there's anything else I need to add!

**Comment by xuesichao** [comment]
#880 has been merged. Thanks for your contribution! Closing this feature request now.
