### ISSUE TITLE
Background Blur huge frame rate drop when tab is out of focus

### ISSUE THREAD

**Issue by mycroft-cesar** [aws/amazon-chime-sdk-component-library-react#883]
### What happened and what did you expect to happen?

I am implementing the background blur feature and I noticed the attendee video is only fluid (the remote tile) if the attendee is currently on the meeting tab. If the attendee changes the tab, or minimizes the browser the video frame rate drops for a value <= 5.

I did follow the example application from the docs.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

- Enter on a meeting with two attendees
- enable the background blur for one of them 
- change the browser tab or minimizes the browser for the attendee with the background blur enabled
- compare both states while watching with the second attendee (the one without the background blur)

### Amazon Chime SDK React Components Library version

3.5.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

111.0.5563.110

### Device Information

macOS Ventura 13.0

### Browser console logs

with the meeting on focus:
![image](https://user-images.githubusercontent.com/121102630/230610037-801bc86a-dd1d-4873-baca-c1b4bc802e1d.png)

out of focus:
![image](https://user-images.githubusercontent.com/121102630/230610085-df49f74e-a37b-4f8c-bf2a-29652affdb48.png)

### Add any other context about the problem here.

these are the options used on the provider:
`{ blurStrength: 5, filterCPUUtilization: 30, reportingPeriodMillis: 1000 }`

**Comment by ryanajae** [comment]
Thank you for raising this issue! It is a known issue that Chrome and other browsers throttle background tabs to optimize performance. There may be browser flags that you can try to disable background tab throttling in the client, but we’re currently unaware of any options to systematically resolve this issue from the developer side.

**Comment by mycroft-cesar** [comment]
I didn't found a single thing about such flags, do you have some links about this matter?

**Comment by michhyun1** [comment]
https://winaero.com/disable-tab-throttling-google-chrome/

Perhaps you can try this.

I'll close this issue for now, please create a new issue if this persists.
