### ISSUE TITLE
Incorrect error being thrown when starting video input device from MeetingManager

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-component-library-react#888]
### What happened and what did you expect to happen?

I am using `meetingManager.startVideoInputDevice()` and `meetingManager.stopVideoInputDevice` to start/stop the video input device, and if an error is thrown, the error name is used to display an appropriate error message.

**Current Result:**

These 2 functions are wrapping the original Error coming from `handleGetUserMedia` (in device controller from the JS sdk) and throwing a generic Error.

**Expected Result:**

The original Error should be thrown for these 2 functions, and possibly all the other functions (`startAudioInputDevice`, `stopAudioInputDevice`, `startAudioOutputDevice`, `stopAudioOutputDevice`).

I also note that in `setupDeviceLabelTrigger`, the error is being wrapped (`throw new Error(error)`), it should `throw error` directly.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Block browser permissions or if on Windows, ensure that browser permissions are granted and the video device is being used in another application.
2. Call `await meetingManager.startVideoInputDevice()`.
3. When `PermissionDeniedError` / `NotReadableError` is thrown, the Error name is "Error" with reason "MeetingManager failed to select video input device"

### Amazon Chime SDK React Components Library version

3.5.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 112.0.5615.49 (Official Build) (arm64)

### Device Information

macOS Monterey 12.6.1

### Browser console logs

```
MeetingManager failed to select video input device PermissionDeniedError: Permission denied by browser
    at DefaultDeviceController.handleGetUserMediaError (DefaultDeviceController.js:885:1)
    at DefaultDeviceController.eval (DefaultDeviceController.js:1010:1)
    at Generator.throw (<anonymous>)
    at rejected (DefaultDeviceController.js:8:42)

An error was thrown (name: Error, message: MeetingManager failed to select video input device)
```

**Comment by Nanosync** [comment]
Hi team,

Could I check if there are any updates on this issue?

Thank you.

**Comment by xuesichao** [comment]
@Nanosync I checked the code. The `deviceLabelTrigger` is only used when SDK tries to list device (updateDeviceLists() call). 

So the error here in line 371 will not be thrown when you call `startVideoInputDevice()`. 

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/952f829a8310cba80cdef27aa39ee3fdb374efab/src/providers/MeetingProvider/MeetingManager.ts#L350-L376

The flow is:
1. meetingManager.join()
2. updateDeviceLists()
3. deviceLabelTrigger()

So if you blocked device permission in browser before you call `meetingManager.join()`, the error in line 371 will be printed.



The error message you got is actually from `startVideoInputDevice()` at line 513.
>An error was thrown (name: Error, message: MeetingManager failed to select video input device)
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/952f829a8310cba80cdef27aa39ee3fdb374efab/src/providers/MeetingProvider/MeetingManager.ts#L503-L515

**Comment by xuesichao** [comment]
You're right, we should:
1. throw error directly in `setupDeviceLabelTrigger`.
2. throw the original error from `handleGetUserMediaError` for `start` and `stop` device methods.

Thanks a lot for your investigation, these are really helpful.

**Comment by xuesichao** [comment]
Change is merged into main line and will be released in next version. Closing this for now. Let me know if you have any other thoughts. Thank you!
