### ISSUE TITLE
Support npm 9

### ISSUE THREAD

**Issue by mcqj** [aws/amazon-chime-sdk-component-library-react#905]
### What happened and what did you expect to happen?

package.json specifically required npm 5, 6, 7, 8 but not 9.
So, errors occur if you are using npm 9

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

npm install with npm 9

### Amazon Chime SDK React Components Library version

3.7.0

### What browsers are you seeing the problem on?

NA

### Browser version

NA

### Device Information

NA

### Browser console logs

Not applicable

**Comment by OrrTytocare** [comment]
Any progress on this issue ?

**Comment by suula** [comment]
`node 20` and `npm 10` should be added

**Comment by Tjs002** [comment]
@suula is this issue solved if not can I work on this?

**Comment by suula** [comment]
> @suula is this issue solved if not can I work on this?

By all means

**Comment by ziyiz-amzn** [comment]
The https://github.com/aws/amazon-chime-sdk-component-library-react/pull/935 solved this.
