### ISSUE TITLE
Naaa

### ISSUE THREAD

**Issue by Nishapar** [aws/amazon-chime-sdk-component-library-react#907]
### What are you trying to do?

*For example: I'm trying to run the demo app.*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure a component.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime Component Library Guide, etc.

**Comment by michhyun1** [comment]
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/quick-starts--page
