### ISSUE TITLE
Error when running Amazon Chime SDK Component Library React demo locally

### ISSUE THREAD

**Issue by Schayimerdan** [aws/amazon-chime-sdk-component-library-react#912]
### What happened and what did you expect to happen?

Seeing this issue on the browser:
{"error":"ENOENT: no such file or directory, open 'dist/meeting.html'"}

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Clone the Amazon Chime SDK Component Library React repository to your local machine.
2. Navigate to the amazon-chime-sdk-component-library-react/demo/meeting directory.
3. Run the application locally using `npm start`.

### Amazon Chime SDK React Components Library version

latest

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 115.0.5790.110 (Official Build) (64-bit)

### Device Information

Win11 Desktop 

### Browser console logs

 server caught error: Error: ENOENT: no such file or directory, open 'dist/meeting.html'

**Comment by michhyun1** [comment]
you need to run `npm i && npm run build && npm run start`
