### ISSUE TITLE
Documentation Website - Dark Theme Not working

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws/amazon-chime-sdk-component-library-react#916]
### What are you trying to do?

- Toggle Dark Mode
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/introduction--page&globals=theme:dark

### How can the documentation be improved to help your use case?
![Screenshot 2023-10-25 at 11 44 18 AM](https://github.com/aws/amazon-chime-sdk-component-library-react/assets/11032490/ac2e980a-d4ca-4987-b9b4-4ce108edde40)

N/A

### What documentation have you looked at so far?

N/A

**Comment by josephharkins** [comment]
It's dark mode for the react components.. :)
