### ISSUE TITLE
[FEATURE REQUEST] Add Node.js LTS (20.x) support

### ISSUE THREAD

**Issue by mystafer** [aws/amazon-chime-sdk-component-library-react#923]
## Community Note

* Please do not add additional comments such as "+1" or "me too" to existing issues - instead please vote on the issue by adding a 👍 to the issue. The Amazon Chime SDK team will prioritize the request based on the number of 👍 the issue has received.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues) to see if your request has already been recommended.
* Please do not use this template to report bugs. This repository has an [issue template](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/new/choose) for issues and [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/quick-starts--page) to help with your development.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

## Tell us about your request

The package is missing support for the current Node.js LTS version, which recently changed to 20.10.0.

What do you want us to build?

Add support for Node engine ^20.

How are you currently solving a problem?

Using previous LTS engine.

**Comment by vitiaaap29** [comment]
Guys, we really need NodeJS 20 support. Please add!
