### ISSUE TITLE
Sidebar search input UI issue

### ISSUE THREAD

**Issue by admirhusic** [aws/amazon-chime-sdk-component-library-react#956]
When the sidebar is to narrow the search input gets cut off. Seems like a good first issue. :) 

https://github.com/aws/amazon-chime-sdk-component-library-react/assets/16584154/41d88b7e-61dc-44a4-ad4e-8e8c87e46d00

Os: MacOS
Browser: Chrome

**Comment by michhyun1** [comment]
This is storyboard - those arent components of the react component library.
