### ISSUE TITLE
Video scaling when attendee joins meeting

### ISSUE THREAD

**Issue by laurabrooks** [aws/amazon-chime-sdk-component-library-react#968]
### What happened and what did you expect to happen?

When an attendee joins a meeting, their video scales up from low resolution over the first 10-12 seconds of their meeting session, as viewed in the media capture pipeline recording. I would expect to be able to provide some information when the attendee joins so that we can start the video at the desired resolution.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Create chime meeting and media capture pipeline to record.
2. Join as an attendee with video
    - before turning on video: `meetingManager.audioVideo.chooseVideoInputQuality(960, 540, 30);`
    - has been tested using `NoVideoUplinkBandwidthPolicy` as well as `NScaleVideoUplinkBandwidthPolicy` with each `setHasBandwidthPriority(true)` and `setSVCEnabled(false)`
4. End meeting and review the video. The attendee's video begins at a low resolution and scales up around 10-12 seconds.

### Amazon Chime SDK React Components Library version

3.8.0

### What browsers are you seeing the problem on?

chrome

### Browser version

129.0.6668.100

### Device Information

macOS 13.0

### Meeting and Attendee ID Information.

meeting id: `f0a95c3a-33df-4193-b412-7a600e632713`
attendee id: `0f8ed7e8-ea29-6d1a-6b24-7ea97af50164`

### Browser console logs

[localhost.log](https://github.com/user-attachments/files/17557901/localhost.log)

### Add any other context about the problem here.

first seconds of video:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/5489866f-fdb0-48d4-8638-bd0a54f4627f">

after 12 seconds:
<img width="543" alt="image" src="https://github.com/user-attachments/assets/00379229-2507-450d-97aa-f4d4f1b457ef">

**Comment by hensmi-amazon** [comment]
Basically, the browser by default starts sending at 300kbps before increasing it (as long as the network is clear). It may lower resolution to work around the lower value. It's a reasonable decision, but I find it to still be a bit unnecessarily defensive. In https://github.com/aws/amazon-chime-sdk-js/pull/2987 i raised it to 1000kbps. In this case it should start sending 540p immediately.
